#!/usr/bin/env bash
set -euo pipefail

simulation_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
manifest="${simulation_dir}/manifest.lua"
temporary_manifest="$(mktemp "${simulation_dir}/manifest.lua.XXXXXX")"
trap 'rm -f -- "${temporary_manifest}"' EXIT

{
  echo "-- Generated by update-manifest.sh. Do not hand-edit."
  echo "return {"
  while IFS= read -r filename; do
    printf '  "%s",\n' "${filename}"
  done < <(find "${simulation_dir}" -maxdepth 1 -type f -name '*.zip' -printf '%f\n' | LC_ALL=C sort)
  echo "}"
} > "${temporary_manifest}"

mv -- "${temporary_manifest}" "${manifest}"
trap - EXIT
