require("prototypes.updates.resource-placement")
require("prototypes.updates.recipe-tweaks")
require("prototypes.updates.rocket-reusability-final-fixes")
require("prototypes.updates.factoriopedia")
require("prototypes.recipes.flux-condensing")
require("prototypes.updates.crafting-tabs")
require("prototypes.updates.flux-tooltips")
