require("prototypes.resources.flux-rift-resource")
require("prototypes.resources.ores")
require("prototypes.resources.shattered-flux-vents")
require("prototypes.entities.flux-quarry")
require("prototypes.entities.flux-processing-machines")
require("prototypes.entities.flux-condenser")
require("prototypes.entities.late-utility")
require("prototypes.entities.expansion-machines")
require("prototypes.entities.advanced-expansion-machines")
require("prototypes.items.crafting-tabs")
require("prototypes.items.advanced-materials")
require("prototypes.items.chemistry-materials")
require("prototypes.items.metal-plates")
require("prototypes.items.flux-systems")
require("prototypes.items.progression-components")
require("prototypes.items.expansion-systems")
require("prototypes.items.advanced-expansion-systems")
require("prototypes.technology.comminution")
require("prototypes.technology.flux-extraction")
require("prototypes.technology.flux-mining-productivity")
require("prototypes.technology.material-processing")
require("prototypes.technology.liquid-mining")
require("prototypes.technology.industrial-expansion")
require("prototypes.technology.flux-systems")
require("prototypes.technology.progression-components")
require("prototypes.fluids.fluids")
require("prototypes.fluids.chemistry-fluids")
require("prototypes.recipes.advanced-materials")
require("prototypes.recipes.chemistry-processes")
require("prototypes.recipes.industrial-processes")
require("prototypes.recipes.bonus-processes")
require("prototypes.recipes.metal-plates")
require("prototypes.recipes.transmutation-recipes")
require("prototypes.recipes.flux-systems")
require("prototypes.recipes.progression-components")
require("prototypes.recipes.expansion-processes")
require("prototypes.recipes.advanced-expansion-processes")
require("prototypes.recipes.space-age-symbiosis")
require("prototypes.recipes.shattered-campaign")
require("prototypes.technology.expansion-systems")
require("prototypes.technology.flux-bonuses")
require("prototypes.technology.advanced-expansion-systems")
require("prototypes.technology.space-age-symbiosis")
require("prototypes.technology.shattered-campaign")
require("prototypes.technology.krastorio-logistics")
require("prototypes.not-stolen-things.krastorio-logistics")
require("prototypes.updates.shattered-planet")
require("prototypes.updates.resource-placement")
require("prototypes.updates.rocket-reusability")
require("prototypes.updates.flux-asteroids")

-- FluxWorks fluids use dedicated pipe/tank logistics and should not generate
-- vanilla barrel items whose graphics would become part of our visual identity.
for name, fluid in pairs(data.raw.fluid or {}) do
  if string.sub(name, 1, 3) == "fw-" then
    fluid.auto_barrel = false
  end
end
