data:extend({
  {
    type = "string-setting",
    name = "fw-difficulty-mode",
    setting_type = "startup",
    default_value = "normal",
    allowed_values = { "easy", "normal", "hard" },
    order = "a[core]-a[difficulty-mode]",
  },
  {
    type = "bool-setting",
    name = "fw-enable-recipe-integration",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-b[recipe-integration]",
  },
  {
    type = "bool-setting",
    name = "fw-enable-crafting-tab-reorganization",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-c[crafting-tabs]",
  },
  {
    type = "bool-setting",
    name = "fw-difficulty-affects-fluid-systems",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-d[difficulty-fluid]",
  },
  {
    type = "bool-setting",
    name = "fw-difficulty-affects-control-systems",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-e[difficulty-control]",
  },
  {
    type = "bool-setting",
    name = "fw-difficulty-affects-late-machines",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-f[difficulty-late]",
  },
  {
    type = "bool-setting",
    name = "fw-difficulty-affects-orbital-recipes",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-g[difficulty-orbital]",
  },
  {
    type = "bool-setting",
    name = "fw-enable-science-pack-overhaul",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-h[science-overhaul]",
  },
  {
    type = "bool-setting",
    name = "fw-enable-core-material-replacements",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-i[core-materials]",
  },
  {
    type = "bool-setting",
    name = "fw-enable-combat-recipe-integration",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-j[combat-integration]",
  },
  {
    type = "bool-setting",
    name = "fw-enable-orbital-and-planetary-integration",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-k[orbital-planetary]",
  },
  {
    type = "bool-setting",
    name = "fw-enable-machine-part-rehoming",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-l[machine-rehoming]",
  },
  {
    type = "bool-setting",
    name = "enable-incomplete-rocket-parts",
    setting_type = "startup",
    default_value = true,
    order = "a[core]-m[incomplete-rocket-parts]",
  },
  {
    type = "bool-setting",
    name = "enable-incomplete-rocket-parts-productivity",
    setting_type = "startup",
    default_value = false,
    order = "a[core]-n[incomplete-rocket-productivity]",
  },
  {
    type = "bool-setting",
    name = "fw-difficulty-affects-science-recipes",
    setting_type = "startup",
    default_value = true,
    order = "z[extras]-a[difficulty-science]",
  },
  {
    type = "bool-setting",
    name = "fw-difficulty-affects-flux-core-recipes",
    setting_type = "startup",
    default_value = true,
    order = "z[extras]-b[difficulty-flux-core]",
  },
  {
    type = "bool-setting",
    name = "fw-difficulty-affects-crafting-time",
    setting_type = "startup",
    default_value = true,
    order = "z[extras]-c[difficulty-crafting-time]",
  },
  {
    type = "bool-setting",
    name = "fw-tab-science-organization",
    setting_type = "startup",
    default_value = true,
    order = "z[extras]-d[tabs-science]",
  },
  {
    type = "bool-setting",
    name = "fw-tab-bioprocessing-organization",
    setting_type = "startup",
    default_value = true,
    order = "z[extras]-e[tabs-bioprocessing]",
  },
  {
    type = "bool-setting",
    name = "fw-tab-chemistry-organization",
    setting_type = "startup",
    default_value = true,
    order = "z[extras]-f[tabs-chemistry]",
  },
  {
    type = "bool-setting",
    name = "fw-tab-flux-organization",
    setting_type = "startup",
    default_value = true,
    order = "z[extras]-g[tabs-flux]",
  },
  {
    type = "bool-setting",
    name = "fw-tab-fabrication-organization",
    setting_type = "startup",
    default_value = true,
    order = "z[extras]-h[tabs-fabrication]",
  },
})
