local util = require("util")
local Startup = require("prototypes.lib.startup-settings")
local styles = data.raw["gui-style"].default

local origin_difficulty = Startup.difficulty_tier("fw-balance-origin-singularity-difficulty", "normal")
local origin_buffer_capacity = ({
  easy = "30GJ",
  normal = "120GJ",
  hard = "240GJ",
})[origin_difficulty] or "120GJ"

local rift_logistics = ({
  easy = { buffer = "4GJ", input = "500MW" },
  normal = { buffer = "10GJ", input = "1GW" },
  hard = { buffer = "20GJ", input = "1500MW" },
})[Startup.difficulty_tier("fw-balance-rift-logistics", "normal")]

styles.fw_memory_entity_preview = {
  type = "empty_widget_style",
  vertically_stretchable = "on",
  horizontally_stretchable = "on",
  padding = 0,
  graphical_set = {
    base = {
      position = { 17, 0 },
      corner_size = 8,
      center = { position = { 76, 8 }, size = { 1, 1 } },
      draw_type = "outer",
    },
    shadow = default_inner_shadow,
  },
}

local circuit_wire_connection_points = {
  shadow = {
    green = { 0.0, 0.0 },
    red = { 0.0, 0.0 },
  },
  wire = {
    green = { 0.0, 0.0 },
    red = { 0.0, 0.0 },
  },
}

circuit_wire_connection_points = {
  circuit_wire_connection_points,
  circuit_wire_connection_points,
  circuit_wire_connection_points,
  circuit_wire_connection_points,
}

local nothing = {
  filename = "__FluxWorksAssets__/graphics/late-utility/deep-storage-unit/nothing.png",
  priority = "extra-high",
  size = 1,
}

local phase_vault = {
  type = "container",
  name = "fw-phase-vault",
  icon = "__FluxWorksAssets__/graphics/icons/items/deep-storage-unit/memory-unit.png",
  icon_size = 64,
  inventory_size = 300,
  picture = {
    layers = {
      {
        filename = "__FluxWorksAssets__/graphics/late-utility/deep-storage-unit/memory-unit.png",
        width = 256,
        height = 256,
        priority = "high",
        scale = 0.5,
        shift = util.by_pixel(0, 0),
      },
      {
        filename = "__FluxWorksAssets__/graphics/late-utility/deep-storage-unit/hr-memory-unit.png",
        width = 512,
        height = 512,
        priority = "high",
        scale = 0.25,
        shift = util.by_pixel(0, 0),
      },
    },
  },
  max_health = 3000,
  minable = { mining_time = 1, result = "fw-phase-vault" },
  corpse = "big-remnants",
  close_sound = {
    filename = "__base__/sound/metallic-chest-close.ogg",
    volume = 0.9,
  },
  open_sound = {
    filename = "__base__/sound/metallic-chest-open.ogg",
    volume = 0.6,
  },
  selection_box = { { -1.55, -1.55 }, { 1.55, 1.55 } },
  collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
  flags = { "placeable-neutral", "player-creation", "not-rotatable" },
  enable_inventory_bar = false,
  not_inventory_moveable = true,
  inventory_type = "with_filters_and_bar",
}

local spectral_reservoir = {
  type = "storage-tank",
  name = "fw-spectral-reservoir",
  icon = "__FluxWorksAssets__/graphics/icons/items/fluid-memory-storage/fluid-memory-unit.png",
  icon_size = 64,
  fluid_box = {
    volume = 120000,
    pipe_covers = pipecoverspictures(),
    pipe_connections = {
      { position = { 0, 1 }, direction = defines.direction.south, hide_connection_info = false },
      { position = { 0, -1 }, direction = defines.direction.north, hide_connection_info = false },
      { position = { 1, 0 }, direction = defines.direction.east, hide_connection_info = false },
      { position = { -1, 0 }, direction = defines.direction.west, hide_connection_info = false },
    },
    base_level = -1,
  },
  two_direction_only = true,
  collision_box = { { -1.1, -1.1 }, { 1.1, 1.1 } },
  selection_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
  window_bounding_box = { { -0.95, -0.95 }, { 0.95, 0.95 } },
  pictures = {
    picture = {
      filename = "__FluxWorksAssets__/graphics/late-utility/fluid-memory-storage/fluid-memory-unit.png",
      priority = "high",
      size = { 256, 256 },
      shift = util.by_pixel(0, 0),
      scale = 0.5,
    },
  },
  flow_length_in_ticks = 360,
  corpse = "medium-remnants",
  flags = { "player-creation", "placeable-neutral", "not-rotatable" },
  placeable_by = { item = "fw-spectral-reservoir", count = 1 },
  minable = { result = "fw-spectral-reservoir", mining_time = 1 },
  max_health = 1500,
  not_inventory_moveable = true,
}

local rift_exchange_gate = {
  type = "container",
  name = "fw-rift-exchange-gate",
  icon = "__FluxWorksAssets__/graphics/icons/items/late-utility/fw-rift-exchange-gate.png",
  icon_size = 64,
  inventory_size = 48,
  picture = {
    filename = "__FluxWorksAssets__/graphics/late-utility/rift-exchange-gate/rift-exchange-gate.png",
    width = 1254,
    height = 1254,
    shift = util.by_pixel(0, -10),
    scale = 0.30,
  },
  max_health = 4000,
  minable = { mining_time = 1, result = "fw-rift-exchange-gate" },
  corpse = "beacon-remnants",
  close_sound = {
    filename = "__base__/sound/metallic-chest-close.ogg",
    volume = 0.9,
  },
  open_sound = {
    filename = "__base__/sound/metallic-chest-open.ogg",
    volume = 0.6,
  },
  -- The 1254 px render occupies almost a full 12 x 12 tile footprint at 0.30 scale.
  -- Keep the collision close to the visible chassis so players cannot walk through
  -- the tanks and corner machinery while retaining a small placement margin.
  selection_box = { { -5.8, -5.8 }, { 5.8, 5.8 } },
  collision_box = { { -5.65, -5.65 }, { 5.65, 5.65 } },
  flags = { "placeable-neutral", "player-creation", "not-rotatable" },
  circuit_connector = circuit_connector_definitions["chest"],
  circuit_wire_max_distance = default_circuit_wire_max_distance,
  enable_inventory_bar = false,
  not_inventory_moveable = true,
}

local rift_exchange_fluid_gate = {
  type = "storage-tank",
  name = "fw-rift-exchange-fluid-gate",
  icon = "__FluxWorksAssets__/graphics/icons/items/late-utility/fw-rift-exchange-fluid-gate.png",
  icon_size = 64,
  fluid_box = {
    volume = 200000,
    pipe_covers = pipecoverspictures(),
    pipe_connections = {
      -- The rendered manifolds terminate on the centre line at the outer edge.
      { flow_direction = "input-output", direction = defines.direction.north, position = { 0, -5.6 }, hide_connection_info = false },
      { flow_direction = "input-output", direction = defines.direction.south, position = { 0, 5.6 }, hide_connection_info = false },
    },
    base_level = -1,
  },
  collision_box = { { -5.65, -5.65 }, { 5.65, 5.65 } },
  selection_box = { { -5.8, -5.8 }, { 5.8, 5.8 } },
  window_bounding_box = { { -5.1, -5.1 }, { 5.1, 5.1 } },
  pictures = {
    picture = {
      filename = "__FluxWorksAssets__/graphics/late-utility/rift-exchange-gate/rift-exchange-fluid-gate.png",
      width = 1254,
      height = 1254,
      priority = "high",
      shift = util.by_pixel(0, -2),
      scale = 0.30,
    },
  },
  flow_length_in_ticks = 360,
  corpse = "medium-remnants",
  flags = { "placeable-neutral", "player-creation", "not-rotatable" },
  circuit_connector = circuit_connector_definitions["storage-tank"],
  circuit_wire_max_distance = default_circuit_wire_max_distance,
  placeable_by = { item = "fw-rift-exchange-fluid-gate", count = 1 },
  minable = { mining_time = 1, result = "fw-rift-exchange-fluid-gate" },
  max_health = 4000,
  not_inventory_moveable = true,
}

local origin_singularity = {
  type = "container",
  name = "fw-origin-singularity",
  icon = "__FluxWorksAssets__/graphics/icons/items/origin-projects/fw-origin-singularity.png",
  icon_size = 256,
  inventory_size = 1,
  picture = {
    layers = {
      {
        filename = "__finely-crafted-graphics__/graphics/fusion-reactor/fusion-reactor-hr-shadow.png",
        width = 700,
        height = 600,
        shift = util.by_pixel(20, 42),
        scale = 1.28,
        draw_as_shadow = true,
      },
      {
        filename = "__finely-crafted-graphics__/graphics/fusion-reactor/fusion-reactor-hr-animation.png",
        width = 400,
        height = 400,
        frame_count = 1,
        line_length = 1,
        shift = util.by_pixel(0, -8),
        scale = 1.58,
      },
      {
        filename = "__FluxWorksAssets__/graphics/late-utility/rift-exchange-gate/rift-exchange-fluid-gate.png",
        width = 1254,
        height = 1254,
        shift = util.by_pixel(0, -4),
        scale = 0.50,
        draw_as_glow = true,
      },
    },
  },
  max_health = 5000,
  minable = { mining_time = 2, result = "fw-origin-singularity" },
  corpse = "big-remnants",
  close_sound = {
    filename = "__base__/sound/metallic-chest-close.ogg",
    volume = 0.9,
  },
  open_sound = {
    filename = "__base__/sound/metallic-chest-open.ogg",
    volume = 0.6,
  },
  selection_box = { { -5.2, -5.2 }, { 5.2, 5.2 } },
  collision_box = { { -3.6, -3.6 }, { 3.6, 3.6 } },
  flags = { "placeable-neutral", "player-creation", "not-rotatable" },
  enable_inventory_bar = false,
  not_inventory_moveable = true,
}

data:extend({
  {
    type = "item-with-tags",
    name = "fw-phase-vault-packed",
    icons = {
      {
        icon = "__FluxWorksAssets__/graphics/icons/items/deep-storage-unit/memory-unit.png",
        icon_size = 64,
        scale = 0.5,
      },
      {
        icon = "__FluxWorksAssets__/graphics/icons/items/deep-storage-unit/packing-tape-50.png",
        icon_size = 64,
        icon_mipmaps = 4,
      },
    },
    weight = 10000000,
    stack_size = 1,
    place_result = "fw-phase-vault",
    subgroup = "fw-flux-exchange",
    order = "b[fw-phase-vault-packed]",
    localised_name = { "", { "entity-name.fw-phase-vault" }, " (Packed)" },
    localised_description = { "entity-description.fw-phase-vault" },
    flags = { "not-stackable" },
    hidden = true,
  },
  {
    type = "item-with-tags",
    name = "fw-spectral-reservoir-packed",
    icons = {
      {
        icon = "__FluxWorksAssets__/graphics/icons/items/fluid-memory-storage/fluid-memory-unit.png",
        icon_size = 64,
        scale = 0.5,
      },
      {
        icon = "__FluxWorksAssets__/graphics/icons/items/fluid-memory-storage/packing-tape-50.png",
        icon_size = 64,
        icon_mipmaps = 4,
      },
    },
    weight = 10000000,
    stack_size = 1,
    place_result = "fw-spectral-reservoir",
    subgroup = "fw-flux-exchange",
    order = "c[fw-spectral-reservoir-packed]",
    localised_name = { "", { "entity-name.fw-spectral-reservoir" }, " (Packed)" },
    localised_description = { "entity-description.fw-spectral-reservoir" },
    flags = { "not-stackable" },
    hidden = true,
  },
  {
    type = "animation",
    name = "fw-spectral-reservoir-fluid-animation",
    filename = "__FluxWorksAssets__/graphics/late-utility/fluid-memory-storage/fluid-background.png",
    priority = "extra-high",
    size = { 256, 256 },
    shift = { 0.25, -0.0625 },
    scale = 0.5,
    frame_count = 16,
    line_length = 8,
    apply_runtime_tint = true,
  },
  {
    type = "item-with-inventory",
    name = "fw-memory-gui-item",
    inventory_size = 1,
    item_filters = { "fw-memory-gui-item" },
    stack_size = 1,
    icon = "__core__/graphics/empty.png",
    icon_size = 1,
    localised_name = "",
    flags = { "not-stackable" },
    hidden = true,
  },
  {
    type = "sprite",
    name = "fw-bulk-insert",
    filename = "__FluxWorksAssets__/graphics/icons/items/deep-storage-unit/insert.png",
    size = { 100, 100 },
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "fw-bulk-extract",
    filename = "__FluxWorksAssets__/graphics/icons/items/deep-storage-unit/extract.png",
    size = { 100, 100 },
    flags = { "gui-icon" },
  },
  {
    type = "electric-energy-interface",
    name = "fw-phase-vault-power-interface",
    localised_name = { "entity-name.fw-phase-vault" },
    localised_description = { "entity-description.fw-phase-vault" },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      buffer_capacity = "1J",
    },
    energy_usage = "1000W",
    collision_box = { { -2.7, -2.7 }, { 2.7, 2.7 } },
    collision_mask = { layers = {} },
    selectable_in_game = false,
    remove_decoratives = "false",
    icon = "__FluxWorksAssets__/graphics/icons/items/deep-storage-unit/memory-unit.png",
    icon_size = 64,
    quality_indicator_scale = 0,
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-selectable-in-game",
      "not-rotatable",
      "not-flammable",
      "placeable-off-grid",
    },
  },
  {
    type = "electric-energy-interface",
    name = "fw-spectral-reservoir-power-interface",
    localised_name = { "entity-name.fw-spectral-reservoir" },
    localised_description = { "entity-description.fw-spectral-reservoir" },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      buffer_capacity = "1J",
    },
    energy_usage = "1000W",
    collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
    collision_mask = { layers = {} },
    selectable_in_game = false,
    remove_decoratives = "false",
    icon = "__FluxWorksAssets__/graphics/icons/items/fluid-memory-storage/fluid-memory-unit.png",
    icon_size = 64,
    quality_indicator_scale = 0,
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-selectable-in-game",
      "not-rotatable",
      "not-flammable",
      "placeable-off-grid",
    },
  },
  {
    type = "electric-energy-interface",
    name = "fw-rift-exchange-fluid-power-interface",
    localised_name = { "entity-name.fw-rift-exchange-fluid-gate" },
    localised_description = { "entity-description.fw-rift-exchange-fluid-gate" },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      buffer_capacity = rift_logistics.buffer,
      input_flow_limit = rift_logistics.input,
    },
    energy_usage = "0W",
    collision_box = { { -3.9, -4.6 }, { 3.9, 4.6 } },
    collision_mask = { layers = {} },
    selectable_in_game = false,
    remove_decoratives = "false",
    icon = "__FluxWorksAssets__/graphics/icons/items/late-utility/fw-rift-exchange-fluid-gate.png",
    icon_size = 64,
    quality_indicator_scale = 0,
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-selectable-in-game",
      "not-rotatable",
      "not-flammable",
      "placeable-off-grid",
    },
  },
  {
    type = "electric-energy-interface",
    name = "fw-origin-singularity-power-interface",
    localised_name = { "entity-name.fw-origin-singularity" },
    localised_description = { "entity-description.fw-origin-singularity" },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      buffer_capacity = origin_buffer_capacity,
      input_flow_limit = "250MW",
    },
    energy_usage = "0W",
    collision_box = { { -3.6, -3.6 }, { 3.6, 3.6 } },
    collision_mask = { layers = {} },
    selectable_in_game = false,
    remove_decoratives = "false",
    icon = "__FluxWorksAssets__/graphics/icons/items/origin-projects/fw-origin-singularity.png",
    icon_size = 256,
    quality_indicator_scale = 0,
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-selectable-in-game",
      "not-rotatable",
      "not-flammable",
      "placeable-off-grid",
    },
  },
  {
    type = "electric-energy-interface",
    name = "fw-rift-exchange-power-interface",
    localised_name = { "entity-name.fw-rift-exchange-gate" },
    localised_description = { "entity-description.fw-rift-exchange-gate" },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      buffer_capacity = rift_logistics.buffer,
      input_flow_limit = rift_logistics.input,
    },
    energy_usage = "0W",
    collision_box = { { -3.9, -3.9 }, { 3.9, 3.9 } },
    collision_mask = { layers = {} },
    selectable_in_game = false,
    remove_decoratives = "false",
    icon = "__FluxWorksAssets__/graphics/icons/items/late-utility/fw-rift-exchange-gate.png",
    icon_size = 64,
    quality_indicator_scale = 0,
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-selectable-in-game",
      "not-rotatable",
      "not-flammable",
      "placeable-off-grid",
    },
  },
  {
    type = "constant-combinator",
    name = "fw-phase-vault-combinator",
    icon = "__FluxWorksAssets__/graphics/icons/items/deep-storage-unit/memory-unit.png",
    icon_size = 64,
    quality_indicator_scale = 0,
    item_slot_count = 1,
    collision_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    circuit_wire_connection_points = circuit_wire_connection_points,
    circuit_wire_max_distance = 9,
    sprites = nothing,
    activity_led_sprites = nothing,
    activity_led_light_offsets = { { 0, 0 }, { 0, 0 }, { 0, 0 }, { 0, 0 } },
    collision_mask = { layers = {} },
    remove_decoratives = "false",
    selection_priority = 51,
    placeable_by = { item = "fw-phase-vault", count = 0 },
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-deconstructable",
      "not-flammable",
      "not-upgradable",
      "not-rotatable",
      "hide-alt-info",
      "placeable-off-grid",
    },
  },
  {
    type = "constant-combinator",
    name = "fw-spectral-reservoir-combinator",
    icon = "__FluxWorksAssets__/graphics/icons/items/fluid-memory-storage/fluid-memory-unit.png",
    icon_size = 64,
    quality_indicator_scale = 0,
    item_slot_count = 1,
    collision_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    circuit_wire_connection_points = circuit_wire_connection_points,
    circuit_wire_max_distance = 12,
    sprites = nothing,
    activity_led_sprites = nothing,
    activity_led_light_offsets = { { 0, 0 }, { 0, 0 }, { 0, 0 }, { 0, 0 } },
    collision_mask = { layers = {} },
    remove_decoratives = "false",
    selection_priority = 51,
    placeable_by = { item = "fw-spectral-reservoir", count = 0 },
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-deconstructable",
      "not-flammable",
      "not-upgradable",
      "not-rotatable",
      "hide-alt-info",
      "placeable-off-grid",
    },
  },
  phase_vault,
  spectral_reservoir,
  rift_exchange_gate,
  rift_exchange_fluid_gate,
  origin_singularity,
})
