local util = require("util")

local styles = data.raw["gui-style"].default

styles.fw_memory_entity_preview = {
  type = "empty_widget_style",
  vertically_stretchable = "on",
  horizontally_stretchable = "on",
  padding = 0,
  graphical_set = {
    base = {
      position = { 17, 0 },
      corner_size = 8,
      center = { position = { 76, 8 }, size = { 1, 1 } },
      draw_type = "outer",
    },
    shadow = default_inner_shadow,
  },
}

local circuit_wire_connection_points = {
  shadow = {
    green = { 0.0, 0.0 },
    red = { 0.0, 0.0 },
  },
  wire = {
    green = { 0.0, 0.0 },
    red = { 0.0, 0.0 },
  },
}

circuit_wire_connection_points = {
  circuit_wire_connection_points,
  circuit_wire_connection_points,
  circuit_wire_connection_points,
  circuit_wire_connection_points,
}

local nothing = {
  filename = "__FluxWorks__/graphics/late-utility/deep-storage-unit/nothing.png",
  priority = "extra-high",
  size = 1,
}

local phase_vault = {
  type = "container",
  name = "fw-phase-vault",
  icon = "__FluxWorks__/graphics/icons/items/deep-storage-unit/memory-unit.png",
  icon_size = 64,
  icon_mipmaps = 4,
  inventory_size = 300,
  picture = {
    filename = "__FluxWorks__/graphics/late-utility/deep-storage-unit/memory-unit.png",
    height = 256,
    width = 256,
    priority = "high",
    shift = { 0.59375, 0 },
    hr_version = {
      filename = "__FluxWorks__/graphics/late-utility/deep-storage-unit/hr-memory-unit.png",
      height = 512,
      width = 512,
      priority = "high",
      scale = 0.5,
      shift = { 0.59375, 0 },
    },
  },
  max_health = 3000,
  minable = { mining_time = 1, result = "fw-phase-vault" },
  corpse = "big-remnants",
  close_sound = {
    filename = "__base__/sound/metallic-chest-close.ogg",
    volume = 0.9,
  },
  open_sound = {
    filename = "__base__/sound/metallic-chest-open.ogg",
    volume = 0.6,
  },
  selection_box = { { -3, -3 }, { 3, 3 } },
  collision_box = { { -2.7, -2.7 }, { 2.7, 2.7 } },
  flags = { "placeable-neutral", "player-creation", "not-rotatable" },
  enable_inventory_bar = false,
  not_inventory_moveable = true,
  inventory_type = "with_filters_and_bar",
}

local spectral_reservoir = {
  type = "storage-tank",
  name = "fw-spectral-reservoir",
  icon = "__FluxWorks__/graphics/icons/items/fluid-memory-storage/fluid-memory-unit.png",
  icon_size = 64,
  icon_mipmaps = 4,
  fluid_box = {
    volume = 120000,
    pipe_covers = pipecoverspictures(),
    pipe_connections = {
      { position = { 0, 1 }, direction = defines.direction.south },
      { position = { 0, -1 }, direction = defines.direction.north },
      { position = { 1, 0 }, direction = defines.direction.east },
      { position = { -1, 0 }, direction = defines.direction.west },
    },
    hide_connection_info = true,
    base_level = -1,
  },
  two_direction_only = true,
  collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
  selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
  window_bounding_box = { { -1, -1 }, { 1, 1 } },
  pictures = {
    picture = {
      filename = "__FluxWorks__/graphics/late-utility/fluid-memory-storage/fluid-memory-unit.png",
      priority = "high",
      size = { 256, 256 },
      shift = { 0.25, -0.0625 },
      scale = 0.5,
    },
  },
  flow_length_in_ticks = 360,
  corpse = "medium-remnants",
  flags = { "player-creation", "placeable-neutral", "not-rotatable" },
  placeable_by = { item = "fw-spectral-reservoir", count = 1 },
  minable = { result = "fw-spectral-reservoir", mining_time = 1 },
  max_health = 1500,
  not_inventory_moveable = true,
}

local rift_exchange_gate = {
  type = "container",
  name = "fw-rift-exchange-gate",
  icon = "__FluxWorks__/graphics/icons/items/late-utility/fw-rift-exchange-gate.png",
  icon_size = 1024,
  inventory_size = 48,
  picture = {
    filename = "__FluxWorks__/graphics/late-utility/rift-exchange-gate/rift-exchange-gate.png",
    width = 1024,
    height = 1024,
    shift = util.by_pixel(0, -6),
    scale = 0.18,
  },
  max_health = 2200,
  minable = { mining_time = 1, result = "fw-rift-exchange-gate" },
  corpse = "beacon-remnants",
  close_sound = {
    filename = "__base__/sound/metallic-chest-close.ogg",
    volume = 0.9,
  },
  open_sound = {
    filename = "__base__/sound/metallic-chest-open.ogg",
    volume = 0.6,
  },
  selection_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
  collision_box = { { -2.1, -2.1 }, { 2.1, 2.1 } },
  flags = { "placeable-neutral", "player-creation", "not-rotatable" },
  enable_inventory_bar = false,
  not_inventory_moveable = true,
}

data:extend({
  {
    type = "item-with-tags",
    name = "fw-phase-vault-packed",
    icons = {
      {
        icon = "__FluxWorks__/graphics/icons/items/deep-storage-unit/memory-unit.png",
        icon_size = 64,
        scale = 0.5,
      },
      {
        icon = "__FluxWorks__/graphics/icons/items/deep-storage-unit/packing-tape-50.png",
        icon_size = 64,
        icon_mipmaps = 4,
      },
    },
    weight = 10000000,
    stack_size = 1,
    place_result = "fw-phase-vault",
    subgroup = "fw-flux-exchange",
    order = "b[fw-phase-vault-packed]",
    localised_name = { "", { "entity-name.fw-phase-vault" }, " (Packed)" },
    localised_description = { "entity-description.fw-phase-vault" },
    flags = { "not-stackable" },
    hidden = true,
  },
  {
    type = "item-with-tags",
    name = "fw-spectral-reservoir-packed",
    icons = {
      {
        icon = "__FluxWorks__/graphics/icons/items/fluid-memory-storage/fluid-memory-unit.png",
        icon_size = 64,
        scale = 0.5,
      },
      {
        icon = "__FluxWorks__/graphics/icons/items/fluid-memory-storage/packing-tape-50.png",
        icon_size = 64,
        icon_mipmaps = 4,
      },
    },
    weight = 10000000,
    stack_size = 1,
    place_result = "fw-spectral-reservoir",
    subgroup = "fw-flux-exchange",
    order = "c[fw-spectral-reservoir-packed]",
    localised_name = { "", { "entity-name.fw-spectral-reservoir" }, " (Packed)" },
    localised_description = { "entity-description.fw-spectral-reservoir" },
    flags = { "not-stackable" },
    hidden = true,
  },
  {
    type = "animation",
    name = "fw-spectral-reservoir-fluid-animation",
    filename = "__FluxWorks__/graphics/late-utility/fluid-memory-storage/fluid-background.png",
    priority = "extra-high",
    size = { 256, 256 },
    shift = { 0.25, -0.0625 },
    scale = 0.5,
    frame_count = 16,
    line_length = 8,
    apply_runtime_tint = true,
  },
  {
    type = "item-with-inventory",
    name = "fw-memory-gui-item",
    inventory_size = 1,
    item_filters = { "fw-memory-gui-item" },
    stack_size = 1,
    icon = "__core__/graphics/empty.png",
    icon_size = 1,
    localised_name = "",
    flags = { "not-stackable" },
    hidden = true,
  },
  {
    type = "sprite",
    name = "fw-bulk-insert",
    filename = "__FluxWorks__/graphics/icons/items/deep-storage-unit/insert.png",
    size = { 100, 100 },
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "fw-bulk-extract",
    filename = "__FluxWorks__/graphics/icons/items/deep-storage-unit/extract.png",
    size = { 100, 100 },
    flags = { "gui-icon" },
  },
  {
    type = "electric-energy-interface",
    name = "fw-phase-vault-power-interface",
    localised_name = { "entity-name.fw-phase-vault" },
    localised_description = { "entity-description.fw-phase-vault" },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      buffer_capacity = "1J",
    },
    energy_usage = "1000W",
    collision_box = { { -2.7, -2.7 }, { 2.7, 2.7 } },
    collision_mask = { layers = {} },
    selectable_in_game = false,
    remove_decoratives = "false",
    icon = "__FluxWorks__/graphics/icons/items/deep-storage-unit/memory-unit.png",
    icon_size = 64,
    icon_mipmaps = 4,
    quality_indicator_scale = 0,
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-selectable-in-game",
      "not-rotatable",
      "not-flammable",
      "placeable-off-grid",
    },
  },
  {
    type = "electric-energy-interface",
    name = "fw-spectral-reservoir-power-interface",
    localised_name = { "entity-name.fw-spectral-reservoir" },
    localised_description = { "entity-description.fw-spectral-reservoir" },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      buffer_capacity = "1J",
    },
    energy_usage = "1000W",
    collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
    collision_mask = { layers = {} },
    selectable_in_game = false,
    remove_decoratives = "false",
    icon = "__FluxWorks__/graphics/icons/items/fluid-memory-storage/fluid-memory-unit.png",
    icon_size = 64,
    icon_mipmaps = 4,
    quality_indicator_scale = 0,
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-selectable-in-game",
      "not-rotatable",
      "not-flammable",
      "placeable-off-grid",
    },
  },
  {
    type = "electric-energy-interface",
    name = "fw-rift-exchange-power-interface",
    localised_name = { "entity-name.fw-rift-exchange-gate" },
    localised_description = { "entity-description.fw-rift-exchange-gate" },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      buffer_capacity = "3GJ",
      input_flow_limit = "150MW",
    },
    energy_usage = "0W",
    collision_box = { { -2.1, -2.1 }, { 2.1, 2.1 } },
    collision_mask = { layers = {} },
    selectable_in_game = false,
    remove_decoratives = "false",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-rift-stabilizer.png",
    icon_size = 1024,
    quality_indicator_scale = 0,
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-selectable-in-game",
      "not-rotatable",
      "not-flammable",
      "placeable-off-grid",
    },
  },
  {
    type = "constant-combinator",
    name = "fw-phase-vault-combinator",
    icon = "__FluxWorks__/graphics/icons/items/deep-storage-unit/memory-unit.png",
    icon_size = 64,
    icon_mipmaps = 4,
    quality_indicator_scale = 0,
    item_slot_count = 1,
    collision_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    circuit_wire_connection_points = circuit_wire_connection_points,
    circuit_wire_max_distance = 9,
    sprites = nothing,
    activity_led_sprites = nothing,
    activity_led_light_offsets = { { 0, 0 }, { 0, 0 }, { 0, 0 }, { 0, 0 } },
    collision_mask = { layers = {} },
    remove_decoratives = "false",
    selection_priority = 51,
    placeable_by = { item = "fw-phase-vault", count = 0 },
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-deconstructable",
      "not-flammable",
      "not-upgradable",
      "not-rotatable",
      "hide-alt-info",
      "placeable-off-grid",
    },
  },
  {
    type = "constant-combinator",
    name = "fw-spectral-reservoir-combinator",
    icon = "__FluxWorks__/graphics/icons/items/fluid-memory-storage/fluid-memory-unit.png",
    icon_size = 64,
    icon_mipmaps = 4,
    quality_indicator_scale = 0,
    item_slot_count = 1,
    collision_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    circuit_wire_connection_points = circuit_wire_connection_points,
    circuit_wire_max_distance = 12,
    sprites = nothing,
    activity_led_sprites = nothing,
    activity_led_light_offsets = { { 0, 0 }, { 0, 0 }, { 0, 0 }, { 0, 0 } },
    collision_mask = { layers = {} },
    remove_decoratives = "false",
    selection_priority = 51,
    placeable_by = { item = "fw-spectral-reservoir", count = 0 },
    hidden = true,
    flags = {
      "placeable-neutral",
      "not-deconstructable",
      "not-flammable",
      "not-upgradable",
      "not-rotatable",
      "hide-alt-info",
      "placeable-off-grid",
    },
  },
  phase_vault,
  spectral_reservoir,
  rift_exchange_gate,
})
