local Layout = {}

Layout.item_groups = {
  {
    name = "fw-science",
    icons = {
      {
        icon = "__space-age__/graphics/technology/research-productivity.png",
        icon_size = 256,
        scale = 0.5,
      },
    },
    order = "z[fluxworks]-a[science]",
  },
  {
    name = "fw-fabrication",
    icon = "__space-age__/graphics/technology/foundry.png",
    icon_size = 256,
    order = "z[fluxworks]-b[fabrication]",
  },
  {
    name = "fw-chemistry",
    icon = "__base__/graphics/technology/advanced-oil-processing.png",
    icon_size = 256,
    order = "z[fluxworks]-c[chemistry]",
  },
  {
    name = "fw-energy",
    icon = "__space-age__/graphics/technology/fusion-reactor.png",
    icon_size = 256,
    order = "z[fluxworks]-d[energy]",
  },
  {
    name = "fw-bioprocessing",
    icon = "__space-age__/graphics/technology/bioflux-processing.png",
    icon_size = 256,
    order = "z[fluxworks]-e[bioprocessing]",
  },
  {
    name = "fw-systems",
    icon = "__space-age__/graphics/technology/electromagnetic-plant.png",
    icon_size = 256,
    order = "z[fluxworks]-f[systems]",
  },
  {
    name = "fw-flux",
    icon = "__space-age__/graphics/technology/quantum-processor.png",
    icon_size = 256,
    order = "z[fluxworks]-g[flux]",
  },
}

Layout.subgroups = {
  { name = "fw-logistics-transport", group = "logistics", order = "a[fluxworks]-a[transport]" },
  { name = "fw-logistics-inserters", group = "logistics", order = "a[fluxworks]-b[inserters]" },
  { name = "fw-logistics-storage", group = "logistics", order = "a[fluxworks]-c[storage]" },
  { name = "fw-logistics-fluid-handling", group = "logistics", order = "a[fluxworks]-d[fluid-handling]" },
  { name = "fw-logistics-rail", group = "logistics", order = "a[fluxworks]-e[rail]" },
  { name = "fw-logistics-power", group = "logistics", order = "a[fluxworks]-f[power]" },
  { name = "fw-logistics-circuitry", group = "logistics", order = "a[fluxworks]-g[circuitry]" },
  { name = "fw-logistics-robotics", group = "logistics", order = "a[fluxworks]-h[robotics]" },
  { name = "fw-logistics-network", group = "logistics", order = "a[fluxworks]-i[network]" },
  { name = "fw-production-extraction", group = "production", order = "z[fluxworks]-9[extraction]" },
  { name = "fw-production-smelting", group = "production", order = "z[fluxworks]-a[smelting]" },
  { name = "fw-production-assembly", group = "production", order = "z[fluxworks]-b[assembly]" },
  { name = "fw-production-chemistry", group = "production", order = "z[fluxworks]-c[chemistry]" },
  { name = "fw-production-specialized", group = "production", order = "z[fluxworks]-d[specialized]" },
  { name = "fw-production-processing", group = "production", order = "z[fluxworks]-e[processing]" },
  { name = "fw-science-packs", group = "fw-science", order = "z[fluxworks]-f[science]-a[packs]" },
  { name = "fw-science-labs", group = "fw-science", order = "z[fluxworks]-f[science]-b[labs]" },
  { name = "fw-bioprocessing-machines", group = "fw-bioprocessing", order = "z[fluxworks]-f[bioprocessing]-a[machines]" },
  { name = "fw-bioprocessing-products", group = "fw-bioprocessing", order = "z[fluxworks]-g[bioprocessing]-b[products]" },
  { name = "fw-bioprocessing-processes", group = "fw-bioprocessing", order = "z[fluxworks]-h[bioprocessing]-c[processes]" },
  { name = "fw-energy-generation", group = "fw-energy", order = "z[fluxworks]-i[energy]-a[generation]" },
  { name = "fw-energy-storage", group = "fw-energy", order = "z[fluxworks]-j[energy]-b[storage]" },
  { name = "fw-energy-reactors", group = "fw-energy", order = "z[fluxworks]-k[energy]-c[reactors]" },
  { name = "fw-energy-fuels", group = "fw-energy", order = "z[fluxworks]-l[energy]-d[fuels]" },
  { name = "fw-chemistry-machines", group = "fw-chemistry", order = "z[fluxworks]-m[chemistry]-a[machines]" },
  { name = "fw-chemistry-feedstocks", group = "fw-chemistry", order = "z[fluxworks]-n[chemistry]-b[feedstocks]" },
  { name = "fw-chemistry-polymers", group = "fw-chemistry", order = "z[fluxworks]-o[chemistry]-c[polymers]" },
  { name = "fw-chemistry-reactives", group = "fw-chemistry", order = "z[fluxworks]-p[chemistry]-d[reactives]" },
  { name = "fw-chemistry-fluids", group = "fw-chemistry", order = "z[fluxworks]-q[chemistry]-e[fluids]" },
  { name = "fw-chemistry-petrochem", group = "fw-chemistry", order = "z[fluxworks]-r[chemistry]-f[petrochem]" },
  { name = "fw-chemistry-advanced", group = "fw-chemistry", order = "z[fluxworks]-s[chemistry]-g[advanced]" },
  { name = "fw-chemistry-barrels", group = "fw-chemistry", order = "z[fluxworks]-t[chemistry]-h[barrels]" },
  { name = "fw-chemistry-materials", group = "fw-chemistry", order = "z[fluxworks]-u[chemistry]-i[materials]" },
  { name = "fw-chemistry-processes", group = "fw-chemistry", order = "z[fluxworks]-v[chemistry]-j[processes]" },
  { name = "fw-systems-machines", group = "fw-systems", order = "z[fluxworks]-w[systems]-a[machines]" },
  { name = "fw-systems-control", group = "fw-systems", order = "z[fluxworks]-x[systems]-b[control]" },
  { name = "fw-systems-instrumentation", group = "fw-systems", order = "z[fluxworks]-y[systems]-c[instrumentation]" },
  { name = "fw-systems-infrastructure", group = "fw-systems", order = "z[fluxworks]-z[systems]-d[infrastructure]" },
  { name = "fw-fabrication-machines", group = "fw-fabrication", order = "z[fluxworks]-z[fabrication]-a[machines]" },
  { name = "fw-intermediate-structural", group = "fw-fabrication", order = "z[fluxworks]-za[fabrication]-b[structural]" },
  { name = "fw-intermediate-electrical", group = "fw-fabrication", order = "z[fluxworks]-zb[fabrication]-c[electrical]" },
  { name = "fw-intermediate-precision", group = "fw-fabrication", order = "z[fluxworks]-zc[fabrication]-d[precision]" },
  { name = "fw-intermediate-ballistic", group = "fw-fabrication", order = "z[fluxworks]-zd[fabrication]-e[ballistic]" },
  { name = "fw-intermediate-aerospace", group = "fw-fabrication", order = "z[fluxworks]-ze[fabrication]-f[aerospace]" },
  { name = "fw-fabrication-components", group = "fw-fabrication", order = "z[fluxworks]-zf[fabrication]-g[general]" },
  { name = "fw-flux-machines", group = "fw-flux", order = "z[fluxworks]-zg[flux]-a[machines]" },
  { name = "fw-flux-resources", group = "fw-flux", order = "z[fluxworks]-zh[flux]-b[resources]" },
  { name = "fw-flux-systems", group = "fw-flux", order = "z[fluxworks]-zi[flux]-c[systems]" },
  { name = "fw-flux-purple", group = "fw-flux", order = "z[fluxworks]-zj[flux]-d[purple]" },
  { name = "fw-flux-yellow", group = "fw-flux", order = "z[fluxworks]-zk[flux]-e[yellow]" },
  { name = "fw-flux-red", group = "fw-flux", order = "z[fluxworks]-zl[flux]-f[red]" },
  { name = "fw-flux-green", group = "fw-flux", order = "z[fluxworks]-zm[flux]-g[green]" },
  { name = "fw-transmutation-upcycle", group = "fw-flux", order = "z[fluxworks]-zn[flux]-h[transmutation]-a[upcycle]" },
  { name = "fw-transmutation-downcycle", group = "fw-flux", order = "z[fluxworks]-zo[flux]-i[transmutation]-b[downcycle]" },
  { name = "fw-flux-condensing-core", group = "fw-flux", order = "z[fluxworks]-zp[flux]-j[condensing]-a[core]" },
  { name = "fw-flux-condensing-promethium", group = "fw-flux", order = "z[fluxworks]-zq[flux]-k[condensing]-b[promethium]" },
  { name = "fw-flux-exchange", group = "fw-flux", order = "z[fluxworks]-zr[flux]-l[exchange]" },
  { name = "fw-flux-origin-projects", group = "fw-flux", order = "z[fluxworks]-zs[flux]-m[origin-projects]" },
}

return Layout
