data:extend({
  { type = "recipe-category", name = "basic-crushing" },
})

data:extend({
  {
    type = "recipe",
    name = "fw-crushed-iron-ore",
    category = "basic-crushing",
    enabled = false,
    energy_required = 0.8,
    allow_productivity = true,
    ingredients = { { type = "item", name = "iron-ore", amount = 2 } },
    results = { { type = "item", name = "fw-crushed-iron-ore", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-crushed-copper-ore",
    category = "basic-crushing",
    enabled = false,
    energy_required = 0.8,
    allow_productivity = true,
    ingredients = { { type = "item", name = "copper-ore", amount = 2 } },
    results = { { type = "item", name = "fw-crushed-copper-ore", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-crushed-tin-ore",
    category = "basic-crushing",
    enabled = false,
    energy_required = 1.0,
    allow_productivity = true,
    ingredients = { { type = "item", name = "tin-ore", amount = 2 } },
    results = { { type = "item", name = "fw-crushed-tin-ore", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-crushed-bauxite-ore",
    category = "basic-crushing",
    enabled = false,
    energy_required = 1.1,
    allow_productivity = true,
    ingredients = { { type = "item", name = "bauxite-ore", amount = 2 } },
    results = { { type = "item", name = "fw-crushed-bauxite-ore", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-crushed-lead-ore",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-lead-ore.png",
    icon_size = 256,
    category = "basic-crushing",
    enabled = false,
    energy_required = 1.0,
    allow_productivity = true,
    ingredients = { { type = "item", name = "lead-ore", amount = 2 } },
    results = { { type = "item", name = "fw-crushed-lead-ore", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-crushed-titanium-ore",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-titanium-ore.png",
    icon_size = 256,
    category = "basic-crushing",
    enabled = false,
    energy_required = 1.4,
    allow_productivity = true,
    ingredients = { { type = "item", name = "titanium-ore", amount = 2 } },
    results = { { type = "item", name = "fw-crushed-titanium-ore", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-silicon-beneficiation",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-silicon-ore-clean.png",
    icon_size = 256,
    category = "basic-crushing",
    enabled = false,
    energy_required = 1.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "silicon-ore", amount = 2 },
    },
    results = {
      { type = "item", name = "silicon", amount = 1 },
      { type = "item", name = "sand", amount = 2 },
    },
  },
  {
    type = "recipe",
    name = "fw-carbon-washing",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-carbon-ore.png",
    icon_size = 128,
    category = "chemistry",
    enabled = false,
    energy_required = 1.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "coal", amount = 2 },
      { type = "fluid", name = "water", amount = 20 },
    },
    results = {
      { type = "item", name = "fw-carbon", amount = 2 },
      { type = "fluid", name = "fw-chlorine", amount = 2, ignored_by_stats = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-alumina-refractory",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-alumina-refractory.png",
    icon_size = 256,
    category = "smelting",
    enabled = false,
    energy_required = 2.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "bauxite-ore", amount = 2 },
      { type = "item", name = "sand", amount = 1 },
      { type = "item", name = "fw-salt", amount = 1 },
    },
    results = { { type = "item", name = "fw-alumina-refractory", amount = 4 } },
  },
  {
    type = "recipe",
    name = "fw-iron-beam",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-iron-beam.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "iron-plate", amount = 2 },
      { type = "item", name = "lead-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-iron-beam", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-steel-beam",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-steel-beam.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 1 },
      { type = "item", name = "fw-iron-beam", amount = 1 },
    },
    results = { { type = "item", name = "fw-steel-beam", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-aluminum-beam",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-aluminum-beam.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "glass", amount = 1 },
    },
    results = { { type = "item", name = "fw-aluminum-beam", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-copper-tube",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-copper-tube.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "copper-plate", amount = 2 },
      { type = "item", name = "lead-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-copper-tube", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-inductor-coil",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-inductor-coil.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "copper-cable", amount = 3 },
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "item", name = "iron-plate", amount = 1 },
      { type = "item", name = "fw-ceramic-insulator", amount = 1 },
    },
    results = { { type = "item", name = "fw-inductor-coil", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-circuit-substrate",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-circuit-substrate.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "glass", amount = 1 },
      { type = "item", name = "stone-brick", amount = 2 },
      { type = "item", name = "silicon", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "fw-copper-tube", amount = 1 },
    },
    results = { { type = "item", name = "fw-circuit-substrate", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-metal-mesh",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-metal-mesh.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-iron-beam", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "lead-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-metal-mesh", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-rubber-sheet",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-rubber-sheet.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "coal", amount = 2 },
      { type = "item", name = "fw-salt", amount = 1 },
    },
    results = { { type = "item", name = "fw-rubber-sheet", amount = 4 } },
  },
  {
    type = "recipe",
    name = "fw-composite-panel",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-composite-panel.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 2.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-metal-mesh", amount = 2 },
      { type = "item", name = "fw-rubber-sheet", amount = 1 },
      { type = "item", name = "glass", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "fw-resin", amount = 1 },
    },
    results = { { type = "item", name = "fw-composite-panel", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-glass-lens",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-glass-lens.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "glass", amount = 2 },
      { type = "item", name = "silicon", amount = 1 },
      { type = "item", name = "fw-copper-tube", amount = 1 },
      { type = "item", name = "lead-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-glass-lens", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-ribbon-cable",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-ribbon-cable.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "copper-cable", amount = 2 },
      { type = "item", name = "fw-tinned-cable", amount = 2 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "fw-rubber-sheet", amount = 1 },
    },
    results = { { type = "item", name = "fw-ribbon-cable", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-sensor-package",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-sensor-package.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "electronic-circuit", amount = 1 },
      { type = "item", name = "fw-control-assembly", amount = 1 },
      { type = "item", name = "fw-circuit-substrate", amount = 1 },
      { type = "item", name = "fw-glass-lens", amount = 1 },
      { type = "item", name = "silicon", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 1 },
    },
    results = { { type = "item", name = "fw-sensor-package", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-cermet",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-cermet.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "stone-brick", amount = 2 },
      { type = "item", name = "steel-plate", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "fw-alumina-refractory", amount = 1 },
      { type = "item", name = "fw-ceramic-insulator", amount = 1 },
    },
    results = { { type = "item", name = "fw-cermet", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-inline-filter",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-inline-filter.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-metal-mesh", amount = 1 },
      { type = "item", name = "fw-carbon", amount = 1 },
      { type = "item", name = "fw-rubber-sheet", amount = 1 },
    },
    results = { { type = "item", name = "fw-inline-filter", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-transformer-core",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-transformer-core.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 2.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-steel-beam", amount = 1 },
      { type = "item", name = "engine-unit", amount = 1 },
      { type = "item", name = "fw-control-assembly", amount = 1 },
      { type = "item", name = "copper-cable", amount = 4 },
      { type = "item", name = "fw-tinned-cable", amount = 1 },
      { type = "item", name = "fw-inductor-coil", amount = 1 },
      { type = "item", name = "bronze-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-transformer-core", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-solder-alloy",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-solder-alloy.png",
    icon_size = 64,
    category = "smelting",
    enabled = false,
    energy_required = 2.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "lead-plate", amount = 2 },
      { type = "item", name = "tin-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-solder-alloy", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-bearing",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bearing.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 1.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 1 },
      { type = "item", name = "iron-plate", amount = 2 },
      { type = "item", name = "iron-gear-wheel", amount = 1 },
      { type = "item", name = "bronze-plate", amount = 1 },
      { type = "item", name = "fw-solder-alloy", amount = 1 },
    },
    results = { { type = "item", name = "fw-bearing", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-light-frame",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-light-frame.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 3.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "aluminum-plate", amount = 2 },
      { type = "item", name = "titanium-plate", amount = 1 },
      { type = "item", name = "steel-plate", amount = 1 },
      { type = "item", name = "fw-aluminum-beam", amount = 1 },
      { type = "item", name = "fw-ribbon-cable", amount = 1 },
    },
    results = { { type = "item", name = "fw-light-frame", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-ceramic-insulator",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-ceramic-insulator.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 2.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "stone-brick", amount = 1 },
      { type = "item", name = "glass", amount = 1 },
    },
    results = { { type = "item", name = "fw-ceramic-insulator", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-capacitor",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-capacitor.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 2.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-solder-alloy", amount = 1 },
      { type = "item", name = "fw-ceramic-insulator", amount = 1 },
      { type = "item", name = "silicon", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "copper-cable", amount = 3 },
    },
    results = { { type = "item", name = "fw-capacitor", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-gunpowder-early",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-gunpowder.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 0.8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "coal", amount = 1 },
      { type = "item", name = "fw-salt", amount = 1 },
    },
    results = { { type = "item", name = "fw-gunpowder", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-gunpowder",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-gunpowder.png",
    icon_size = 128,
    category = "chemistry",
    enabled = false,
    energy_required = 1.6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-carbon", amount = 2 },
      { type = "item", name = "fw-salt", amount = 1 },
      { type = "item", name = "sulfur", amount = 1 },
    },
    results = { { type = "item", name = "fw-gunpowder", amount = 4 } },
  },
  {
    type = "recipe",
    name = "fw-solder-wire",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-solder-wire.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 0.8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-solder-alloy", amount = 1 },
      { type = "item", name = "copper-cable", amount = 2 },
    },
    results = { { type = "item", name = "fw-solder-wire", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-tinned-cable",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-tinned-cable.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 1.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "item", name = "copper-cable", amount = 4 },
    },
    results = { { type = "item", name = "fw-tinned-cable", amount = 4 } },
  },
  {
    type = "recipe",
    name = "fw-chip-carrier",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-chip-carrier.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 1.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-circuit-substrate", amount = 1 },
      { type = "item", name = "fw-circuit-contact", amount = 1 },
      { type = "item", name = "stone-brick", amount = 1 },
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "item", name = "fw-silicon-wafer", amount = 1 },
    },
    results = { { type = "item", name = "fw-chip-carrier", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-control-assembly",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-logic-matrix.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 2.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "engine-unit", amount = 1 },
      { type = "item", name = "fw-circuit-substrate", amount = 1 },
      { type = "item", name = "fw-chip-carrier", amount = 1 },
      { type = "item", name = "fw-solder-wire", amount = 1 },
      { type = "item", name = "stone-brick", amount = 1 },
      { type = "item", name = "glass", amount = 1 },
    },
    results = { { type = "item", name = "fw-control-assembly", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-microchip",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-microchip.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 1.8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-chip-carrier", amount = 1 },
      { type = "item", name = "fw-control-assembly", amount = 1 },
      { type = "item", name = "fw-ribbon-cable", amount = 1 },
      { type = "item", name = "fw-solder-wire", amount = 1 },
      { type = "item", name = "silicon", amount = 1 },
      { type = "item", name = "advanced-circuit", amount = 1 },
    },
    results = { { type = "item", name = "fw-microchip", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-memory-die",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-memory-die.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 2.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-microchip", amount = 1 },
      { type = "item", name = "fw-chip-carrier", amount = 1 },
      { type = "item", name = "fw-silicon-wafer", amount = 1 },
      { type = "item", name = "fw-ceramic-insulator", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-memory-die", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-silicon-wafer",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-silicon-wafer.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 1.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "silicon", amount = 2 },
      { type = "item", name = "glass", amount = 1 },
    },
    results = { { type = "item", name = "fw-silicon-wafer", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-circuit-contact",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-circuit-contact.png",
    icon_size = 64,
    category = "crafting",
    enabled = false,
    energy_required = 0.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "copper-cable", amount = 2 },
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "item", name = "iron-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-circuit-contact", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-circuit-contact-leaded",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-circuit-contact.png",
    icon_size = 64,
    category = "crafting",
    enabled = false,
    energy_required = 0.6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "copper-cable", amount = 2 },
      { type = "item", name = "lead-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-circuit-contact", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-rocket-engine",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-rocket-engine.png",
    icon_size = 256,
    category = "crafting",
    enabled = false,
    energy_required = 3.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "electric-engine-unit", amount = 1 },
      { type = "item", name = "fw-control-assembly", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 2 },
      { type = "item", name = "titanium-plate", amount = 2 },
      { type = "item", name = "silicon", amount = 1 },
      { type = "item", name = "fw-light-frame", amount = 1 },
      { type = "item", name = "fw-bearing", amount = 2 },
      { type = "item", name = "fw-memory-die", amount = 1 },
    },
    results = { { type = "item", name = "fw-rocket-engine", amount = 1 } },
  },
})
