data:extend({
  { type = "recipe-category", name = "basic-crushing" },
})

data:extend({
  {
    type = "recipe",
    name = "fw-crushed-lead-ore",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-lead-ore.png",
    icon_size = 128,
    category = "basic-crushing",
    enabled = false,
    energy_required = 1.0,
    allow_productivity = true,
    ingredients = { { type = "item", name = "lead-ore", amount = 2 } },
    results = { { type = "item", name = "fw-crushed-lead-ore", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-crushed-titanium-ore",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-titanium-ore.png",
    icon_size = 128,
    category = "basic-crushing",
    enabled = false,
    energy_required = 1.4,
    allow_productivity = true,
    ingredients = { { type = "item", name = "titanium-ore", amount = 2 } },
    results = { { type = "item", name = "fw-crushed-titanium-ore", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-crushed-iron-ore",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-iron-ore.png",
    icon_size = 128,
    category = "basic-crushing",
    enabled = false,
    energy_required = 0.8,
    allow_productivity = true,
    ingredients = { { type = "item", name = "iron-ore", amount = 2 } },
    results = { { type = "item", name = "fw-crushed-iron-ore", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-crushed-copper-ore",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-copper-ore.png",
    icon_size = 128,
    category = "basic-crushing",
    enabled = false,
    energy_required = 0.8,
    allow_productivity = true,
    ingredients = { { type = "item", name = "copper-ore", amount = 2 } },
    results = { { type = "item", name = "fw-crushed-copper-ore", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-solder-alloy",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-solder-alloy.png",
    icon_size = 128,
    category = "smelting",
    enabled = false,
    energy_required = 2.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "lead-plate", amount = 1 },
      { type = "item", name = "copper-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-solder-alloy", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-bearing",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bearing.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 1.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 1 },
      { type = "item", name = "iron-plate", amount = 2 },
    },
    results = { { type = "item", name = "fw-bearing", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-light-frame",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-light-frame.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 3.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "aluminum-plate", amount = 2 },
      { type = "item", name = "steel-plate", amount = 1 },
      { type = "item", name = "copper-cable", amount = 4 },
    },
    results = { { type = "item", name = "fw-light-frame", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-ceramic-insulator",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-ceramic-insulator.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 2.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "stone-brick", amount = 2 },
      { type = "item", name = "plastic-bar", amount = 1 },
    },
    results = { { type = "item", name = "fw-ceramic-insulator", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-capacitor",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-capacitor.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 2.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-solder-alloy", amount = 1 },
      { type = "item", name = "fw-ceramic-insulator", amount = 1 },
      { type = "item", name = "copper-cable", amount = 4 },
    },
    results = { { type = "item", name = "fw-capacitor", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-gunpowder-early",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-gunpowder.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 1.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "coal", amount = 2 },
      { type = "item", name = "fw-salt", amount = 1 },
    },
    results = { { type = "item", name = "fw-gunpowder", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-gunpowder",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-gunpowder.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 1.6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "coal", amount = 2 },
      { type = "item", name = "fw-salt", amount = 1 },
      { type = "item", name = "sulfur", amount = 1 },
    },
    results = { { type = "item", name = "fw-gunpowder", amount = 2 } },
  },
})
