data:extend({
  { type = "recipe-category", name = "fw-atomic-enrichment" },
})

data:extend({
  {
    type = "recipe",
    name = "fw-atomic-enricher",
    icon = "__finely-crafted-graphics__/graphics/atom-forge/atom-forge-icon.png",
    icon_size = 64,
    enabled = false,
    energy_required = 10,
    ingredients = {
      { type = "item", name = "centrifuge", amount = 1 },
      { type = "item", name = "fw-pressure-housing", amount = 6 },
      { type = "item", name = "fw-annealed-cermet", amount = 4 },
      { type = "item", name = "fw-logic-matrix", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-transformer-core", amount = 4 },
      { type = "item", name = "fw-capacitor", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 2 },
    },
    results = { { type = "item", name = "fw-atomic-enricher", amount = 1 } },
    subgroup = "fw-fabrication-machines",
  },
  {
    type = "recipe",
    name = "fw-shielded-fuel-casing",
    icon = data.raw.item["fw-shielded-fuel-casing"].icon,
    icon_size = data.raw.item["fw-shielded-fuel-casing"].icon_size,
    icon_mipmaps = data.raw.item["fw-shielded-fuel-casing"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-shielded-fuel-casing"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "lead-plate", amount = 4 },
      { type = "item", name = "fw-ceramic-casing", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = { { type = "item", name = "fw-shielded-fuel-casing", amount = 2 } },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-isotope-matrix",
    icon = data.raw.item["fw-isotope-matrix"].icon,
    icon_size = data.raw.item["fw-isotope-matrix"].icon_size,
    icon_mipmaps = data.raw.item["fw-isotope-matrix"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-isotope-matrix"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 9,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "uranium-235", amount = 1 },
      { type = "item", name = "uranium-238", amount = 4 },
      { type = "item", name = "fw-ceramic-casing", amount = 1 },
      { type = "item", name = "fw-logic-matrix", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 2 },
      { type = "fluid", name = "sulfuric-acid", amount = 20 },
    },
    results = { { type = "item", name = "fw-isotope-matrix", amount = 2 } },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-fuel-pellet-bundle",
    icon = data.raw.item["fw-fuel-pellet-bundle"].icon,
    icon_size = data.raw.item["fw-fuel-pellet-bundle"].icon_size,
    icon_mipmaps = data.raw.item["fw-fuel-pellet-bundle"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-fuel-pellet-bundle"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "uranium-238", amount = 8 },
      { type = "item", name = "uranium-235", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-carbon", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 16 },
    },
    results = { { type = "item", name = "fw-fuel-pellet-bundle", amount = 2 } },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-moderator-lattice",
    icon = data.raw.item["fw-moderator-lattice"].icon,
    icon_size = data.raw.item["fw-moderator-lattice"].icon_size,
    icon_mipmaps = data.raw.item["fw-moderator-lattice"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-moderator-lattice"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "lead-plate", amount = 2 },
      { type = "item", name = "fw-glass", amount = 2 },
      { type = "item", name = "fw-metal-mesh", amount = 1 },
      { type = "item", name = "fw-flux-lattice", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 12 },
    },
    results = { { type = "item", name = "fw-moderator-lattice", amount = 2 } },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-control-rod-assembly",
    icon = data.raw.item["fw-control-rod-assembly"].icon,
    icon_size = data.raw.item["fw-control-rod-assembly"].icon_size,
    icon_mipmaps = data.raw.item["fw-control-rod-assembly"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-control-rod-assembly"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 10,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "titanium-plate", amount = 1 },
      { type = "item", name = "fw-field-winding", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-moderator-lattice", amount = 1 },
      { type = "item", name = "fw-thermal-buffer", amount = 1 },
    },
    results = { { type = "item", name = "fw-control-rod-assembly", amount = 2 } },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-reactor-coolant-cartridge",
    icon = data.raw.item["fw-reactor-coolant-cartridge"].icon,
    icon_size = data.raw.item["fw-reactor-coolant-cartridge"].icon_size,
    icon_mipmaps = data.raw.item["fw-reactor-coolant-cartridge"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-reactor-coolant-cartridge"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 10,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-thermal-buffer", amount = 1 },
      { type = "item", name = "fw-cryo-coil", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-reinforced-seal", amount = 1 },
      { type = "fluid", name = "fluoroketone-cold", amount = 20, temperature = -150 },
    },
    results = { { type = "item", name = "fw-reactor-coolant-cartridge", amount = 2 } },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-reactor-dopant",
    icon = data.raw.item["fw-reactor-dopant"].icon,
    icon_size = data.raw.item["fw-reactor-dopant"].icon_size,
    icon_mipmaps = data.raw.item["fw-reactor-dopant"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-reactor-dopant"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 10,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-isotope-matrix", amount = 1 },
      { type = "item", name = "fw-control-rod-assembly", amount = 1 },
      { type = "item", name = "fw-reactor-coolant-cartridge", amount = 1 },
      { type = "item", name = "fw-logic-matrix", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 1 },
      { type = "item", name = "fw-fuel-pellet-bundle", amount = 1 },
    },
    results = { { type = "item", name = "fw-reactor-dopant", amount = 2 } },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-radioactive-scrap-sorting",
    icon = data.raw.item["fw-radioactive-scrap"].icon,
    icon_size = data.raw.item["fw-radioactive-scrap"].icon_size,
    icon_mipmaps = data.raw.item["fw-radioactive-scrap"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-radioactive-scrap"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 12,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-radioactive-scrap", amount = 3 },
      { type = "item", name = "fw-moderator-lattice", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 30 },
    },
    results = {
      { type = "item", name = "fw-recovered-actinides", amount = 2 },
      { type = "item", name = "uranium-238", amount = 4 },
      { type = "item", name = "fw-inline-filter", amount = 1, probability = 0.7 },
    },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-isotope-recovery",
    icon = data.raw.item["fw-recovered-actinides"].icon,
    icon_size = data.raw.item["fw-recovered-actinides"].icon_size,
    icon_mipmaps = data.raw.item["fw-recovered-actinides"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-recovered-actinides"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 12,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-recovered-actinides", amount = 2 },
      { type = "item", name = "fw-isotope-matrix", amount = 1 },
      { type = "item", name = "fw-reactor-coolant-cartridge", amount = 1 },
      { type = "fluid", name = "fw-red-flux", amount = 16 },
    },
    results = {
      { type = "item", name = "uranium-235", amount = 1 },
      { type = "item", name = "uranium-238", amount = 6 },
      { type = "item", name = "fw-reactor-coolant-cartridge", amount = 1, probability = 0.5 },
    },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-actinide-matrix-seeding",
    icon = data.raw.item["fw-isotope-matrix"].icon,
    icon_size = data.raw.item["fw-isotope-matrix"].icon_size,
    icon_mipmaps = data.raw.item["fw-isotope-matrix"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-isotope-matrix"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 11,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-recovered-actinides", amount = 1 },
      { type = "item", name = "uranium-238", amount = 4 },
      { type = "item", name = "fw-logic-matrix", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 1 },
      { type = "item", name = "fw-ceramic-casing", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 20 },
    },
    results = { { type = "item", name = "fw-isotope-matrix", amount = 2 } },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-scrap-lattice-recasting",
    icon = data.raw.item["fw-moderator-lattice"].icon,
    icon_size = data.raw.item["fw-moderator-lattice"].icon_size,
    icon_mipmaps = data.raw.item["fw-moderator-lattice"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-moderator-lattice"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 10,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-radioactive-scrap", amount = 2 },
      { type = "item", name = "lead-plate", amount = 2 },
      { type = "item", name = "fw-flux-lattice", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 12 },
    },
    results = { { type = "item", name = "fw-moderator-lattice", amount = 2 } },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-pellet-bundle-reprocessing",
    icon = data.raw.item["fw-fuel-pellet-bundle"].icon,
    icon_size = data.raw.item["fw-fuel-pellet-bundle"].icon_size,
    icon_mipmaps = data.raw.item["fw-fuel-pellet-bundle"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-fuel-pellet-bundle"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 12,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "depleted-uranium-fuel-cell", amount = 2 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-recovered-actinides", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 20 },
    },
    results = {
      { type = "item", name = "fw-fuel-pellet-bundle", amount = 2 },
      { type = "item", name = "fw-radioactive-scrap", amount = 1 },
    },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-actinide-dopant-refining",
    icon = data.raw.item["fw-reactor-dopant"].icon,
    icon_size = data.raw.item["fw-reactor-dopant"].icon_size,
    icon_mipmaps = data.raw.item["fw-reactor-dopant"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-reactor-dopant"].icons),
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 13,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-recovered-actinides", amount = 1 },
      { type = "item", name = "fw-isotope-matrix", amount = 1 },
      { type = "item", name = "fw-reactor-coolant-cartridge", amount = 1 },
      { type = "item", name = "fw-logic-matrix", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 1 },
      { type = "fluid", name = "fw-red-flux", amount = 20 },
    },
    results = { { type = "item", name = "fw-reactor-dopant", amount = 3 } },
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-reactor-grade-fuel-cell",
    icon = "__base__/graphics/icons/uranium-fuel-cell.png",
    icon_size = 64,
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 10,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-fuel-pellet-bundle", amount = 1 },
      { type = "item", name = "fw-isotope-matrix", amount = 1 },
      { type = "item", name = "fw-moderator-lattice", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 20 },
    },
    results = { { type = "item", name = "uranium-fuel-cell", amount = 2 } },
    main_product = "uranium-fuel-cell",
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-spent-fuel-reconditioning",
    icon = "__base__/graphics/icons/depleted-uranium-fuel-cell.png",
    icon_size = 64,
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 14,
    ingredients = {
      { type = "item", name = "depleted-uranium-fuel-cell", amount = 4 },
      { type = "item", name = "fw-reactor-coolant-cartridge", amount = 1 },
      { type = "item", name = "fw-reactor-dopant", amount = 1 },
      { type = "item", name = "fw-moderator-lattice", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 40 },
    },
    results = {
      { type = "item", name = "uranium-fuel-cell", amount = 2 },
      { type = "item", name = "fw-radioactive-scrap", amount = 2 },
    },
    main_product = "uranium-fuel-cell",
    subgroup = "fw-fabrication-components",
  },
  {
    type = "recipe",
    name = "fw-nuclear-fuel-overdrive",
    icon = "__base__/graphics/icons/nuclear-fuel.png",
    icon_size = 64,
    enabled = false,
    category = "fw-atomic-enrichment",
    energy_required = 14,
    ingredients = {
      { type = "item", name = "nuclear-fuel", amount = 1 },
      { type = "item", name = "fw-reactor-dopant", amount = 1 },
      { type = "item", name = "fw-isotope-matrix", amount = 1 },
      { type = "item", name = "fw-logic-matrix", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 1 },
      { type = "item", name = "fw-reactor-coolant-cartridge", amount = 1 },
      { type = "fluid", name = "fw-red-flux", amount = 30 },
    },
    results = { { type = "item", name = "nuclear-fuel", amount = 2 } },
    main_product = "nuclear-fuel",
    subgroup = "fw-fabrication-components",
  },
})
