data:extend({
  {
    type = "recipe",
    name = "lead-plate",
    icon = "__FluxWorksAssets__/graphics/resources/ores/lead-ore.png",
    icon_size = 64,
    category = "smelting",
    enabled = false,
    energy_required = 3.2,
    allow_productivity = true,
    ingredients = { { type = "item", name = "lead-ore", amount = 1 } },
    results = { { type = "item", name = "lead-plate", amount = 1 } },
  },
  {
    type = "recipe",
    name = "lead-plate-from-crushed",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-lead-ore.png",
    icon_size = 128,
    category = "smelting",
    enabled = false,
    energy_required = 3.2,
    allow_productivity = true,
    ingredients = { { type = "item", name = "fw-crushed-lead-ore", amount = 3 } },
    results = { { type = "item", name = "lead-plate", amount = 2 } },
  },
  {
    type = "recipe",
    name = "titanium-plate",
    icon = "__FluxWorksAssets__/graphics/resources/ores/titanium-ore.png",
    icon_size = 64,
    category = "smelting",
    enabled = false,
    energy_required = 6.4,
    allow_productivity = true,
    ingredients = { { type = "item", name = "titanium-ore", amount = 2 } },
    results = { { type = "item", name = "titanium-plate", amount = 1 } },
  },
  {
    type = "recipe",
    name = "titanium-plate-from-crushed",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-titanium-ore.png",
    icon_size = 128,
    category = "smelting",
    enabled = false,
    energy_required = 6.4,
    allow_productivity = true,
    ingredients = { { type = "item", name = "fw-crushed-titanium-ore", amount = 3 } },
    results = { { type = "item", name = "titanium-plate", amount = 2 } },
  },
  {
    type = "recipe",
    name = "aluminum-plate",
    icon = "__FluxWorksAssets__/graphics/icons/items/aluminum-plate.png",
    icon_size = 128,
    category = "smelting",
    enabled = false,
    energy_required = 4.0,
    allow_productivity = true,
    ingredients = { { type = "item", name = "bauxite-ore", amount = 2 } },
    results = { { type = "item", name = "aluminum-plate", amount = 1 } },
  },
})
