data:extend({
  { type = "recipe-category", name = "fw-petrochemistry" },
  { type = "recipe-category", name = "fw-hydraulics" },
})

data:extend({
  {
    type = "recipe",
    name = "fw-petrochemical-facility",
    icon = "__finely-crafted-graphics__/graphics/thermal-plant/thermal-plant-icon.png",
    icon_size = 64,
    enabled = false,
    energy_required = 10,
    ingredients = {
      { type = "item", name = "fw-pressure-housing", amount = 6 },
      { type = "item", name = "fw-steel-beam", amount = 8 },
      { type = "item", name = "fw-flow-regulator", amount = 4 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "item", name = "fw-resin", amount = 6 },
      { type = "item", name = "pipe", amount = 8 },
      { type = "item", name = "engine-unit", amount = 4 },
    },
    results = { { type = "item", name = "fw-petrochemical-facility", amount = 1 } },
    subgroup = "fw-chemistry-machines",
  },
  {
    type = "recipe",
    name = "fw-hydraulic-plant",
    icon = "__finely-crafted-graphics__/graphics/oxidizer/oxidizer-icon.png",
    icon_size = 64,
    enabled = false,
    energy_required = 10,
    ingredients = {
      { type = "item", name = "fw-pressure-housing", amount = 4 },
      { type = "item", name = "fw-copper-tube", amount = 8 },
      { type = "item", name = "fw-flow-regulator", amount = 4 },
      { type = "item", name = "fw-power-regulator", amount = 1 },
      { type = "item", name = "fw-reinforced-seal", amount = 4 },
      { type = "item", name = "fw-steel-beam", amount = 6 },
      { type = "item", name = "electric-engine-unit", amount = 3 },
    },
    results = { { type = "item", name = "fw-hydraulic-plant", amount = 1 } },
    subgroup = "fw-fabrication-machines",
  },
  {
    type = "recipe",
    name = "fw-chlorinated-binder-stock",
    icon = data.raw.item["fw-chlorinated-binder-stock"].icon,
    icon_size = data.raw.item["fw-chlorinated-binder-stock"].icon_size,
    icon_mipmaps = data.raw.item["fw-chlorinated-binder-stock"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-chlorinated-binder-stock"].icons),
    enabled = false,
    category = "fw-petrochemistry",
    energy_required = 5.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-resin", amount = 2 },
      { type = "item", name = "plastic-bar", amount = 2 },
      { type = "item", name = "sulfur", amount = 1 },
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "fluid", name = "fw-chlorine", amount = 35 },
      { type = "fluid", name = "sulfuric-acid", amount = 20 },
    },
    results = { { type = "item", name = "fw-chlorinated-binder-stock", amount = 3 } },
    subgroup = "fw-chemistry-processes",
  },
  {
    type = "recipe",
    name = "fw-elastomer-matrix",
    icon = data.raw.item["fw-elastomer-matrix"].icon,
    icon_size = data.raw.item["fw-elastomer-matrix"].icon_size,
    icon_mipmaps = data.raw.item["fw-elastomer-matrix"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-elastomer-matrix"].icons),
    enabled = false,
    category = "fw-petrochemistry",
    energy_required = 6.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-chlorinated-binder-stock", amount = 2 },
      { type = "item", name = "fw-rubber-sheet", amount = 2 },
      { type = "item", name = "bronze-plate", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "fluid", name = "fw-latex", amount = 30 },
      { type = "fluid", name = "lubricant", amount = 20 },
    },
    results = { { type = "item", name = "fw-elastomer-matrix", amount = 3 } },
    subgroup = "fw-chemistry-processes",
  },
  {
    type = "recipe",
    name = "fw-reinforced-seal",
    icon = data.raw.item["fw-reinforced-seal"].icon,
    icon_size = data.raw.item["fw-reinforced-seal"].icon_size,
    icon_mipmaps = data.raw.item["fw-reinforced-seal"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-reinforced-seal"].icons),
    enabled = false,
    category = "fw-petrochemistry",
    energy_required = 6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-chlorinated-binder-stock", amount = 1 },
      { type = "item", name = "fw-elastomer-matrix", amount = 2 },
      { type = "item", name = "fw-pressure-housing", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "item", name = "fw-flow-regulator", amount = 1 },
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "fluid", name = "fw-latex", amount = 10 },
      { type = "fluid", name = "water", amount = 20 },
    },
    results = { { type = "item", name = "fw-reinforced-seal", amount = 3 } },
    subgroup = "fw-chemistry-processes",
  },
  {
    type = "recipe",
    name = "fw-hydraulic-manifold",
    icon = data.raw.item["fw-hydraulic-manifold"].icon,
    icon_size = data.raw.item["fw-hydraulic-manifold"].icon_size,
    icon_mipmaps = data.raw.item["fw-hydraulic-manifold"].icon_mipmaps,
    icons = table.deepcopy(data.raw.item["fw-hydraulic-manifold"].icons),
    enabled = false,
    category = "fw-hydraulics",
    energy_required = 5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flow-regulator", amount = 1 },
      { type = "item", name = "bronze-plate", amount = 1 },
      { type = "item", name = "fw-pressure-housing", amount = 1 },
      { type = "item", name = "fw-copper-tube", amount = 4 },
      { type = "item", name = "fw-reinforced-seal", amount = 2 },
      { type = "item", name = "fw-elastomer-matrix", amount = 1 },
      { type = "item", name = "electric-engine-unit", amount = 1 },
      { type = "item", name = "fw-power-regulator", amount = 1 },
      { type = "item", name = "fw-signal-conduit", amount = 1 },
      { type = "item", name = "lead-plate", amount = 1 },
      { type = "item", name = "titanium-plate", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 1 },
    },
    results = { { type = "item", name = "fw-hydraulic-manifold", amount = 3 } },
    subgroup = "fw-fabrication-components",
  },
})

local function hydraulic_recipe(name, product_name, energy_required, ingredients, amount, subgroup)
  local product = data.raw.item[product_name]
  local recipe = {
    type = "recipe",
    name = name,
    enabled = false,
    category = "fw-hydraulics",
    energy_required = energy_required,
    allow_productivity = true,
    ingredients = ingredients,
    results = { { type = "item", name = product_name, amount = amount } },
    main_product = product_name,
    subgroup = subgroup,
  }

  if product.icons then
    recipe.icons = table.deepcopy(product.icons)
  else
    recipe.icon = product.icon
    recipe.icon_size = product.icon_size
    recipe.icon_mipmaps = product.icon_mipmaps
  end

  return recipe
end

data:extend({
  hydraulic_recipe("fw-hydraulic-tube-drawing", "fw-copper-tube", 3.5, {
    { type = "item", name = "copper-plate", amount = 4 },
    { type = "item", name = "lead-plate", amount = 1 },
    { type = "fluid", name = "lubricant", amount = 20 },
  }, 8, "fw-intermediate-structural"),
  hydraulic_recipe("fw-hydraulic-filter-pressing", "fw-inline-filter", 4, {
    { type = "item", name = "fw-metal-mesh", amount = 2 },
    { type = "item", name = "fw-carbon", amount = 2 },
    { type = "item", name = "fw-rubber-sheet", amount = 1 },
    { type = "fluid", name = "water", amount = 30 },
  }, 8, "fw-intermediate-precision"),
  hydraulic_recipe("fw-hydraulic-housing-forming", "fw-pressure-housing", 6, {
    { type = "item", name = "fw-cermet", amount = 2 },
    { type = "item", name = "fw-steel-beam", amount = 2 },
    { type = "item", name = "fw-inline-filter", amount = 1 },
    { type = "item", name = "lead-plate", amount = 1 },
    { type = "item", name = "titanium-plate", amount = 1 },
    { type = "fluid", name = "lubricant", amount = 30 },
  }, 5, "fw-intermediate-structural"),
  hydraulic_recipe("fw-hydraulic-seal-compression", "fw-reinforced-seal", 6.5, {
    { type = "item", name = "fw-chlorinated-binder-stock", amount = 2 },
    { type = "item", name = "fw-elastomer-matrix", amount = 3 },
    { type = "item", name = "lead-plate", amount = 1 },
    { type = "item", name = "fw-ceramic-insulator", amount = 2 },
    { type = "item", name = "fw-carbon", amount = 1 },
    { type = "item", name = "fw-salt", amount = 1 },
    { type = "fluid", name = "water", amount = 30 },
  }, 6, "fw-intermediate-structural"),
  hydraulic_recipe("fw-hydraulic-regulator-calibration", "fw-flow-regulator", 7, {
    { type = "item", name = "fw-pressure-housing", amount = 2 },
    { type = "item", name = "electric-motor", amount = 1 },
    { type = "item", name = "fw-bearing", amount = 2 },
    { type = "item", name = "bronze-plate", amount = 2 },
    { type = "item", name = "fw-inline-filter", amount = 1 },
    { type = "item", name = "fw-capacitor", amount = 2 },
    { type = "item", name = "fw-copper-tube", amount = 2 },
    { type = "item", name = "fw-signal-conduit", amount = 2 },
    { type = "fluid", name = "lubricant", amount = 20 },
  }, 5, "fw-intermediate-precision"),
})
