local quantum_component = "processing-unit"
if data.raw.item["quantum-processor"] then
  quantum_component = "quantum-processor"
end

local K = 1000
local M = 1000000

data:extend({
  {
    type = "recipe",
    name = "fw-harvester-head",
    icons = data.raw.item["fw-harvester-head"].icons,
    category = "fw-flux-harvesting",
    subgroup = "fw-flux-systems",
    order = "a[conditioning]-b[harvester-head]",
    enabled = false,
    energy_required = 4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-pressure-housing", amount = 1 },
      { type = "item", name = "fw-flow-regulator", amount = 1 },
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 30 },
    },
    results = {
      { type = "item", name = "fw-harvester-head", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.45 },
    },
    main_product = "fw-harvester-head",
  },
  {
    type = "recipe",
    name = "fw-flux-catalyst",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-2.png",
    icon_size = 64,
    category = "crafting",
    subgroup = "fw-flux-systems",
    order = "a[conditioning]-a[flux-catalyst]",
    enabled = false,
    energy_required = 2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-crystalised-flux", amount = 2 },
      { type = "item", name = "fw-sand", amount = 3 },
      { type = "item", name = "sulfur", amount = 1 },
    },
    results = {
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-stabilized-flux-crystal",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-3.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-a[stabilized-flux-crystal]",
    enabled = false,
    energy_required = 4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-crystalised-flux", amount = 3 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 42 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
      { type = "fluid", name = "fw-red-flux", amount = 10 },
      { type = "fluid", name = "fw-green-flux", amount = 8 },
      { type = "fluid", name = "fw-chlorine", amount = 15 },
    },
    results = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.45 },
    },
    main_product = "fw-stabilized-flux-crystal",
  },
  {
    type = "recipe",
    name = "fw-flux-lattice",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-metal-mesh.png",
    icon_size = 1024,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-b[flux-lattice]",
    enabled = false,
    energy_required = 4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 2 },
      { type = "item", name = "fw-circuit-contact", amount = 2 },
      { type = "item", name = "fw-glass", amount = 1 },
      { type = "item", name = "fw-solder-wire", amount = 2 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
    },
    results = {
      { type = "item", name = "fw-flux-lattice", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-annealed-cermet",
    icons = data.raw.item["fw-annealed-cermet"].icons,
    category = "fw-arc-smelting",
    subgroup = "fw-flux-systems",
    order = "b[systems]-c[annealed-cermet]",
    enabled = false,
    energy_required = 5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-cermet", amount = 2 },
      { type = "item", name = "fw-foundry-lining", amount = 1 },
      { type = "item", name = "titanium-plate", amount = 1 },
      { type = "fluid", name = "fw-red-flux", amount = 30 },
    },
    results = {
      { type = "item", name = "fw-annealed-cermet", amount = 2 },
    },
  },
  {
    type = "recipe",
    name = "fw-resonance-substrate",
    icons = data.raw.item["fw-resonance-substrate"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-d[resonance-substrate]",
    enabled = false,
    energy_required = 6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-circuit-substrate", amount = 2 },
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 1 },
      { type = "item", name = "fw-sensor-package", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 24 },
      { type = "fluid", name = "fw-red-flux", amount = 12 },
      { type = "fluid", name = "fw-green-flux", amount = 8 },
    },
    results = {
      { type = "item", name = "fw-resonance-substrate", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-condensed-flux-matrix",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-1-light.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-e[condensed-flux-matrix]",
    enabled = false,
    energy_required = 7.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 4 },
      { type = "item", name = "fw-flux-lattice", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 20 },
      { type = "fluid", name = "fw-yellow-flux", amount = 36 },
      { type = "fluid", name = "fw-red-flux", amount = 72 },
      { type = "fluid", name = "fw-green-flux", amount = 20 },
    },
    results = {
      { type = "item", name = "fw-condensed-flux-matrix", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.7 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-asteroid-deep-refining",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-3.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "c[refinement]-a[asteroid-deep-refining]",
    enabled = false,
    energy_required = 8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-asteroid-chunk", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "item", name = "fw-flux-lattice", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 16 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
      { type = "fluid", name = "fw-red-flux", amount = 30 },
    },
    results = {
      { type = "item", name = "fw-condensed-flux-matrix", amount = 1 },
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.65 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-resonance-cell",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-2-light.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-f[flux-resonance-cell]",
    enabled = false,
    energy_required = 10,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 2 },
      { type = "item", name = "fw-resonance-substrate", amount = 1 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 30 },
      { type = "fluid", name = "fw-red-flux", amount = 60 },
      { type = "fluid", name = "fw-green-flux", amount = 12 },
    },
    results = {
      { type = "item", name = "fw-flux-resonance-cell", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.8 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-phase-manifold",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-circuit-substrate.png",
    icon_size = 1024,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-g[flux-phase-manifold]",
    enabled = false,
    energy_required = 14,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-resonance-cell", amount = 2 },
      { type = "item", name = "fw-resonance-substrate", amount = 2 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "item", name = "fw-sensor-package", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 14 },
      { type = "fluid", name = "fw-yellow-flux", amount = 80 },
      { type = "fluid", name = "fw-red-flux", amount = 160 },
      { type = "fluid", name = "fw-green-flux", amount = 20 },
    },
    results = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.8 },
    },
  },
  {
    type = "recipe",
    name = "fw-rift-seed-crystallization",
    icon = "__FluxWorksAssets__/graphics/icons/items/crystallized-flux.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "c[refinement]-b[rift-seed-crystallization]",
    enabled = false,
    energy_required = 18,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 180 },
      { type = "fluid", name = "fw-yellow-flux", amount = 60 },
      { type = "fluid", name = "fw-red-flux", amount = 160 },
      { type = "fluid", name = "fw-green-flux", amount = 120 },
    },
    results = {
      { type = "item", name = "fw-crystalised-flux", amount = 48 },
      { type = "item", name = "fw-flux-phase-manifold", amount = 1, probability = 0.65 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 1, probability = 0.75 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-metallic-synthesis",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-1-light.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "c[refinement]-c[metallic-synthesis]",
    enabled = false,
    energy_required = 20,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 2 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 160 },
      { type = "fluid", name = "fw-yellow-flux", amount = 80 },
      { type = "fluid", name = "fw-red-flux", amount = 220 },
    },
    results = {
      { type = "item", name = "uranium-ore", amount = 10 },
      { type = "item", name = "titanium-ore", amount = 10 },
      { type = "item", name = "silicon-ore", amount = 16 },
      { type = "item", name = "fw-flux-phase-manifold", amount = 1, probability = 0.7 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 1, probability = 0.7 },
    },
  },
  {
    type = "recipe",
    name = "fw-phase-anchor",
    icons = data.raw.item["fw-phase-anchor"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "d[utility]-a[phase-anchor]",
    enabled = false,
    energy_required = 60,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 2 },
      { type = "item", name = "fw-rift-stabilizer", amount = 1 },
      { type = "item", name = "fw-field-winding", amount = 2 },
      { type = "item", name = "fw-pressure-housing", amount = 2 },
      { type = "item", name = "supercapacitor", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 250 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 180 * K },
      { type = "fluid", name = "fw-red-flux", amount = 220 * K },
      { type = "fluid", name = "fw-green-flux", amount = 140 * K },
    },
    results = {
      { type = "item", name = "fw-phase-anchor", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-entanglement-core",
    icons = data.raw.item["fw-entanglement-core"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "d[utility]-b[entanglement-core]",
    enabled = false,
    energy_required = 70,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-em-core", amount = 1 },
      { type = "item", name = "fw-logic-matrix", amount = 2 },
      { type = "item", name = "fw-memory-die", amount = 2 },
      { type = "item", name = "fw-signal-conduit", amount = 3 },
      { type = "item", name = quantum_component, amount = 4 },
      { type = "fluid", name = "fw-purple-flux", amount = 160 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 300 * K },
      { type = "fluid", name = "fw-red-flux", amount = 180 * K },
      { type = "fluid", name = "fw-green-flux", amount = 240 * K },
    },
    results = {
      { type = "item", name = "fw-entanglement-core", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-reservoir-lining",
    icons = data.raw.item["fw-reservoir-lining"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "d[utility]-c[reservoir-lining]",
    enabled = false,
    energy_required = 55,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-thermal-buffer", amount = 2 },
      { type = "item", name = "fw-flow-regulator", amount = 2 },
      { type = "item", name = "fw-ceramic-casing", amount = 3 },
      { type = "item", name = "fw-cryo-coil", amount = 2 },
      { type = "item", name = "fw-rubber-sheet", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 200 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 120 * K },
      { type = "fluid", name = "fw-red-flux", amount = 260 * K },
      { type = "fluid", name = "fw-green-flux", amount = 100 * K },
    },
    results = {
      { type = "item", name = "fw-reservoir-lining", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-compression-baffle",
    icons = data.raw.item["fw-compression-baffle"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "d[utility]-d[compression-baffle]",
    enabled = false,
    energy_required = 55,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flow-regulator", amount = 2 },
      { type = "item", name = "fw-inline-filter", amount = 2 },
      { type = "item", name = "fw-flux-lattice", amount = 2 },
      { type = "item", name = "fw-pressure-housing", amount = 2 },
      { type = "item", name = "fw-sensor-diode", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 240 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 180 * K },
      { type = "fluid", name = "fw-red-flux", amount = 320 * K },
      { type = "fluid", name = "fw-green-flux", amount = 80 * K },
    },
    results = {
      { type = "item", name = "fw-compression-baffle", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-thermal-phase-gasket",
    icons = data.raw.item["fw-thermal-phase-gasket"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "d[utility]-e[thermal-phase-gasket]",
    enabled = false,
    energy_required = 48,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-rubber-sheet", amount = 3 },
      { type = "item", name = "fw-thermal-buffer", amount = 2 },
      { type = "item", name = "fw-ceramic-insulator", amount = 3 },
      { type = "item", name = "fw-flow-regulator", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 150 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 100 * K },
      { type = "fluid", name = "fw-red-flux", amount = 280 * K },
      { type = "fluid", name = "fw-green-flux", amount = 70 * K },
    },
    results = {
      { type = "item", name = "fw-thermal-phase-gasket", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-rift-coupler",
    icons = data.raw.item["fw-rift-coupler"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-exchange",
    order = "d[utility]-f[rift-coupler]",
    enabled = false,
    energy_required = 120,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-phase-anchor", amount = 2 },
      { type = "item", name = "fw-entanglement-core", amount = 2 },
      { type = "item", name = "fw-promethium-matrix", amount = 1 },
      { type = "item", name = "fw-field-winding", amount = 2 },
      { type = "item", name = "superconductor", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 1 * M },
      { type = "fluid", name = "fw-yellow-flux", amount = 600 * K },
      { type = "fluid", name = "fw-red-flux", amount = 1200 * K },
      { type = "fluid", name = "fw-green-flux", amount = 500 * K },
    },
    results = {
      { type = "item", name = "fw-rift-coupler", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-phase-vault",
    icons = data.raw.item["fw-phase-vault"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-exchange",
    order = "d[utility]-g[phase-vault]",
    enabled = false,
    energy_required = 180,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "storage-chest", amount = 4 },
      { type = "item", name = "fw-phase-anchor", amount = 2 },
      { type = "item", name = "fw-entanglement-core", amount = 2 },
      { type = "item", name = "fw-compression-baffle", amount = 4 },
      { type = "item", name = "fw-pressure-housing", amount = 4 },
      { type = "item", name = "fw-power-regulator", amount = 4 },
      { type = "item", name = "superconductor", amount = 4 },
      { type = "fluid", name = "fw-purple-flux", amount = 2 * M },
      { type = "fluid", name = "fw-yellow-flux", amount = 1500 * K },
      { type = "fluid", name = "fw-red-flux", amount = 2200 * K },
      { type = "fluid", name = "fw-green-flux", amount = 900 * K },
    },
    results = {
      { type = "item", name = "fw-phase-vault", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-spectral-reservoir",
    icons = data.raw.item["fw-spectral-reservoir"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-exchange",
    order = "d[utility]-h[spectral-reservoir]",
    enabled = false,
    energy_required = 180,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "storage-tank", amount = 3 },
      { type = "item", name = "fw-reservoir-lining", amount = 4 },
      { type = "item", name = "fw-entanglement-core", amount = 2 },
      { type = "item", name = "fw-thermal-phase-gasket", amount = 4 },
      { type = "item", name = "fw-thermal-buffer", amount = 4 },
      { type = "item", name = "fw-cryo-coil", amount = 4 },
      { type = "item", name = "supercapacitor", amount = 4 },
      { type = "fluid", name = "fw-purple-flux", amount = 1800 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 1200 * K },
      { type = "fluid", name = "fw-red-flux", amount = 2600 * K },
      { type = "fluid", name = "fw-green-flux", amount = 1100 * K },
    },
    results = {
      { type = "item", name = "fw-spectral-reservoir", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-rift-exchange-gate",
    icons = data.raw.item["fw-rift-exchange-gate"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-exchange",
    order = "d[utility]-i[rift-exchange-gate]",
    enabled = false,
    energy_required = 300,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-rift-coupler", amount = 4 },
      { type = "item", name = "fw-phase-anchor", amount = 2 },
      { type = "item", name = "fw-entanglement-core", amount = 2 },
      { type = "item", name = "fw-thermal-phase-gasket", amount = 4 },
      { type = "item", name = "fw-promethium-matrix", amount = 2 },
      { type = "item", name = "fusion-reactor-equipment", amount = 2 },
      { type = "item", name = "superconductor", amount = 6 },
      { type = "item", name = quantum_component, amount = 6 },
      { type = "fluid", name = "fw-purple-flux", amount = 4 * M },
      { type = "fluid", name = "fw-yellow-flux", amount = 3 * M },
      { type = "fluid", name = "fw-red-flux", amount = 5 * M },
      { type = "fluid", name = "fw-green-flux", amount = 2500 * K },
    },
    results = {
      { type = "item", name = "fw-rift-exchange-gate", amount = 1 },
    },
  },
})
