local quantum_component = "processing-unit"
if data.raw.item["quantum-processor"] then
  quantum_component = "quantum-processor"
end

data:extend({
  {
    type = "recipe",
    name = "fw-harvester-head",
    icons = data.raw.item["fw-harvester-head"].icons,
    category = "fw-flux-harvesting",
    subgroup = "fw-flux-systems",
    order = "a[conditioning]-b[harvester-head]",
    enabled = false,
    energy_required = 4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-pressure-housing", amount = 1 },
      { type = "item", name = "fw-flow-regulator", amount = 1 },
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 30 },
    },
    results = {
      { type = "item", name = "fw-harvester-head", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.45 },
    },
    main_product = "fw-harvester-head",
  },
  {
    type = "recipe",
    name = "fw-flux-catalyst",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-2.png",
    icon_size = 64,
    category = "crafting",
    subgroup = "fw-flux-systems",
    order = "a[conditioning]-a[flux-catalyst]",
    enabled = false,
    energy_required = 2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-crystalised-flux", amount = 2 },
      { type = "item", name = "fw-sand", amount = 3 },
      { type = "item", name = "sulfur", amount = 1 },
    },
    results = {
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-stabilized-flux-crystal",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-3.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-a[stabilized-flux-crystal]",
    enabled = false,
    energy_required = 4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-crystalised-flux", amount = 3 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 42 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
      { type = "fluid", name = "fw-red-flux", amount = 10 },
      { type = "fluid", name = "fw-green-flux", amount = 8 },
      { type = "fluid", name = "fw-chlorine", amount = 15 },
    },
    results = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.45 },
    },
    main_product = "fw-stabilized-flux-crystal",
  },
  {
    type = "recipe",
    name = "fw-flux-lattice",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-metal-mesh.png",
    icon_size = 1024,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-b[flux-lattice]",
    enabled = false,
    energy_required = 4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 2 },
      { type = "item", name = "fw-circuit-contact", amount = 2 },
      { type = "item", name = "fw-glass", amount = 1 },
      { type = "item", name = "fw-solder-wire", amount = 2 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
    },
    results = {
      { type = "item", name = "fw-flux-lattice", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-annealed-cermet",
    icons = data.raw.item["fw-annealed-cermet"].icons,
    category = "fw-arc-smelting",
    subgroup = "fw-flux-systems",
    order = "b[systems]-c[annealed-cermet]",
    enabled = false,
    energy_required = 5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-cermet", amount = 2 },
      { type = "item", name = "fw-foundry-lining", amount = 1 },
      { type = "item", name = "titanium-plate", amount = 1 },
      { type = "fluid", name = "fw-red-flux", amount = 30 },
    },
    results = {
      { type = "item", name = "fw-annealed-cermet", amount = 2 },
    },
  },
  {
    type = "recipe",
    name = "fw-resonance-substrate",
    icons = data.raw.item["fw-resonance-substrate"].icons,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-d[resonance-substrate]",
    enabled = false,
    energy_required = 6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-circuit-substrate", amount = 2 },
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 1 },
      { type = "item", name = "fw-sensor-package", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 24 },
      { type = "fluid", name = "fw-red-flux", amount = 12 },
      { type = "fluid", name = "fw-green-flux", amount = 8 },
    },
    results = {
      { type = "item", name = "fw-resonance-substrate", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-condensed-flux-matrix",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-1-light.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-e[condensed-flux-matrix]",
    enabled = false,
    energy_required = 7.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 4 },
      { type = "item", name = "fw-flux-lattice", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 20 },
      { type = "fluid", name = "fw-yellow-flux", amount = 36 },
      { type = "fluid", name = "fw-red-flux", amount = 72 },
      { type = "fluid", name = "fw-green-flux", amount = 20 },
    },
    results = {
      { type = "item", name = "fw-condensed-flux-matrix", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.7 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-asteroid-deep-refining",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-3.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "c[refinement]-a[asteroid-deep-refining]",
    enabled = false,
    energy_required = 8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-asteroid-chunk", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "item", name = "fw-flux-lattice", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 16 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
      { type = "fluid", name = "fw-red-flux", amount = 30 },
    },
    results = {
      { type = "item", name = "fw-condensed-flux-matrix", amount = 1 },
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.65 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-resonance-cell",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-2-light.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-f[flux-resonance-cell]",
    enabled = false,
    energy_required = 10,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 2 },
      { type = "item", name = "fw-resonance-substrate", amount = 1 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 30 },
      { type = "fluid", name = "fw-red-flux", amount = 60 },
      { type = "fluid", name = "fw-green-flux", amount = 12 },
    },
    results = {
      { type = "item", name = "fw-flux-resonance-cell", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.8 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-phase-manifold",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-circuit-substrate.png",
    icon_size = 1024,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-g[flux-phase-manifold]",
    enabled = false,
    energy_required = 14,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-resonance-cell", amount = 2 },
      { type = "item", name = "fw-resonance-substrate", amount = 2 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "item", name = "fw-sensor-package", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 14 },
      { type = "fluid", name = "fw-yellow-flux", amount = 80 },
      { type = "fluid", name = "fw-red-flux", amount = 160 },
      { type = "fluid", name = "fw-green-flux", amount = 20 },
    },
    results = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.8 },
    },
  },
  {
    type = "recipe",
    name = "fw-rift-seed-crystallization",
    icon = "__FluxWorksAssets__/graphics/icons/items/crystallized-flux.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "c[refinement]-b[rift-seed-crystallization]",
    enabled = false,
    energy_required = 18,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 180 },
      { type = "fluid", name = "fw-yellow-flux", amount = 60 },
      { type = "fluid", name = "fw-red-flux", amount = 160 },
      { type = "fluid", name = "fw-green-flux", amount = 120 },
    },
    results = {
      { type = "item", name = "fw-crystalised-flux", amount = 48 },
      { type = "item", name = "fw-flux-phase-manifold", amount = 1, probability = 0.65 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 1, probability = 0.75 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-metallic-synthesis",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-1-light.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "c[refinement]-c[metallic-synthesis]",
    enabled = false,
    energy_required = 20,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 2 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 160 },
      { type = "fluid", name = "fw-yellow-flux", amount = 80 },
      { type = "fluid", name = "fw-red-flux", amount = 220 },
    },
    results = {
      { type = "item", name = "uranium-ore", amount = 10 },
      { type = "item", name = "titanium-ore", amount = 10 },
      { type = "item", name = "silicon-ore", amount = 16 },
      { type = "item", name = "fw-flux-phase-manifold", amount = 1, probability = 0.7 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 1, probability = 0.7 },
    },
  },
})
