local quantum_component = "processing-unit"
if data.raw.item["quantum-processor"] then
  quantum_component = "quantum-processor"
end

local K = 1000
local M = 1000000
local B = 1000000000

data:extend({
  {
    type = "recipe",
    name = "fw-harvester-head",
    icons = data.raw.item["fw-harvester-head"].icons,
    category = "fw-flux-harvesting",
    subgroup = "fw-flux-systems",
    order = "a[conditioning]-b[harvester-head]",
    enabled = false,
    energy_required = 4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-pressure-housing", amount = 1 },
      { type = "item", name = "fw-flow-regulator", amount = 1 },
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 12 },
    },
    results = {
      { type = "item", name = "fw-harvester-head", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.9 },
    },
    main_product = "fw-harvester-head",
  },
  {
    type = "recipe",
    name = "fw-flux-catalyst",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-2.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "a[conditioning]-a[flux-catalyst]",
    enabled = false,
    energy_required = 2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-crystalised-flux", amount = 2 },
      { type = "item", name = "fw-sand", amount = 3 },
      { type = "item", name = "sulfur", amount = 1 },
    },
    results = {
      { type = "item", name = "fw-flux-catalyst", amount = 3 },
    },
  },
  {
    type = "recipe",
    name = "fw-stabilized-flux-crystal",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-3.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-a[stabilized-flux-crystal]",
    enabled = false,
    energy_required = 4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-crystalised-flux", amount = 3 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 24 },
      { type = "fluid", name = "fw-yellow-flux", amount = 10 },
      { type = "fluid", name = "fw-red-flux", amount = 6 },
      { type = "fluid", name = "fw-green-flux", amount = 4 },
      { type = "fluid", name = "fw-chlorine", amount = 12 },
    },
    results = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 3 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.8 },
    },
    main_product = "fw-stabilized-flux-crystal",
  },
  {
    type = "recipe",
    name = "fw-flux-lattice",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-flux-lattice.png",
    icon_size = 1024,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-b[flux-lattice]",
    enabled = false,
    energy_required = 4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-metal-mesh", amount = 1 },
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 2 },
      { type = "item", name = "fw-glass", amount = 1 },
      { type = "item", name = "fw-solder-wire", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 16 },
    },
    results = {
      { type = "item", name = "fw-flux-lattice", amount = 2 },
    },
  },
  {
    type = "recipe",
    name = "fw-annealed-cermet",
    icons = data.raw.item["fw-annealed-cermet"].icons,
    category = "fw-arc-smelting",
    subgroup = "fw-flux-systems",
    order = "b[systems]-c[annealed-cermet]",
    enabled = false,
    energy_required = 5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-cermet", amount = 2 },
      { type = "item", name = "fw-foundry-lining", amount = 1 },
      { type = "item", name = "titanium-plate", amount = 1 },
      { type = "fluid", name = "fw-red-flux", amount = 30 },
    },
    results = {
      { type = "item", name = "fw-annealed-cermet", amount = 2 },
    },
  },
  {
    type = "recipe",
    name = "fw-resonance-substrate",
    icon = data.raw.item["fw-resonance-substrate"].icon,
    icon_size = data.raw.item["fw-resonance-substrate"].icon_size,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-d[resonance-substrate]",
    enabled = false,
    energy_required = 6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-circuit-substrate", amount = 1 },
      { type = "item", name = "fw-flux-lattice", amount = 1 },
      { type = "item", name = "fw-sensor-package", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
      { type = "fluid", name = "fw-green-flux", amount = 10 },
    },
    results = {
      { type = "item", name = "fw-resonance-substrate", amount = 2 },
    },
  },
  {
    type = "recipe",
    name = "fw-condensed-flux-matrix",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-condensed-flux-matrix.png",
    icon_size = 1024,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-e[condensed-flux-matrix]",
    enabled = false,
    energy_required = 7.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 2 },
      { type = "item", name = "fw-flux-lattice", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 20 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
      { type = "fluid", name = "fw-red-flux", amount = 18 },
      { type = "fluid", name = "fw-green-flux", amount = 8 },
    },
    results = {
      { type = "item", name = "fw-condensed-flux-matrix", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.85 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-resonance-cell",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-flux-resonance-cell.png",
    icon_size = 1024,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-f[flux-resonance-cell]",
    enabled = false,
    energy_required = 10,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-resonance-substrate", amount = 1 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 1 },
      { type = "item", name = "fw-field-winding", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 12 },
      { type = "fluid", name = "fw-red-flux", amount = 26 },
      { type = "fluid", name = "fw-green-flux", amount = 14 },
    },
    results = {
      { type = "item", name = "fw-flux-resonance-cell", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.95 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-phase-manifold",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-flux-phase-manifold.png",
    icon_size = 1024,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "b[systems]-g[flux-phase-manifold]",
    enabled = false,
    energy_required = 14,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-resonance-cell", amount = 2 },
      { type = "item", name = "fw-resonance-substrate", amount = 1 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 1 },
      { type = "item", name = "fw-field-winding", amount = 1 },
      { type = "item", name = "fw-sensor-package", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 16 },
      { type = "fluid", name = "fw-yellow-flux", amount = 28 },
      { type = "fluid", name = "fw-red-flux", amount = 34 },
      { type = "fluid", name = "fw-green-flux", amount = 16 },
    },
    results = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 2 },
    },
  },
  {
    type = "recipe",
    name = "fw-rift-seed-crystallization",
    icon = "__FluxWorksAssets__/graphics/icons/items/crystallized-flux.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "c[refinement]-b[rift-seed-crystallization]",
    enabled = false,
    energy_required = 18,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 180 },
      { type = "fluid", name = "fw-yellow-flux", amount = 60 },
      { type = "fluid", name = "fw-red-flux", amount = 160 },
      { type = "fluid", name = "fw-green-flux", amount = 120 },
    },
    results = {
      { type = "item", name = "fw-crystalised-flux", amount = 48 },
      { type = "item", name = "fw-flux-phase-manifold", amount = 1, probability = 0.65 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 1, probability = 0.75 },
    },
  },
  {
    type = "recipe",
    name = "fw-flux-metallic-synthesis",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux-1-light.png",
    icon_size = 64,
    category = "fw-flux-synthesis",
    subgroup = "fw-flux-systems",
    order = "c[refinement]-c[metallic-synthesis]",
    enabled = false,
    energy_required = 20,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 2 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 160 },
      { type = "fluid", name = "fw-yellow-flux", amount = 80 },
      { type = "fluid", name = "fw-red-flux", amount = 220 },
    },
    results = {
      { type = "item", name = "uranium-ore", amount = 10 },
      { type = "item", name = "titanium-ore", amount = 10 },
      { type = "item", name = "silicon-ore", amount = 16 },
      { type = "item", name = "fw-flux-phase-manifold", amount = 1, probability = 0.7 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 1, probability = 0.7 },
    },
  },
  {
    type = "recipe",
    name = "fw-phase-anchor",
    icons = data.raw.item["fw-phase-anchor"].icons,
    category = "fw-flux-condensing",
    subgroup = "fw-flux-systems",
    order = "d[utility]-a[phase-anchor]",
    enabled = false,
    energy_required = 60,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 2 },
      { type = "item", name = "fw-rift-stabilizer", amount = 1 },
      { type = "item", name = "fw-resonance-substrate", amount = 1 },
      { type = "item", name = "fw-field-winding", amount = 2 },
      { type = "item", name = "fw-pressure-housing", amount = 2 },
      { type = "item", name = "supercapacitor", amount = 2 },
      { type = "item", name = "fw-signal-conduit", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 250 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 180 * K },
      { type = "fluid", name = "fw-red-flux", amount = 220 * K },
      { type = "fluid", name = "fw-green-flux", amount = 140 * K },
    },
    results = {
      { type = "item", name = "fw-phase-anchor", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-entanglement-core",
    icons = data.raw.item["fw-entanglement-core"].icons,
    category = "fw-flux-condensing",
    subgroup = "fw-flux-systems",
    order = "d[utility]-b[entanglement-core]",
    enabled = false,
    energy_required = 70,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-em-core", amount = 1 },
      { type = "item", name = "fw-logic-matrix", amount = 2 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 1 },
      { type = "item", name = "fw-memory-die", amount = 2 },
      { type = "item", name = "fw-signal-conduit", amount = 3 },
      { type = "item", name = "fw-power-regulator", amount = 1 },
      { type = "item", name = quantum_component, amount = 3 },
      { type = "fluid", name = "fw-purple-flux", amount = 160 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 300 * K },
      { type = "fluid", name = "fw-red-flux", amount = 180 * K },
      { type = "fluid", name = "fw-green-flux", amount = 240 * K },
    },
    results = {
      { type = "item", name = "fw-entanglement-core", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-reservoir-lining",
    icons = data.raw.item["fw-reservoir-lining"].icons,
    category = "fw-flux-condensing",
    subgroup = "fw-flux-systems",
    order = "d[utility]-c[reservoir-lining]",
    enabled = false,
    energy_required = 55,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-thermal-buffer", amount = 2 },
      { type = "item", name = "fw-flow-regulator", amount = 2 },
      { type = "item", name = "fw-ceramic-casing", amount = 3 },
      { type = "item", name = "fw-cryo-coil", amount = 2 },
      { type = "item", name = "fw-rubber-sheet", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 200 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 120 * K },
      { type = "fluid", name = "fw-red-flux", amount = 260 * K },
      { type = "fluid", name = "fw-green-flux", amount = 100 * K },
    },
    results = {
      { type = "item", name = "fw-reservoir-lining", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-compression-baffle",
    icons = data.raw.item["fw-compression-baffle"].icons,
    category = "fw-flux-condensing",
    subgroup = "fw-flux-systems",
    order = "d[utility]-d[compression-baffle]",
    enabled = false,
    energy_required = 55,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flow-regulator", amount = 2 },
      { type = "item", name = "fw-inline-filter", amount = 2 },
      { type = "item", name = "fw-flux-lattice", amount = 2 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 1 },
      { type = "item", name = "fw-pressure-housing", amount = 2 },
      { type = "item", name = "fw-sensor-diode", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 240 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 180 * K },
      { type = "fluid", name = "fw-red-flux", amount = 320 * K },
      { type = "fluid", name = "fw-green-flux", amount = 80 * K },
    },
    results = {
      { type = "item", name = "fw-compression-baffle", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-thermal-phase-gasket",
    icons = data.raw.item["fw-thermal-phase-gasket"].icons,
    category = "fw-flux-condensing",
    subgroup = "fw-flux-systems",
    order = "d[utility]-e[thermal-phase-gasket]",
    enabled = false,
    energy_required = 48,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-rubber-sheet", amount = 3 },
      { type = "item", name = "fw-thermal-buffer", amount = 2 },
      { type = "item", name = "fw-ceramic-insulator", amount = 3 },
      { type = "item", name = "fw-flow-regulator", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 150 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 100 * K },
      { type = "fluid", name = "fw-red-flux", amount = 280 * K },
      { type = "fluid", name = "fw-green-flux", amount = 70 * K },
    },
    results = {
      { type = "item", name = "fw-thermal-phase-gasket", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-rift-coupler",
    icons = data.raw.item["fw-rift-coupler"].icons,
    category = "fw-flux-condensing",
    subgroup = "fw-flux-exchange",
    order = "d[utility]-f[rift-coupler]",
    enabled = false,
    energy_required = 120,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-phase-anchor", amount = 2 },
      { type = "item", name = "fw-entanglement-core", amount = 2 },
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-promethium-matrix", amount = 1 },
      { type = "item", name = "fw-thermal-phase-gasket", amount = 2 },
      { type = "item", name = "superconductor", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 1 * M },
      { type = "fluid", name = "fw-yellow-flux", amount = 600 * K },
      { type = "fluid", name = "fw-red-flux", amount = 1200 * K },
      { type = "fluid", name = "fw-green-flux", amount = 500 * K },
    },
    results = {
      { type = "item", name = "fw-rift-coupler", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-phase-vault",
    icons = data.raw.item["fw-phase-vault"].icons,
    category = "fw-flux-condensing",
    subgroup = "fw-flux-exchange",
    order = "d[utility]-g[phase-vault]",
    enabled = false,
    energy_required = 180,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "storage-chest", amount = 4 },
      { type = "item", name = "fw-phase-anchor", amount = 2 },
      { type = "item", name = "fw-entanglement-core", amount = 2 },
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-compression-baffle", amount = 4 },
      { type = "item", name = "fw-pressure-housing", amount = 3 },
      { type = "item", name = "fw-power-regulator", amount = 3 },
      { type = "item", name = "superconductor", amount = 4 },
      { type = "fluid", name = "fw-purple-flux", amount = 2 * M },
      { type = "fluid", name = "fw-yellow-flux", amount = 1500 * K },
      { type = "fluid", name = "fw-red-flux", amount = 2200 * K },
      { type = "fluid", name = "fw-green-flux", amount = 900 * K },
    },
    results = {
      { type = "item", name = "fw-phase-vault", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-spectral-reservoir",
    icons = data.raw.item["fw-spectral-reservoir"].icons,
    category = "fw-flux-condensing",
    subgroup = "fw-flux-exchange",
    order = "d[utility]-h[spectral-reservoir]",
    enabled = false,
    energy_required = 180,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "storage-tank", amount = 3 },
      { type = "item", name = "fw-reservoir-lining", amount = 4 },
      { type = "item", name = "fw-entanglement-core", amount = 2 },
      { type = "item", name = "fw-phase-anchor", amount = 1 },
      { type = "item", name = "fw-thermal-phase-gasket", amount = 4 },
      { type = "item", name = "fw-thermal-buffer", amount = 3 },
      { type = "item", name = "fw-cryo-coil", amount = 3 },
      { type = "item", name = "supercapacitor", amount = 4 },
      { type = "fluid", name = "fw-purple-flux", amount = 1800 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 1200 * K },
      { type = "fluid", name = "fw-red-flux", amount = 2600 * K },
      { type = "fluid", name = "fw-green-flux", amount = 1100 * K },
    },
    results = {
      { type = "item", name = "fw-spectral-reservoir", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-rift-exchange-gate",
    icons = data.raw.item["fw-rift-exchange-gate"].icons,
    category = "fw-flux-condensing",
    subgroup = "fw-flux-exchange",
    order = "d[utility]-i[rift-exchange-gate]",
    enabled = false,
    energy_required = 300,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-rift-coupler", amount = 4 },
      { type = "item", name = "fw-phase-anchor", amount = 1 },
      { type = "item", name = "fw-entanglement-core", amount = 2 },
      { type = "item", name = "fw-phase-vault", amount = 1 },
      { type = "item", name = "fw-spectral-reservoir", amount = 1 },
      { type = "item", name = "fw-thermal-phase-gasket", amount = 4 },
      { type = "item", name = "fw-promethium-matrix", amount = 2 },
      { type = "item", name = "fusion-reactor-equipment", amount = 2 },
      { type = "item", name = "superconductor", amount = 6 },
      { type = "item", name = quantum_component, amount = 6 },
      { type = "fluid", name = "fw-purple-flux", amount = 4 * M },
      { type = "fluid", name = "fw-yellow-flux", amount = 3 * M },
      { type = "fluid", name = "fw-red-flux", amount = 5 * M },
      { type = "fluid", name = "fw-green-flux", amount = 2500 * K },
    },
    results = {
      { type = "item", name = "fw-rift-exchange-gate", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-storm-spine-segment",
    icons = data.raw.item["fw-storm-spine-segment"].icons,
    category = "fw-origin-forging",
    subgroup = "fw-flux-origin-projects",
    order = "a[infrastructure]-a[storm-spine-segment]",
    enabled = false,
    energy_required = 90,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-phase-anchor", amount = 2 },
      { type = "item", name = "fw-annealed-cermet", amount = 8 },
      { type = "item", name = "fw-rift-stabilizer", amount = 2 },
      { type = "item", name = "fusion-power-cell", amount = 4 },
      { type = "item", name = "tungsten-carbide", amount = 6 },
      { type = "item", name = "carbon-fiber", amount = 6 },
      { type = "fluid", name = "fw-purple-flux", amount = 900 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 600 * K },
      { type = "fluid", name = "fw-red-flux", amount = 1400 * K },
      { type = "fluid", name = "fw-green-flux", amount = 500 * K },
    },
    results = {
      { type = "item", name = "fw-storm-spine-segment", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-origin-crucible-lining",
    icons = data.raw.item["fw-origin-crucible-lining"].icons,
    category = "fw-origin-forging",
    subgroup = "fw-flux-origin-projects",
    order = "a[infrastructure]-b[origin-crucible-lining]",
    enabled = false,
    energy_required = 100,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-reservoir-lining", amount = 3 },
      { type = "item", name = "fw-compression-baffle", amount = 3 },
      { type = "item", name = "fw-thermal-phase-gasket", amount = 4 },
      { type = "item", name = "fw-promethium-matrix", amount = 2 },
      { type = "item", name = "superconductor", amount = 8 },
      { type = "item", name = "lithium-plate", amount = 12 },
      { type = "fluid", name = "fw-purple-flux", amount = 1200 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 700 * K },
      { type = "fluid", name = "fw-red-flux", amount = 900 * K },
      { type = "fluid", name = "fw-green-flux", amount = 700 * K },
    },
    results = {
      { type = "item", name = "fw-origin-crucible-lining", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-harmonic-lattice-core",
    icons = data.raw.item["fw-harmonic-lattice-core"].icons,
    category = "fw-origin-forging",
    subgroup = "fw-flux-origin-projects",
    order = "a[infrastructure]-c[harmonic-lattice-core]",
    enabled = false,
    energy_required = 110,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-lattice", amount = 8 },
      { type = "item", name = "fw-entanglement-core", amount = 2 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 6 },
      { type = "item", name = "supercapacitor", amount = 6 },
      { type = "item", name = quantum_component, amount = 6 },
      { type = "fluid", name = "fw-purple-flux", amount = 1500 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 1000 * K },
      { type = "fluid", name = "fw-red-flux", amount = 800 * K },
      { type = "fluid", name = "fw-green-flux", amount = 600 * K },
    },
    results = {
      { type = "item", name = "fw-harmonic-lattice-core", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-living-reactor-weave",
    icons = data.raw.item["fw-living-reactor-weave"].icons,
    category = "fw-origin-forging",
    subgroup = "fw-flux-origin-projects",
    order = "b[projects]-a[living-reactor-weave]",
    enabled = false,
    energy_required = 120,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fusion-power-cell", amount = 8 },
      { type = "item", name = "bioflux", amount = 8 },
      { type = "item", name = "superconductor", amount = 4 },
      { type = "item", name = "carbon-fiber", amount = 8 },
      { type = "item", name = "fw-resonance-substrate", amount = 4 },
      { type = "fluid", name = "fw-purple-flux", amount = 700 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 900 * K },
      { type = "fluid", name = "fw-red-flux", amount = 900 * K },
      { type = "fluid", name = "fw-green-flux", amount = 1600 * K },
    },
    results = {
      { type = "item", name = "fw-living-reactor-weave", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-origin-catalyst-manifold",
    icons = data.raw.item["fw-origin-catalyst-manifold"].icons,
    category = "fw-origin-forging",
    subgroup = "fw-flux-origin-projects",
    order = "b[projects]-b[origin-catalyst-manifold]",
    enabled = false,
    energy_required = 130,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 6 },
      { type = "item", name = "fw-rift-coupler", amount = 2 },
      { type = "item", name = "fw-harmonic-lattice-core", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 8 },
      { type = "item", name = "fw-promethium-primer", amount = 4 },
      { type = "fluid", name = "fw-purple-flux", amount = 1600 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 1800 * K },
      { type = "fluid", name = "fw-red-flux", amount = 1200 * K },
      { type = "fluid", name = "fw-green-flux", amount = 700 * K },
    },
    results = {
      { type = "item", name = "fw-origin-catalyst-manifold", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-storm-spine",
    icons = data.raw.item["fw-storm-spine"].icons,
    category = "fw-origin-forging",
    subgroup = "fw-flux-origin-projects",
    order = "c[megastructures]-a[storm-spine]",
    enabled = false,
    energy_required = 180,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-storm-spine-segment", amount = 6 },
      { type = "item", name = "fw-harmonic-lattice-core", amount = 2 },
      { type = "item", name = "fw-origin-catalyst-manifold", amount = 2 },
      { type = "item", name = "fw-rift-stabilizer", amount = 4 },
      { type = "item", name = "fusion-power-cell", amount = 10 },
      { type = "fluid", name = "fw-purple-flux", amount = 2 * M },
      { type = "fluid", name = "fw-yellow-flux", amount = 1500 * K },
      { type = "fluid", name = "fw-red-flux", amount = 3 * M },
      { type = "fluid", name = "fw-green-flux", amount = 900 * K },
    },
    results = {
      { type = "item", name = "fw-storm-spine", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-origin-crucible",
    icons = data.raw.item["fw-origin-crucible"].icons,
    category = "fw-origin-forging",
    subgroup = "fw-flux-origin-projects",
    order = "c[megastructures]-b[origin-crucible]",
    enabled = false,
    energy_required = 200,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-origin-crucible-lining", amount = 6 },
      { type = "item", name = "fw-living-reactor-weave", amount = 2 },
      { type = "item", name = "fw-origin-catalyst-manifold", amount = 2 },
      { type = "item", name = "fw-promethium-matrix", amount = 4 },
      { type = "item", name = "superconductor", amount = 12 },
      { type = "fluid", name = "fw-purple-flux", amount = 2200 * K },
      { type = "fluid", name = "fw-yellow-flux", amount = 2 * M },
      { type = "fluid", name = "fw-red-flux", amount = 1800 * K },
      { type = "fluid", name = "fw-green-flux", amount = 1800 * K },
    },
    results = {
      { type = "item", name = "fw-origin-crucible", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-universal-collapse-core",
    icons = data.raw.item["fw-universal-collapse-core"].icons,
    category = "fw-origin-forging",
    subgroup = "fw-flux-origin-projects",
    order = "d[transcendence]-a[universal-collapse-core]",
    enabled = false,
    energy_required = 600,
    allow_productivity = false,
    ingredients = {
      { type = "item", name = "fw-storm-spine", amount = 4 },
      { type = "item", name = "fw-origin-crucible", amount = 4 },
      { type = "item", name = "fw-rift-exchange-gate", amount = 4 },
      { type = "item", name = "fw-origin-catalyst-manifold", amount = 8 },
      { type = "item", name = "fw-harmonic-lattice-core", amount = 12 },
      { type = "fluid", name = "fw-purple-flux", amount = 1 * B },
      { type = "fluid", name = "fw-yellow-flux", amount = 1 * B },
      { type = "fluid", name = "fw-red-flux", amount = 1 * B },
      { type = "fluid", name = "fw-green-flux", amount = 1 * B },
    },
    results = {
      { type = "item", name = "fw-universal-collapse-core", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-genesis-ark",
    icons = data.raw.item["fw-genesis-ark"].icons,
    category = "fw-origin-forging",
    subgroup = "fw-flux-origin-projects",
    order = "d[transcendence]-b[genesis-ark]",
    enabled = false,
    energy_required = 1200,
    allow_productivity = false,
    ingredients = {
      { type = "item", name = "fw-universal-collapse-core", amount = 1000 },
      { type = "item", name = "fw-storm-spine", amount = 64 },
      { type = "item", name = "fw-origin-crucible", amount = 64 },
      { type = "item", name = "fw-origin-catalyst-manifold", amount = 64 },
      { type = "item", name = "fw-rift-exchange-gate", amount = 16 },
    },
    results = {
      { type = "item", name = "fw-genesis-ark", amount = 1 },
    },
  },
  {
    type = "recipe",
    name = "fw-origin-singularity",
    icons = data.raw.item["fw-origin-singularity"].icons,
    category = "fw-origin-forging",
    subgroup = "fw-flux-origin-projects",
    order = "d[transcendence]-c[origin-singularity]",
    enabled = false,
    energy_required = 900,
    allow_productivity = false,
    ingredients = {
      { type = "item", name = "fw-genesis-ark", amount = 1 },
      { type = "item", name = "fw-universal-collapse-core", amount = 4 },
      { type = "item", name = "fw-origin-catalyst-manifold", amount = 16 },
      { type = "item", name = "fw-storm-spine", amount = 8 },
      { type = "item", name = "fw-origin-crucible", amount = 8 },
      { type = "item", name = "promethium-science-pack", amount = 200 },
      { type = "item", name = "quantum-processor", amount = 64 },
      { type = "item", name = "fusion-power-cell", amount = 64 },
    },
    results = {
      { type = "item", name = "fw-origin-singularity", amount = 1 },
    },
  },
})
