local M = {}

-- Hand-tuned starter numbers for the flux economy.
-- Yes, the resolver can figure a lot out on its own.
-- No, I do not trust it to avoid goofy fallback values on the important stuff.
M.item_values = {
  -- Dirt-tier world junk and other things you mostly just yank out of the ground.
  ["stone"] = 2,
  ["coal"] = 3,
  ["copper-ore"] = 4,
  ["iron-ore"] = 4,
  ["uranium-ore"] = 12,
  ["calcite"] = 8,
  ["tungsten-ore"] = 24,
  ["scrap"] = 6,
  ["ice"] = 8,
  ["wood"] = 20,
  ["raw-fish"] = 250,
  ["spoilage"] = 50,
  ["biter-egg"] = 3500,
  ["pentapod-egg"] = 8000,

  -- The usual factory bread-and-butter.
  ["iron-plate"] = 8,
  ["copper-plate"] = 8,
  ["steel-plate"] = 28,
  ["stone-brick"] = 7,
  ["plastic-bar"] = 40,
  ["solid-fuel"] = 120,
  ["sulfur"] = 45,
  ["battery"] = 90,

  -- Science packs are progression keys, not just a grocery list.
  ["automation-science-pack"] = 160,
  ["logistic-science-pack"] = 380,
  ["military-science-pack"] = 700,
  ["chemical-science-pack"] = 1200,
  ["production-science-pack"] = 2200,
  ["utility-science-pack"] = 2600,
  ["space-science-pack"] = 4500,

  -- Modules need hard floors or tier 3 starts doing weird clown math.
  ["speed-module"] = 6000,
  ["speed-module-2"] = 60000,
  ["speed-module-3"] = 350000,
  ["efficiency-module"] = 6000,
  ["efficiency-module-2"] = 60000,
  ["efficiency-module-3"] = 350000,
  ["productivity-module"] = 6000,
  ["productivity-module-2"] = 60000,
  ["productivity-module-3"] = 350000,
  ["quality-module"] = 6000,
  ["quality-module-2"] = 60000,
  ["quality-module-3"] = 350000,
  -- Moving bits, power bits, and all the normal factory guts.
  ["iron-gear-wheel"] = 14,
  ["iron-stick"] = 5,
  ["copper-cable"] = 8,
  ["pipe"] = 12,
  ["transport-belt"] = 30,
  ["underground-belt"] = 260,
  ["splitter"] = 1500,
  ["fast-transport-belt"] = 260,
  ["fast-underground-belt"] = 800,
  ["fast-splitter"] = 3200,
  ["express-transport-belt"] = 700,
  ["express-underground-belt"] = 2400,
  ["express-splitter"] = 9000,
  ["turbo-transport-belt"] = 1400,
  ["turbo-underground-belt"] = 5200,
  ["turbo-splitter"] = 18000,
  ["inserter"] = 320,
  ["long-handed-inserter"] = 400,
  ["fast-inserter"] = 1000,
  ["bulk-inserter"] = 3000,
  ["stack-inserter"] = 3200,
  ["engine-unit"] = 500,
  ["electric-engine-unit"] = 1000,
  ["flying-robot-frame"] = 1800,
  ["burner-mining-drill"] = 220,
  ["electric-mining-drill"] = 1400,
  ["pumpjack"] = 2500,
  ["steam-engine"] = 800,
  ["steam-turbine"] = 8000,
  ["solar-panel"] = 2500,
  ["accumulator"] = 1800,
  ["heat-pipe"] = 1800,
  ["heat-exchanger"] = 9000,
  ["nuclear-reactor"] = 90000,
  ["boiler"] = 120,
  ["rocket-launcher"] = 12000,
  ["pistol"] = 250,
  ["shotgun"] = 800,
  ["combat-shotgun"] = 2200,
  ["submachine-gun"] = 900,
  ["flamethrower"] = 1800,

  -- Personal equipment is still progression hardware even if it stacks in your pocket.
  ["night-vision-equipment"] = 3000,
  ["belt-immunity-equipment"] = 2200,
  ["solar-panel-equipment"] = 7000,
  ["battery-equipment"] = 1800,
  ["battery-mk2-equipment"] = 50000,
  ["battery-mk3-equipment"] = 250000,
  ["energy-shield-equipment"] = 10000,
  ["energy-shield-mk2-equipment"] = 75000,
  ["personal-roboport-equipment"] = 12000,
  ["personal-roboport-mk2-equipment"] = 80000,
  ["exoskeleton-equipment"] = 45000,
  ["personal-laser-defense-equipment"] = 65000,
  ["discharge-defense-equipment"] = 50000,
  ["fission-reactor-equipment"] = 650000,
  ["fusion-reactor-equipment"] = 4200000,

  -- Vehicles are tooltip values only. The condenser is not cloning cars. Relax.
  ["car"] = 12000,
  ["tank"] = 35000,
  ["locomotive"] = 20000,
  ["cargo-wagon"] = 12000,
  ["fluid-wagon"] = 14000,
  ["artillery-wagon"] = 90000,
  ["spidertron"] = 250000,

  -- Circuits stay a little spicy so blue chips do not end up feeling free.
  ["electronic-circuit"] = 180,
  ["advanced-circuit"] = 700,
  ["processing-unit"] = 3000,
  ["quantum-processor"] = 12000,

  -- Combat junk needs real prices or the condenser turns into a war-crimes printer.
  ["firearm-magazine"] = 120,
  ["piercing-rounds-magazine"] = 280,
  ["uranium-rounds-magazine"] = 900,
  ["shotgun-shell"] = 180,
  ["piercing-shotgun-shell"] = 480,
  ["cannon-shell"] = 360,
  ["explosive-cannon-shell"] = 450,
  ["uranium-cannon-shell"] = 900,
  ["explosive-uranium-cannon-shell"] = 1100,
  ["artillery-shell"] = 5000,
  ["rocket"] = 300,
  ["explosive-rocket"] = 700,
  ["atomic-bomb"] = 250000,
  ["flamethrower-ammo"] = 500,
  ["land-mine"] = 120,
  ["grenade"] = 350,
  ["cluster-grenade"] = 1200,
  ["poison-capsule"] = 900,
  ["slowdown-capsule"] = 900,
  ["defender-capsule"] = 1100,
  ["distractor-capsule"] = 2800,
  ["destroyer-capsule"] = 9000,

  -- Rocket bits and other late vanilla staples.
  ["low-density-structure"] = 160,
  ["rocket-fuel"] = 700,
  ["rocket-part"] = 2400,
  ["satellite"] = 2200,
  ["uranium-235"] = 1500,
  ["capture-robot-rocket"] = 2500,

  -- Space Age anchors, and promethium still gets treated like the scary endgame trophy.
  ["bioflux"] = 450,
  ["nutrients"] = 120,
  ["jelly"] = 25,
  ["yumako-mash"] = 25,
  ["jellynut"] = 40,
  ["yumako"] = 40,
  ["jellynut-seed"] = 500,
  ["yumako-seed"] = 500,
  ["tree-seed"] = 400,
  ["copper-bacteria"] = 80,
  ["iron-bacteria"] = 80,
  ["artificial-jellynut-soil"] = 300,
  ["artificial-yumako-soil"] = 300,
  ["overgrowth-jellynut-soil"] = 1200,
  ["overgrowth-yumako-soil"] = 1200,
  ["holmium-ore"] = 36,
  ["holmium-plate"] = 64,
  ["tungsten-plate"] = 80,
  ["tungsten-carbide"] = 140,
  ["lithium"] = 90,
  ["lithium-plate"] = 180,
  ["carbon-fiber"] = 650,
  ["superconductor"] = 1200,
  ["supercapacitor"] = 1000,
  ["electromagnetic-science-pack"] = 2500,
  ["agricultural-science-pack"] = 2500,
  ["metallurgic-science-pack"] = 2500,
  ["cryogenic-science-pack"] = 5000,
  ["fw-promethium-shard"] = 900,
  ["fw-promethium-primer"] = 4200,
  ["fw-harvester-head"] = 600,
  ["fw-annealed-cermet"] = 950,
  ["fw-resonance-substrate"] = 220,
  ["fw-origin-forge"] = 220000,
  ["fw-storm-spine-segment"] = 18000,
  ["fw-origin-crucible-lining"] = 22000,
  ["fw-harmonic-lattice-core"] = 28000,
  ["fw-living-reactor-weave"] = 32000,
  ["fw-origin-catalyst-manifold"] = 42000,
  ["fw-storm-spine"] = 140000,
  ["fw-origin-crucible"] = 170000,
  ["fw-universal-collapse-core"] = 4000000000,
  ["fw-genesis-ark"] = 5000000000000,
  ["fw-origin-singularity"] = 9000000000000,
  ["promethium-asteroid-chunk"] = 6000,
  ["promethium-science-pack"] = 25000,

  -- Big late-game toys, angry weapons, and power bricks.
  ["teslagun"] = 40000,
  ["tesla-ammo"] = 8000,
  ["tesla-turret"] = 180000,
  ["railgun"] = 320000,
  ["railgun-ammo"] = 6000,
  ["railgun-turret"] = 1600000,
  ["rocket-turret"] = 90000,
  ["big-mining-drill"] = 70000,
  ["foundry"] = 80000,
  ["biochamber"] = 50000,
  ["biolab"] = 250000,
  ["cryogenic-plant"] = 140000,
  ["electromagnetic-plant"] = 180000,
  ["agricultural-tower"] = 40000,
  ["fusion-power-cell"] = 1800,
  ["fusion-generator"] = 1200000,
  ["fusion-reactor"] = 4200000,

  -- FluxWorks raw stuff and early-middle intermediates.
  -- Mixed deposits flatten a lot of these by midgame, so keep the floors close together
  -- and save the real tax for titanium and its chlorine nonsense.
  ["lead-ore"] = 4,
  ["bauxite-ore"] = 5,
  ["tin-ore"] = 5,
  ["silicon-ore"] = 5,
  ["titanium-ore"] = 9,
  ["fw-crystalised-flux"] = 14,
  ["fw-salt"] = 4,
  ["fw-sand"] = 3,
  ["fw-carbon"] = 8,
  ["fw-resin"] = 20,
  ["fw-crushed-copper-ore"] = 3,
  ["fw-crushed-iron-ore"] = 3,
  ["fw-crushed-lead-ore"] = 4,
  ["fw-crushed-titanium-ore"] = 9,
  ["lead-plate"] = 8,
  ["tin-plate"] = 9,
  ["titanium-plate"] = 20,
  ["aluminum-plate"] = 12,
  ["silicon"] = 10,

  -- The proper home-grown FluxWorks part ladder.
  ["fw-glass"] = 7,
  ["fw-circuit-contact"] = 12,
  ["fw-solder-wire"] = 7,
  ["fw-tinned-cable"] = 11,
  ["fw-conductor-bundle"] = 28,
  ["fw-ribbon-cable"] = 42,
  ["fw-capacitor"] = 72,
  ["fw-inductor-coil"] = 60,
  ["fw-transformer-core"] = 120,
  ["fw-sensor-package"] = 180,
  ["fw-microchip"] = 150,
  ["fw-memory-die"] = 260,
  ["fw-flux-catalyst"] = 24,
  ["fw-stabilized-flux-crystal"] = 34,
  ["fw-flux-lattice"] = 90,
  ["fw-condensed-flux-matrix"] = 180,
  ["fw-flux-resonance-cell"] = 320,
  ["fw-flux-phase-manifold"] = 860,
  ["fw-aquilo-cryogel"] = 520,
  ["fw-gleba-spore-resin"] = 540,
  ["fw-fulgora-static-mesh"] = 760,
  ["fw-vulcanus-slag-cermet"] = 820,
  ["fw-logic-matrix"] = 980,
  ["fw-rift-stabilizer"] = 5200,
  ["fw-flux-condenser"] = 2200,
  ["fw-shattered-convergence-array"] = 18000,
}

-- Hard locks are the "do not argue with me" tier.
-- Useful for raw resources, weird modded trophies, and anything we know the
-- generic resolver should not try to outsmart.
M.item_value_locks = {}

M.fluid_values = {
  ["water"] = 0.02,
  ["steam"] = 0.02,
  ["petroleum-gas"] = 0.12,
  ["light-oil"] = 0.22,
  ["heavy-oil"] = 0.24,
  ["sulfuric-acid"] = 0.36,
  ["lubricant"] = 0.5,
  ["crude-oil"] = 0.10,
  ["electrolyte"] = 4.0,
  ["holmium-solution"] = 1.2,
  ["lava"] = 0.18,
  ["molten-iron"] = 0.35,
  ["molten-copper"] = 0.35,
  ["ammonia"] = 0.8,
  ["ammoniacal-solution"] = 0.6,
  ["fluorine"] = 1.5,
  ["lithium-brine"] = 0.9,
  ["fluoroketone-hot"] = 1.2,
  ["fluoroketone-cold"] = 1.0,
  ["thruster-fuel"] = 1.2,
  ["thruster-oxidizer"] = 1.2,
  ["fusion-plasma"] = 8.0,

  ["fw-purple-flux"] = 1.0,
  ["fw-yellow-flux"] = 1.8,
  ["fw-red-flux"] = 2.2,
  ["fw-green-flux"] = 2.0,
  ["fw-chlorine"] = 0.8,
  ["fw-latex"] = 0.9,
  ["fw-blasting-gel"] = 1.6,
  ["fw-napalm"] = 2.2,
}

M.item_color_overrides = {
  ["spoilage"] = { "green" },
  ["nutrients"] = { "green" },
  ["bioflux"] = { "green" },
  ["yumako"] = { "green" },
  ["jellynut"] = { "green" },
  ["yumako-mash"] = { "green" },
  ["jelly"] = { "green" },
  ["yumako-seed"] = { "green" },
  ["jellynut-seed"] = { "green" },
  ["tree-seed"] = { "green" },
  ["raw-fish"] = { "green" },
  ["biter-egg"] = { "green" },
  ["pentapod-egg"] = { "green" },
  ["copper-bacteria"] = { "green" },
  ["iron-bacteria"] = { "green" },

  ["solid-fuel"] = { "red" },
  ["rocket-fuel"] = { "red" },
  ["nuclear-fuel"] = { "red" },

  ["sulfur"] = { "yellow" },
  ["plastic-bar"] = { "yellow" },
  ["explosives"] = { "yellow" },
  ["battery"] = { "yellow" },
  ["fw-salt"] = { "yellow" },
  ["fw-resin"] = { "yellow" },
  ["fw-rubber-sheet"] = { "yellow" },
  ["fw-gunpowder"] = { "yellow" },
}

M.fluid_color_overrides = {
  ["water"] = {},
  ["steam"] = {},

  ["petroleum-gas"] = { "yellow" },
  ["light-oil"] = { "yellow" },
  ["heavy-oil"] = { "yellow" },
  ["crude-oil"] = { "yellow" },
  ["sulfuric-acid"] = { "yellow" },
  ["lubricant"] = { "yellow" },
  ["electrolyte"] = { "yellow" },
  ["fw-chlorine"] = { "yellow" },
  ["fw-latex"] = { "yellow" },
  ["fw-blasting-gel"] = { "yellow" },
  ["fw-napalm"] = { "red", "yellow" },
  ["biolubricant"] = { "green" },
}

M.default_time_value = 6

M.recipe_category_multipliers = {
  ["crafting"] = 1.0,
  ["advanced-crafting"] = 1.05,
  ["crafting-with-fluid"] = 1.10,
  ["electronics"] = 1.35,
  ["electronics-with-fluid"] = 1.50,
  ["smelting"] = 1.18,
  ["chemistry"] = 1.15,
  ["centrifuging"] = 1.20,
  ["electromagnetics"] = 1.22,
  ["electromagnetics-or-assembling"] = 1.22,
  ["metallurgy"] = 1.20,
  ["metallurgy-or-assembling"] = 1.20,
  ["organic-or-assembling"] = 1.18,
  ["cryogenics"] = 1.25,
  ["cryogenics-or-assembling"] = 1.25,
  ["rocket-building"] = 1.30,
  ["fw-flux-harvesting"] = 1.16,
  ["fw-arc-smelting"] = 1.24,
  ["fw-flux-synthesis"] = 1.38,
  ["fw-petrochemistry"] = 1.24,
  ["fw-hydraulics"] = 1.28,
  ["fw-atomic-enrichment"] = 1.34,
  ["fw-flux-condensing"] = 1.35,
}

M.recipe_category_time_multipliers = {
  ["crafting"] = 1.0,
  ["advanced-crafting"] = 1.15,
  ["crafting-with-fluid"] = 1.25,
  ["electronics"] = 1.8,
  ["electronics-with-fluid"] = 2.2,
  ["smelting"] = 1.5,
  ["chemistry"] = 1.8,
  ["centrifuging"] = 2.0,
  ["electromagnetics"] = 2.3,
  ["electromagnetics-or-assembling"] = 2.3,
  ["metallurgy"] = 2.2,
  ["metallurgy-or-assembling"] = 2.2,
  ["organic-or-assembling"] = 2.0,
  ["cryogenics"] = 2.5,
  ["cryogenics-or-assembling"] = 2.5,
  ["rocket-building"] = 3.0,
  ["fw-flux-harvesting"] = 2.0,
  ["fw-arc-smelting"] = 2.15,
  ["fw-flux-synthesis"] = 2.45,
  ["fw-petrochemistry"] = 2.1,
  ["fw-hydraulics"] = 2.2,
  ["fw-atomic-enrichment"] = 2.6,
  ["fw-flux-condensing"] = 1.0,
}

M.recipe_category_color_weights = {
  ["crafting"] = { purple = 0.75, yellow = 0.10, red = 0.10, green = 0.05 },
  ["advanced-crafting"] = { purple = 0.70, yellow = 0.20, red = 0.05, green = 0.05 },
  ["crafting-with-fluid"] = { purple = 0.45, yellow = 0.45, red = 0.05, green = 0.05 },
  ["electronics"] = { purple = 0.50, yellow = 0.35, red = 0.10, green = 0.05 },
  ["electronics-with-fluid"] = { purple = 0.40, yellow = 0.45, red = 0.10, green = 0.05 },
  ["smelting"] = { purple = 0.90, yellow = 0.05, red = 0.05, green = 0.00 },
  ["chemistry"] = { purple = 0.15, yellow = 0.75, red = 0.08, green = 0.02 },
  ["centrifuging"] = { purple = 0.55, yellow = 0.20, red = 0.20, green = 0.05 },
  ["electromagnetics"] = { purple = 0.55, yellow = 0.30, red = 0.10, green = 0.05 },
  ["electromagnetics-or-assembling"] = { purple = 0.55, yellow = 0.30, red = 0.10, green = 0.05 },
  ["metallurgy"] = { purple = 0.85, yellow = 0.05, red = 0.10, green = 0.00 },
  ["metallurgy-or-assembling"] = { purple = 0.80, yellow = 0.10, red = 0.10, green = 0.00 },
  ["organic-or-assembling"] = { purple = 0.15, yellow = 0.10, red = 0.05, green = 0.70 },
  ["cryogenics"] = { purple = 0.55, yellow = 0.20, red = 0.20, green = 0.05 },
  ["cryogenics-or-assembling"] = { purple = 0.55, yellow = 0.20, red = 0.20, green = 0.05 },
  ["rocket-building"] = { purple = 0.35, yellow = 0.15, red = 0.45, green = 0.05 },
  ["fw-flux-harvesting"] = { purple = 0.30, yellow = 0.45, red = 0.20, green = 0.05 },
  ["fw-arc-smelting"] = { purple = 0.15, yellow = 0.10, red = 0.70, green = 0.05 },
  ["fw-flux-synthesis"] = { purple = 0.28, yellow = 0.24, red = 0.26, green = 0.22 },
  ["fw-petrochemistry"] = { purple = 0.12, yellow = 0.68, red = 0.15, green = 0.05 },
  ["fw-hydraulics"] = { purple = 0.22, yellow = 0.48, red = 0.25, green = 0.05 },
  ["fw-atomic-enrichment"] = { purple = 0.40, yellow = 0.15, red = 0.40, green = 0.05 },
  ["fw-flux-condensing"] = { purple = 0.25, yellow = 0.25, red = 0.25, green = 0.25 },
}

M.recipe_process_color_share = 0.18

return M
