data:extend({
  {
    type = "recipe",
    name = "fw-arc-cermet-densification",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-cermet.png",
    icon_size = 1024,
    category = "smelting",
    enabled = false,
    energy_required = 6.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-metal-mesh", amount = 2 },
      { type = "item", name = "titanium-plate", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "stone-brick", amount = 2 },
    },
    results = { { type = "item", name = "fw-cermet", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-arc-glass-recast",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-glass.png",
    icon_size = 1024,
    category = "smelting",
    enabled = false,
    energy_required = 4.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-sand", amount = 6 },
      { type = "item", name = "lead-plate", amount = 1 },
      { type = "item", name = "silicon", amount = 1 },
    },
    results = { { type = "item", name = "fw-glass", amount = 4 } },
  },
  {
    type = "recipe",
    name = "fw-synthesized-gunpowder",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-gunpowder.png",
    icon_size = 128,
    category = "crafting",
    enabled = false,
    energy_required = 3.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-carbon", amount = 2 },
      { type = "item", name = "sulfur", amount = 1 },
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "item", name = "fw-sand", amount = 1 },
    },
    results = { { type = "item", name = "fw-gunpowder", amount = 3 } },
  },
  {
    type = "recipe",
    name = "fw-synthesized-filter-core",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-inline-filter.png",
    icon_size = 1024,
    category = "crafting",
    enabled = false,
    energy_required = 3.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "item", name = "fw-silicon-wafer", amount = 2 },
      { type = "item", name = "fw-glass", amount = 2 },
      { type = "item", name = "fw-ceramic-insulator", amount = 1 },
    },
    results = { { type = "item", name = "fw-inline-filter", amount = 2 } },
  },
})
