data:extend({
  {
    type = "recipe",
    name = "fw-salt-brine-clarification",
    icon = "__FluxWorksAssets__/graphics/resources/ores/salt.png",
    icon_size = 128,
    category = "fw-flux-harvesting",
    subgroup = "fw-chemistry-processes",
    order = "a[harvesting]-a[salt-brine-clarification]",
    enabled = false,
    energy_required = 4.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-salt", amount = 6 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "fluid", name = "water", amount = 60 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
    },
    results = {
      { type = "fluid", name = "fw-chlorine", amount = 60 },
      { type = "item", name = "fw-inline-filter", amount = 1, probability = 0.8 },
    },
    main_product = "fw-chlorine",
  },
  {
    type = "recipe",
    name = "fw-silica-beneficiation",
    icons = {
      { icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-silicon-ore-clean.png", icon_size = 256 },
      { icon = "__FluxWorksAssets__/graphics/icons/items/flux-2.png", icon_size = 64, scale = 0.45, shift = { 8, -8 } },
    },
    category = "fw-flux-harvesting",
    subgroup = "fw-chemistry-materials",
    order = "a[harvesting]-b[silica-beneficiation]",
    enabled = false,
    energy_required = 5.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "silicon-ore", amount = 6 },
      { type = "item", name = "sand", amount = 2 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "water", amount = 50 },
      { type = "fluid", name = "fw-yellow-flux", amount = 24 },
    },
    results = {
      { type = "item", name = "silicon", amount = 10 },
      { type = "item", name = "sand", amount = 3 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.8 },
    },
    main_product = "silicon",
  },
  {
    type = "recipe",
    name = "fw-carbonic-washing",
    icons = {
      { icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-carbon-ore.png", icon_size = 128, scale = 0.5 },
      { icon = "__FluxWorksAssets__/graphics/icons/items/crystallized-flux.png", icon_size = 64, scale = 0.45, shift = { 8, -8 } },
    },
    category = "fw-flux-harvesting",
    subgroup = "fw-chemistry-materials",
    order = "a[harvesting]-c[carbonic-washing]",
    enabled = false,
    energy_required = 5.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "coal", amount = 8 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "fluid", name = "water", amount = 60 },
      { type = "fluid", name = "fw-green-flux", amount = 18 },
    },
    results = {
      { type = "item", name = "carbon", amount = 6 },
      { type = "item", name = "sulfur", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1, probability = 0.8 },
    },
    main_product = "carbon",
  },
  {
    type = "recipe",
    name = "fw-bauxite-slurry-clarification",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bauxite-ore.png",
    icon_size = 64,
    category = "fw-flux-harvesting",
    subgroup = "fw-chemistry-materials",
    order = "a[harvesting]-d[bauxite-slurry-clarification]",
    enabled = false,
    energy_required = 5.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "bauxite-ore", amount = 8 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "item", name = "fw-salt", amount = 1 },
      { type = "fluid", name = "water", amount = 60 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
    },
    results = {
      { type = "item", name = "bauxite-ore", amount = 11 },
      { type = "item", name = "sand", amount = 2 },
      { type = "item", name = "fw-inline-filter", amount = 1, probability = 0.8 },
    },
    main_product = "bauxite-ore",
  },
  {
    type = "recipe",
    name = "fw-tin-ore-beneficiation",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-tin-ore.png",
    icon_size = 64,
    category = "fw-flux-harvesting",
    subgroup = "fw-chemistry-materials",
    order = "a[harvesting]-e[tin-ore-beneficiation]",
    enabled = false,
    energy_required = 5.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "tin-ore", amount = 8 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "item", name = "fw-salt", amount = 1 },
      { type = "fluid", name = "water", amount = 50 },
      { type = "fluid", name = "fw-yellow-flux", amount = 16 },
    },
    results = {
      { type = "item", name = "tin-ore", amount = 11 },
      { type = "item", name = "lead-ore", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1, probability = 0.8 },
    },
    main_product = "tin-ore",
  },
  {
    type = "recipe",
    name = "fw-lead-ore-beneficiation",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-lead-ore.png",
    icon_size = 64,
    category = "fw-flux-harvesting",
    subgroup = "fw-chemistry-materials",
    order = "a[harvesting]-f[lead-ore-beneficiation]",
    enabled = false,
    energy_required = 6.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "lead-ore", amount = 8 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 40 },
      { type = "fluid", name = "fw-yellow-flux", amount = 12 },
    },
    results = {
      { type = "item", name = "fw-crushed-lead-ore", amount = 11 },
      { type = "item", name = "sulfur", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1, probability = 0.78 },
    },
    main_product = "fw-crushed-lead-ore",
  },
  {
    type = "recipe",
    name = "fw-titanium-slurry-grading",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-titanium-ore.png",
    icon_size = 64,
    category = "fw-flux-harvesting",
    subgroup = "fw-chemistry-materials",
    order = "a[harvesting]-g[titanium-slurry-grading]",
    enabled = false,
    energy_required = 7.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "titanium-ore", amount = 6 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 40 },
      { type = "fluid", name = "fw-green-flux", amount = 18 },
    },
    results = {
      { type = "item", name = "fw-crushed-titanium-ore", amount = 9 },
      { type = "item", name = "sand", amount = 2 },
      { type = "item", name = "fw-inline-filter", amount = 1, probability = 0.78 },
    },
    main_product = "fw-crushed-titanium-ore",
  },
  {
    type = "recipe",
    name = "fw-carbon-grade-screening",
    icons = {
      { icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-carbon-ore.png", icon_size = 128, scale = 0.5 },
      { icon = "__base__/graphics/icons/stone-furnace.png", icon_size = 64, scale = 0.4, shift = { 8, 8 } },
    },
    category = "fw-flux-harvesting",
    subgroup = "fw-chemistry-materials",
    order = "a[harvesting]-h[carbon-grade-screening]",
    enabled = false,
    energy_required = 6.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "carbon", amount = 6 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "fluid", name = "water", amount = 50 },
      { type = "fluid", name = "fw-green-flux", amount = 14 },
    },
    results = {
      { type = "item", name = "fw-carbon", amount = 5 },
      { type = "item", name = "sulfur", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1, probability = 0.85 },
    },
    main_product = "fw-carbon",
  },
  {
    type = "recipe",
    name = "fw-arc-cermet-densification",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-cermet.png",
    icon_size = 256,
    category = "fw-arc-smelting",
    subgroup = "fw-flux-systems",
    order = "b[foundry]-a[arc-cermet-densification]",
    enabled = false,
    energy_required = 6.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-metal-mesh", amount = 2 },
      { type = "item", name = "titanium-plate", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "stone-brick", amount = 2 },
      { type = "item", name = "fw-carbon", amount = 1 },
      { type = "item", name = "fw-alumina-refractory", amount = 1 },
    },
    results = { { type = "item", name = "fw-cermet", amount = 4 } },
  },
  {
    type = "recipe",
    name = "fw-arc-glass-recast",
    icon = "__FluxWorksAssets__/graphics/icons/items/glass-panes/fw-glass-pane-1.png",
    icon_size = 256,
    category = "fw-arc-smelting",
    subgroup = "fw-flux-systems",
    order = "b[foundry]-b[arc-glass-recast]",
    enabled = false,
    energy_required = 4.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "sand", amount = 6 },
      { type = "item", name = "lead-plate", amount = 1 },
      { type = "item", name = "silicon", amount = 1 },
      { type = "fluid", name = "fw-chlorine", amount = 20 },
    },
    results = { { type = "item", name = "glass", amount = 5 } },
  },
  {
    type = "recipe",
    name = "fw-arc-insulator-vitrification",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-ceramic-insulator.png",
    icon_size = 128,
    category = "fw-arc-smelting",
    subgroup = "fw-flux-systems",
    order = "b[foundry]-c[arc-insulator-vitrification]",
    enabled = false,
    energy_required = 6.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-fired-ceramic", amount = 2 },
      { type = "item", name = "glass", amount = 2 },
      { type = "item", name = "lead-plate", amount = 1 },
      { type = "fluid", name = "fw-red-flux", amount = 28 },
      { type = "fluid", name = "fw-yellow-flux", amount = 12 },
    },
    results = {
      { type = "item", name = "fw-ceramic-insulator", amount = 4 },
    },
  },
  {
    type = "recipe",
    name = "fw-synthesized-gunpowder",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-gunpowder.png",
    icon_size = 128,
    category = "crafting",
    subgroup = "fw-chemistry-materials",
    order = "c[synthesis]-a[synthesized-gunpowder]",
    enabled = false,
    energy_required = 3.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-carbon", amount = 2 },
      { type = "item", name = "sulfur", amount = 1 },
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "item", name = "sand", amount = 1 },
      { type = "item", name = "fw-resin", amount = 1 },
    },
    results = { { type = "item", name = "fw-gunpowder", amount = 8 } },
  },
  {
    type = "recipe",
    name = "fw-spectral-coolant-blend",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-thermal-buffer.png",
    icon_size = 256,
    category = "fw-flux-synthesis",
    subgroup = "fw-chemistry-processes",
    order = "c[synthesis]-c[spectral-coolant-blend]",
    enabled = false,
    energy_required = 7.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "ice", amount = 6 },
      { type = "item", name = "lithium-plate", amount = 1 },
      { type = "item", name = "fw-cryo-coil", amount = 1 },
      { type = "item", name = "fw-aquilo-cryogel", amount = 1 },
      { type = "fluid", name = "fluoroketone-hot", amount = 40, temperature = 180 },
      { type = "fluid", name = "fw-purple-flux", amount = 10 },
      { type = "fluid", name = "fw-yellow-flux", amount = 16 },
      { type = "fluid", name = "fw-red-flux", amount = 18 },
      { type = "fluid", name = "fw-green-flux", amount = 10 },
    },
    results = {
      { type = "fluid", name = "fluoroketone-cold", amount = 60, temperature = -150 },
    },
    main_product = "fluoroketone-cold",
  },
})
