data:extend({
  {
    type = "recipe",
    name = "lead-plate",
    icon = "__FluxWorksAssets__/graphics/icons/items/metal-plate-lead.png",
    icon_size = 1024,
    category = "smelting",
    enabled = true,
    energy_required = 3.2,
    allow_productivity = true,
    ingredients = { { type = "item", name = "lead-ore", amount = 1 } },
    results = { { type = "item", name = "lead-plate", amount = 1 } },
  },
  {
    type = "recipe",
    name = "lead-plate-from-crushed",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-lead-ore.png",
    icon_size = 128,
    category = "smelting",
    enabled = false,
    energy_required = 3.2,
    allow_productivity = true,
    ingredients = { { type = "item", name = "fw-crushed-lead-ore", amount = 3 } },
    results = { { type = "item", name = "lead-plate", amount = 2 } },
  },
  {
    type = "recipe",
    name = "titanium-plate",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-titanium-plate.png",
    icon_size = 128,
    category = "smelting",
    enabled = true,
    energy_required = 6.4,
    allow_productivity = true,
    ingredients = { { type = "item", name = "titanium-ore", amount = 2 } },
    results = { { type = "item", name = "titanium-plate", amount = 1 } },
  },
  {
    type = "recipe",
    name = "titanium-plate-from-crushed",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-crushed-titanium-ore.png",
    icon_size = 128,
    category = "smelting",
    enabled = false,
    energy_required = 6.4,
    allow_productivity = true,
    ingredients = { { type = "item", name = "fw-crushed-titanium-ore", amount = 3 } },
    results = { { type = "item", name = "titanium-plate", amount = 2 } },
  },
  {
    type = "recipe",
    name = "aluminum-plate",
    icon = "__FluxWorksAssets__/graphics/icons/items/aluminum-plate.png",
    icon_size = 128,
    category = "smelting",
    enabled = true,
    energy_required = 4.0,
    allow_productivity = true,
    ingredients = { { type = "item", name = "bauxite-ore", amount = 2 } },
    results = { { type = "item", name = "aluminum-plate", amount = 1 } },
  },
  {
    type = "recipe",
    name = "tin-plate",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-tin-plate.png",
    icon_size = 128,
    category = "smelting",
    enabled = true,
    energy_required = 3.2,
    allow_productivity = true,
    ingredients = { { type = "item", name = "tin-ore", amount = 2 } },
    results = { { type = "item", name = "tin-plate", amount = 1 } },
  },
  {
    type = "recipe",
    name = "silicon",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-silicon.png",
    icon_size = 64,
    category = "smelting",
    enabled = false,
    energy_required = 3.6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "silicon-ore", amount = 2 },
      { type = "item", name = "fw-carbon", amount = 1 },
    },
    results = { { type = "item", name = "silicon", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-carbon-refining",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-carbon-ore.png",
    icon_size = 128,
    category = "smelting",
    enabled = false,
    energy_required = 2.8,
    allow_productivity = true,
    ingredients = { { type = "item", name = "carbon", amount = 2 } },
    results = { { type = "item", name = "fw-carbon", amount = 1 } },
  },
})
