local function recipe_icon(item_name)
  local item = data.raw.item and data.raw.item[item_name]
  if not item then
    error("Missing item prototype for recipe icon: " .. item_name)
  end
  return {
    icon = item.icon,
    icon_size = item.icon_size,
    icons = item.icons,
  }
end

data:extend({
  {
    type = "recipe",
    name = "fw-fired-ceramic",
    icon = recipe_icon("fw-fired-ceramic").icon,
    icon_size = recipe_icon("fw-fired-ceramic").icon_size,
    category = "fw-arc-smelting",
    enabled = false,
    energy_required = 2.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "stone-brick", amount = 2 },
      { type = "item", name = "fw-sand", amount = 3 },
    },
    results = { { type = "item", name = "fw-fired-ceramic", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-ceramic-casing",
    icon = recipe_icon("fw-ceramic-casing").icon,
    icon_size = recipe_icon("fw-ceramic-casing").icon_size,
    category = "fw-flux-synthesis",
    enabled = false,
    energy_required = 2.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-fired-ceramic", amount = 2 },
      { type = "item", name = "fw-steel-beam", amount = 1 },
      { type = "item", name = "titanium-plate", amount = 1 },
      { type = "item", name = "fw-rubber-sheet", amount = 1 },
      { type = "item", name = "fw-metal-mesh", amount = 1 },
    },
    results = { { type = "item", name = "fw-ceramic-casing", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-coil-block",
    icon = recipe_icon("fw-coil-block").icon,
    icon_size = recipe_icon("fw-coil-block").icon_size,
    category = "fw-flux-synthesis",
    enabled = false,
    energy_required = 2.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-inductor-coil", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 1 },
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "item", name = "fw-ceramic-insulator", amount = 1 },
      { type = "item", name = "fw-tinned-cable", amount = 2 },
    },
    results = { { type = "item", name = "fw-coil-block", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-signal-conduit",
    icon = recipe_icon("fw-signal-conduit").icon,
    icon_size = recipe_icon("fw-signal-conduit").icon_size,
    category = "fw-flux-synthesis",
    enabled = false,
    energy_required = 1.8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-cable-harness", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "fw-copper-tube", amount = 1 },
      { type = "item", name = "fw-rubber-sheet", amount = 1 },
      { type = "item", name = "fw-solder-wire", amount = 1 },
      { type = "item", name = "fw-circuit-contact", amount = 1 },
    },
    results = { { type = "item", name = "fw-signal-conduit", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-lens-array",
    icon = recipe_icon("fw-lens-array").icon,
    icon_size = recipe_icon("fw-lens-array").icon_size,
    category = "fw-flux-synthesis",
    enabled = false,
    energy_required = 2.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-glass-lens", amount = 2 },
      { type = "item", name = "fw-circuit-substrate", amount = 1 },
      { type = "item", name = "silicon", amount = 1 },
      { type = "item", name = "fw-glass", amount = 1 },
      { type = "item", name = "fw-circuit-contact", amount = 1 },
    },
    results = { { type = "item", name = "fw-lens-array", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-sensor-diode",
    icon = recipe_icon("fw-sensor-diode").icon,
    icon_size = recipe_icon("fw-sensor-diode").icon_size,
    category = "fw-flux-synthesis",
    enabled = false,
    energy_required = 2.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-lens-array", amount = 1 },
      { type = "item", name = "fw-silicon-wafer", amount = 1 },
      { type = "item", name = "tin-plate", amount = 1 },
      { type = "item", name = "fw-solder-wire", amount = 1 },
      { type = "item", name = "fw-circuit-contact", amount = 2 },
    },
    results = { { type = "item", name = "fw-sensor-diode", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-pressure-housing",
    icon = recipe_icon("fw-pressure-housing").icon,
    icon_size = recipe_icon("fw-pressure-housing").icon_size,
    category = "fw-flux-synthesis",
    enabled = false,
    energy_required = 2.6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-cermet", amount = 2 },
      { type = "item", name = "fw-steel-beam", amount = 1 },
      { type = "item", name = "lead-plate", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "item", name = "titanium-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-pressure-housing", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-flow-regulator",
    icon = recipe_icon("fw-flow-regulator").icon,
    icon_size = recipe_icon("fw-flow-regulator").icon_size,
    category = "fw-flux-synthesis",
    enabled = false,
    energy_required = 2.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-pressure-housing", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "fw-bearing", amount = 2 },
      { type = "item", name = "fw-capacitor", amount = 1 },
      { type = "item", name = "fw-copper-tube", amount = 1 },
      { type = "item", name = "fw-signal-conduit", amount = 1 },
    },
    results = { { type = "item", name = "fw-flow-regulator", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-power-regulator",
    icon = recipe_icon("fw-power-regulator").icon,
    icon_size = recipe_icon("fw-power-regulator").icon_size,
    category = "fw-flux-synthesis",
    enabled = false,
    energy_required = 3.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 2 },
      { type = "item", name = "silicon", amount = 1 },
      { type = "item", name = "fw-solder-wire", amount = 2 },
      { type = "item", name = "fw-ceramic-insulator", amount = 1 },
      { type = "item", name = "fw-circuit-contact", amount = 1 },
    },
    results = { { type = "item", name = "fw-power-regulator", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-field-winding",
    icon = recipe_icon("fw-field-winding").icon,
    icon_size = recipe_icon("fw-field-winding").icon_size,
    category = "crafting",
    enabled = false,
    energy_required = 3.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-coil-block", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "fw-conductor-bundle", amount = 1 },
      { type = "item", name = "fw-tinned-cable", amount = 2 },
    },
    results = { { type = "item", name = "fw-field-winding", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-foundry-lining",
    icon = recipe_icon("fw-foundry-lining").icon,
    icon_size = recipe_icon("fw-foundry-lining").icon_size,
    category = "fw-arc-smelting",
    enabled = false,
    energy_required = 4.5,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-cermet", amount = 2 },
      { type = "item", name = "fw-ceramic-casing", amount = 1 },
      { type = "item", name = "titanium-plate", amount = 2 },
      { type = "item", name = "fw-carbon", amount = 1 },
    },
    results = { { type = "item", name = "fw-foundry-lining", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-smelter-array",
    icon = recipe_icon("fw-smelter-array").icon,
    icon_size = recipe_icon("fw-smelter-array").icon_size,
    category = "fw-flux-synthesis",
    enabled = false,
    energy_required = 4.8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-foundry-lining", amount = 2 },
      { type = "item", name = "fw-annealed-cermet", amount = 2 },
      { type = "item", name = "fw-power-regulator", amount = 1 },
      { type = "item", name = "fw-pressure-housing", amount = 1 },
      { type = "item", name = "fw-light-frame", amount = 1 },
    },
    results = { { type = "item", name = "fw-smelter-array", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-nutrient-bed",
    icon = recipe_icon("fw-nutrient-bed").icon,
    icon_size = recipe_icon("fw-nutrient-bed").icon_size,
    category = "fw-flux-synthesis",
    enabled = false,
    energy_required = 3.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "item", name = "fw-resin", amount = 1 },
      { type = "item", name = "fw-glass", amount = 2 },
      { type = "fluid", name = "fw-latex", amount = 20 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "fw-nutrient-bed", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-spore-filter",
    icon = recipe_icon("fw-spore-filter").icon,
    icon_size = recipe_icon("fw-spore-filter").icon_size,
    category = "crafting",
    enabled = false,
    energy_required = 2.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-nutrient-bed", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "item", name = "fw-rubber-sheet", amount = 1 },
      { type = "item", name = "fw-metal-mesh", amount = 1 },
      { type = "item", name = "fw-resin", amount = 1 },
    },
    results = { { type = "item", name = "fw-spore-filter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-cryo-coil",
    icon = recipe_icon("fw-cryo-coil").icon,
    icon_size = recipe_icon("fw-cryo-coil").icon_size,
    category = "crafting",
    enabled = false,
    energy_required = 3.4,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-field-winding", amount = 1 },
      { type = "item", name = "fw-ceramic-insulator", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 1 },
      { type = "item", name = "aluminum-plate", amount = 1 },
      { type = "item", name = "titanium-plate", amount = 1 },
    },
    results = { { type = "item", name = "fw-cryo-coil", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-thermal-buffer",
    icon = recipe_icon("fw-thermal-buffer").icon,
    icon_size = recipe_icon("fw-thermal-buffer").icon_size,
    category = "crafting",
    enabled = false,
    energy_required = 4.2,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-cryo-coil", amount = 1 },
      { type = "item", name = "fw-cermet", amount = 2 },
      { type = "item", name = "fw-composite-panel", amount = 1 },
      { type = "item", name = "fw-copper-tube", amount = 2 },
      { type = "item", name = "fw-flow-regulator", amount = 1 },
    },
    results = { { type = "item", name = "fw-thermal-buffer", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-em-core",
    icon = recipe_icon("fw-em-core").icon,
    icon_size = recipe_icon("fw-em-core").icon_size,
    category = "crafting",
    enabled = false,
    energy_required = 4.6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-power-regulator", amount = 1 },
      { type = "item", name = "titanium-plate", amount = 1 },
      { type = "item", name = "fw-sensor-diode", amount = 2 },
      { type = "item", name = "fw-memory-die", amount = 1 },
      { type = "item", name = "fw-conductor-bundle", amount = 1 },
    },
    results = { { type = "item", name = "fw-em-core", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-logic-matrix",
    icon = recipe_icon("fw-logic-matrix").icon,
    icon_size = recipe_icon("fw-logic-matrix").icon_size,
    category = "crafting",
    enabled = false,
    energy_required = 5.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-em-core", amount = 1 },
      { type = "item", name = "fw-microchip", amount = 2 },
      { type = "item", name = "fw-circuit-substrate", amount = 1 },
      { type = "item", name = "silicon", amount = 1 },
      { type = "item", name = "fw-sensor-package", amount = 1 },
      { type = "item", name = "fw-conductor-bundle", amount = 1 },
    },
    results = { { type = "item", name = "fw-logic-matrix", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-promethium-primer",
    icons = recipe_icon("fw-promethium-primer").icons,
    category = "fw-flux-condensing",
    enabled = false,
    energy_required = 8.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-promethium-shard", amount = 6 },
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 1 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 1 },
      { type = "item", name = "fw-aquilo-cryogel", amount = 1 },
      { type = "item", name = "fw-gleba-spore-resin", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 32 },
      { type = "fluid", name = "fw-yellow-flux", amount = 26 },
      { type = "fluid", name = "fw-red-flux", amount = 42 },
      { type = "fluid", name = "fw-green-flux", amount = 20 },
    },
    results = {
      { type = "item", name = "fw-promethium-primer", amount = 1 },
      { type = "item", name = "fw-flux-catalyst", amount = 1, probability = 0.45 },
    },
  },
  {
    type = "recipe",
    name = "fw-promethium-matrix",
    icon = recipe_icon("fw-promethium-matrix").icon,
    icon_size = recipe_icon("fw-promethium-matrix").icon_size,
    category = "fw-flux-condensing",
    enabled = false,
    energy_required = 11.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "promethium-asteroid-chunk", amount = 1 },
      { type = "item", name = "fw-promethium-primer", amount = 1 },
      { type = "item", name = "fw-em-core", amount = 1 },
      { type = "item", name = "fw-flux-resonance-cell", amount = 1 },
      { type = "item", name = "fw-condensed-flux-matrix", amount = 1 },
      { type = "item", name = "fw-logic-matrix", amount = 1 },
      { type = "item", name = "fw-fulgora-static-mesh", amount = 1 },
      { type = "item", name = "fw-vulcanus-slag-cermet", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 64 },
      { type = "fluid", name = "fw-yellow-flux", amount = 52 },
      { type = "fluid", name = "fw-red-flux", amount = 76 },
      { type = "fluid", name = "fw-green-flux", amount = 30 },
    },
    results = { { type = "item", name = "fw-promethium-matrix", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-rift-stabilizer",
    icon = recipe_icon("fw-rift-stabilizer").icon,
    icon_size = recipe_icon("fw-rift-stabilizer").icon_size,
    category = "fw-flux-condensing",
    enabled = false,
    energy_required = 14.0,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-flux-phase-manifold", amount = 1 },
      { type = "item", name = "fw-promethium-matrix", amount = 1 },
      { type = "item", name = "fw-promethium-primer", amount = 1 },
      { type = "item", name = "fw-resonance-substrate", amount = 1 },
      { type = "item", name = "fw-logic-matrix", amount = 1 },
      { type = "item", name = "fw-aquilo-cryogel", amount = 1 },
      { type = "item", name = "fw-gleba-spore-resin", amount = 1 },
      { type = "item", name = "fw-fulgora-static-mesh", amount = 1 },
      { type = "item", name = "fw-vulcanus-slag-cermet", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 110 },
      { type = "fluid", name = "fw-yellow-flux", amount = 84 },
      { type = "fluid", name = "fw-red-flux", amount = 120 },
      { type = "fluid", name = "fw-green-flux", amount = 70 },
    },
    results = { { type = "item", name = "fw-rift-stabilizer", amount = 1 } },
  },
})
