data:extend({
  {
    type = "recipe",
    name = "fw-quantum-spindle",
    enabled = false,
    energy_required = 6,
    subgroup = "fw-fabrication-components",
    order = "z[required-mod]-a[quantum-spindle]",
    ingredients = {
      { type = "item", name = "fw-memory-die", amount = 2 },
      { type = "item", name = "fw-signal-conduit", amount = 1 },
      { type = "item", name = "fw-flux-lattice", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 1 },
    },
    results = { { type = "item", name = "fw-quantum-spindle", amount = 1 } },
  },
  {
    type = "recipe",
    name = "fw-reactive-column",
    enabled = false,
    energy_required = 5,
    subgroup = "fw-fabrication-components",
    order = "z[required-mod]-b[reactive-column]",
    ingredients = {
      { type = "item", name = "fw-pressure-housing", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "item", name = "fw-flow-regulator", amount = 1 },
      { type = "item", name = "fw-steel-beam", amount = 1 },
    },
    results = { { type = "item", name = "fw-reactive-column", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-hydraulic-core",
    enabled = false,
    energy_required = 6,
    subgroup = "fw-fabrication-components",
    order = "z[required-mod]-c[hydraulic-core]",
    ingredients = {
      { type = "item", name = "fw-pressure-housing", amount = 1 },
      { type = "item", name = "fw-flow-regulator", amount = 1 },
      { type = "item", name = "fw-reinforced-seal", amount = 1 },
      { type = "item", name = "fw-power-regulator", amount = 1 },
    },
    results = { { type = "item", name = "fw-hydraulic-core", amount = 2 } },
  },
  {
    type = "recipe",
    name = "fw-reactor-instrument-cluster",
    enabled = false,
    energy_required = 8,
    subgroup = "fw-fabrication-components",
    order = "z[required-mod]-d[reactor-instrument-cluster]",
    ingredients = {
      { type = "item", name = "fw-logic-matrix", amount = 1 },
      { type = "item", name = "fw-shielded-fuel-casing", amount = 1 },
      { type = "item", name = "fw-transformer-core", amount = 1 },
      { type = "item", name = "fw-capacitor", amount = 1 },
    },
    results = { { type = "item", name = "fw-reactor-instrument-cluster", amount = 1 } },
  },
})
