-- Pre-origin and bridgehead payoffs for the Shattered Planet campaign.

data:extend({
  {
    type = "recipe", name = "fw-shattered-red-bridgehead-forging", enabled = false,
    category = "metallurgy", subgroup = "fw-flux-red", order = "d[shattered]-a[red-bridgehead]",
    energy_required = 16, allow_productivity = false,
    ingredients = {
      { type = "item", name = "tungsten-plate", amount = 2 },
      { type = "item", name = "fw-cermet", amount = 2 },
      { type = "item", name = "calcite", amount = 2 },
      { type = "fluid", name = "molten-iron", amount = 50 },
      { type = "fluid", name = "fw-red-flux", amount = 80 },
    },
    results = { { type = "item", name = "fw-vulcanus-slag-cermet", amount = 3 } },
    main_product = "fw-vulcanus-slag-cermet",
  },
  {
    type = "recipe", name = "fw-shattered-green-bridgehead-cultivation", enabled = false,
    category = "organic", subgroup = "fw-flux-green", order = "d[shattered]-b[green-bridgehead]",
    energy_required = 16, allow_productivity = false,
    ingredients = {
      { type = "item", name = "bioflux", amount = 2 },
      { type = "item", name = "jelly", amount = 4 },
      { type = "item", name = "fw-resin", amount = 2 },
      { type = "item", name = "carbon-fiber", amount = 2 },
      { type = "fluid", name = "fw-green-flux", amount = 80 },
    },
    results = { { type = "item", name = "fw-gleba-spore-resin", amount = 3 } },
    main_product = "fw-gleba-spore-resin",
  },
  {
    type = "recipe", name = "fw-shattered-yellow-bridgehead-reclamation", enabled = false,
    category = "electromagnetics", subgroup = "fw-flux-yellow", order = "d[shattered]-c[yellow-bridgehead]",
    energy_required = 16, allow_productivity = false,
    ingredients = {
      { type = "item", name = "superconductor", amount = 2 },
      { type = "item", name = "fw-metal-mesh", amount = 2 },
      { type = "item", name = "holmium-plate", amount = 1 },
      { type = "fluid", name = "holmium-solution", amount = 40 },
      { type = "fluid", name = "fw-yellow-flux", amount = 80 },
    },
    results = { { type = "item", name = "fw-fulgora-static-mesh", amount = 3 } },
    main_product = "fw-fulgora-static-mesh",
  },
  {
    type = "recipe", name = "fw-shattered-purple-bridgehead-annealing", enabled = false,
    category = "cryogenics", subgroup = "fw-flux-purple", order = "d[shattered]-d[purple-bridgehead]",
    energy_required = 16, allow_productivity = false,
    ingredients = {
      { type = "item", name = "lithium-plate", amount = 2 },
      { type = "item", name = "ice", amount = 8 },
      { type = "item", name = "fw-cryo-coil", amount = 1 },
      { type = "fluid", name = "fluoroketone-cold", amount = 20 },
      { type = "fluid", name = "fw-purple-flux", amount = 80 },
    },
    results = { { type = "item", name = "fw-aquilo-cryogel", amount = 3 } },
    main_product = "fw-aquilo-cryogel",
  },
  {
    type = "recipe", name = "fw-shattered-vent-spectrum-condensation", enabled = false,
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-condensed-flux-matrix.png", icon_size = 64,
    category = "fw-flux-synthesis", subgroup = "fw-flux-systems", order = "g[shattered]-a[vent-condensation]",
    energy_required = 20, allow_productivity = true,
    ingredients = {
      { type = "item", name = "fw-stabilized-flux-crystal", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 120 },
      { type = "fluid", name = "fw-yellow-flux", amount = 120 },
      { type = "fluid", name = "fw-red-flux", amount = 120 },
      { type = "fluid", name = "fw-green-flux", amount = 120 },
    },
    results = { { type = "item", name = "fw-condensed-flux-matrix", amount = 5 } },
    main_product = "fw-condensed-flux-matrix",
  },
  {
    type = "recipe", name = "fw-shattered-rift-coupler-array", enabled = false,
    icon = "__FluxWorksAssets__/graphics/icons/items/late-utility/fw-rift-coupler.png", icon_size = 1024,
    category = "fw-flux-synthesis", subgroup = "fw-flux-exchange", order = "c[shattered]-a[coupler-array]",
    energy_required = 30, allow_productivity = false,
    ingredients = {
      { type = "item", name = "fw-model-lattice", amount = 1 },
      { type = "item", name = "fw-quantum-computer", amount = 1 },
      { type = "item", name = "fw-phase-anchor", amount = 2 },
      { type = "item", name = "fw-entanglement-core", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 100 },
      { type = "fluid", name = "fw-yellow-flux", amount = 100 },
    },
    results = { { type = "item", name = "fw-rift-coupler", amount = 2 } },
    main_product = "fw-rift-coupler",
  },
  {
    type = "recipe", name = "fw-shattered-origin-survey-lattice", enabled = false,
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-model-lattice.png", icon_size = 64,
    category = "fw-flux-synthesis", subgroup = "fw-flux-origin-projects", order = "a[survey]-a[model-lattice]",
    energy_required = 45, allow_productivity = false,
    ingredients = {
      { type = "item", name = "fw-quantum-computer", amount = 2 },
      { type = "item", name = "fw-flux-lattice", amount = 4 },
      { type = "item", name = "fw-rift-stabilizer", amount = 2 },
      { type = "item", name = "fw-promethium-matrix", amount = 4 },
      { type = "fluid", name = "fw-purple-flux", amount = 250 },
      { type = "fluid", name = "fw-green-flux", amount = 150 },
    },
    results = { { type = "item", name = "fw-model-lattice", amount = 1 } },
    main_product = "fw-model-lattice",
  },
  {
    type = "recipe", name = "fw-ion-storm-harmonic-core", enabled = false,
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-model-lattice.png", icon_size = 64,
    category = "fw-origin-forging", subgroup = "fw-flux-origin-projects", order = "b[storm-capture]-a[harmonic-core]",
    energy_required = 120, allow_productivity = false,
    ingredients = {
      { type = "item", name = "fw-origin-crucible-lining", amount = 2 },
      { type = "item", name = "fw-storm-spine-segment", amount = 2 },
      { type = "item", name = "fw-model-lattice", amount = 2 },
      { type = "item", name = "fw-promethium-matrix", amount = 8 },
      { type = "item", name = "fw-rift-stabilizer", amount = 2 },
      { type = "fluid", name = "fw-purple-flux", amount = 500 },
      { type = "fluid", name = "fw-yellow-flux", amount = 500 },
      { type = "fluid", name = "fw-red-flux", amount = 500 },
      { type = "fluid", name = "fw-green-flux", amount = 500 },
    },
    results = { { type = "item", name = "fw-harmonic-lattice-core", amount = 1 } },
    main_product = "fw-harmonic-lattice-core",
  },
})
