-- Planetary payoff recipes for the technologies in space-age-symbiosis.lua.
-- Each branch combines a native Space Age process with one established Flux discipline.

data:extend({
  {
    type = "recipe",
    name = "fw-orbital-flux-chunk-sorting",
    icon = "__space-age__/graphics/icons/metallic-asteroid-chunk.png",
    enabled = false,
    category = "crushing",
    subgroup = "space-crushing",
    order = "z[fluxworks]-a[orbital-sorting]",
    energy_required = 4,
    allow_productivity = false,
    ingredients = {
      { type = "item", name = "metallic-asteroid-chunk", amount = 1 },
      { type = "fluid", name = "fw-yellow-flux", amount = 8 },
    },
    results = {
      { type = "item", name = "iron-ore", amount = 12 },
      { type = "item", name = "copper-ore", amount = 5 },
      { type = "item", name = "metallic-asteroid-chunk", amount = 1, probability = 0.12 },
    },
  },
  {
    type = "recipe",
    name = "fw-vulcanus-red-carbide-sintering",
    enabled = false,
    category = "metallurgy",
    subgroup = "fw-flux-red",
    order = "c[planetary]-a[vulcanus-carbide]",
    energy_required = 6,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "tungsten-ore", amount = 3 },
      { type = "item", name = "carbon", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
      { type = "fluid", name = "fw-red-flux", amount = 14 },
    },
    results = { { type = "item", name = "tungsten-carbide", amount = 2 } },
    main_product = "tungsten-carbide",
  },
  {
    type = "recipe",
    name = "fw-vulcanus-flux-casting",
    enabled = false,
    category = "metallurgy",
    subgroup = "fw-flux-red",
    order = "c[planetary]-b[vulcanus-casting]",
    energy_required = 12,
    allow_productivity = true,
    ingredients = {
      { type = "fluid", name = "molten-iron", amount = 70 },
      { type = "fluid", name = "molten-copper", amount = 210 },
      { type = "item", name = "plastic-bar", amount = 4 },
      { type = "item", name = "fw-cermet", amount = 1 },
      { type = "fluid", name = "fw-red-flux", amount = 24 },
    },
    results = { { type = "item", name = "low-density-structure", amount = 2 } },
    main_product = "low-density-structure",
  },
  {
    type = "recipe",
    name = "fw-gleba-green-carbon-fiber-cultivation",
    enabled = false,
    category = "organic",
    subgroup = "fw-flux-green",
    order = "c[planetary]-a[gleba-carbon-fiber]",
    energy_required = 8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "yumako-mash", amount = 8 },
      { type = "item", name = "carbon", amount = 1 },
      { type = "item", name = "fw-inline-filter", amount = 1 },
      { type = "fluid", name = "fw-green-flux", amount = 14 },
    },
    results = { { type = "item", name = "carbon-fiber", amount = 2 } },
    main_product = "carbon-fiber",
  },
  {
    type = "recipe",
    name = "fw-fulgora-yellow-holmium-reclamation",
    enabled = false,
    category = "electromagnetics",
    subgroup = "fw-flux-yellow",
    order = "c[planetary]-a[fulgora-holmium]",
    energy_required = 8,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "scrap", amount = 20 },
      { type = "fluid", name = "sulfuric-acid", amount = 20 },
      { type = "fluid", name = "fw-yellow-flux", amount = 18 },
    },
    results = {
      { type = "fluid", name = "holmium-solution", amount = 50 },
      { type = "item", name = "stone", amount = 4 },
    },
    main_product = "holmium-solution",
  },
  {
    type = "recipe",
    name = "fw-aquilo-red-ammonia-cracking",
    enabled = false,
    category = "cryogenics",
    subgroup = "fw-flux-red",
    order = "c[planetary]-c[aquilo-ammonia]",
    energy_required = 10,
    allow_productivity = true,
    ingredients = {
      { type = "fluid", name = "ammonia", amount = 50 },
      { type = "fluid", name = "fw-red-flux", amount = 14 },
      { type = "fluid", name = "fw-yellow-flux", amount = 8 },
    },
    results = { { type = "item", name = "solid-fuel", amount = 4 } },
    main_product = "solid-fuel",
  },
  {
    type = "recipe",
    name = "fw-converged-quantum-processor",
    enabled = false,
    category = "electromagnetics",
    subgroup = "fw-flux-systems",
    order = "f[planetary-convergence]-a[quantum-processor]",
    energy_required = 20,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "processing-unit", amount = 1 },
      { type = "item", name = "superconductor", amount = 1 },
      { type = "item", name = "lithium-plate", amount = 1 },
      { type = "item", name = "fw-aquilo-cryogel", amount = 1 },
      { type = "item", name = "fw-gleba-spore-resin", amount = 1 },
      { type = "item", name = "fw-fulgora-static-mesh", amount = 1 },
      { type = "item", name = "fw-vulcanus-slag-cermet", amount = 1 },
      { type = "fluid", name = "fw-purple-flux", amount = 30 },
      { type = "fluid", name = "fw-yellow-flux", amount = 30 },
      { type = "fluid", name = "fw-red-flux", amount = 30 },
      { type = "fluid", name = "fw-green-flux", amount = 30 },
    },
    results = { { type = "item", name = "quantum-processor", amount = 2 } },
    main_product = "quantum-processor",
  },
})
