local icon_path = "__FluxWorksAssets__/graphics/icons/items/"
data:extend({
  {
    type = "item",
    name = "fw-atomic-enricher",
    icon = "__finely-crafted-graphics__/graphics/atom-forge/atom-forge-icon.png",
    icon_size = 64,
    subgroup = "fw-fabrication-machines",
    order = "d[fw-atomic-enricher]",
    place_result = "fw-atomic-enricher",
    stack_size = 20,
  },
  {
    type = "item",
    name = "fw-shielded-fuel-casing",
    icon = icon_path .. "fw-shielded-fuel-casing.png",
    icon_size = 64,
    subgroup = "fw-intermediate-structural",
    order = "r[fw-shielded-fuel-casing]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-isotope-matrix",
    icon = icon_path .. "fw-isotope-matrix.png",
    icon_size = 64,
    subgroup = "fw-intermediate-electrical",
    order = "s[fw-isotope-matrix]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-fuel-pellet-bundle",
    icon = icon_path .. "fw-fuel-pellet-bundle.png",
    icon_size = 256,
    subgroup = "fw-intermediate-structural",
    order = "t[fw-fuel-pellet-bundle]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-moderator-lattice",
    icon = icon_path .. "fw-moderator-lattice.png",
    icon_size = 64,
    subgroup = "fw-intermediate-electrical",
    order = "u[fw-moderator-lattice]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-control-rod-assembly",
    icon = icon_path .. "fw-control-rod-assembly.png",
    icon_size = 256,
    subgroup = "fw-intermediate-electrical",
    order = "v[fw-control-rod-assembly]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-reactor-coolant-cartridge",
    icon = icon_path .. "fw-reactor-coolant-cartridge.png",
    icon_size = 64,
    subgroup = "fw-intermediate-electrical",
    order = "w[fw-reactor-coolant-cartridge]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-reactor-dopant",
    icon = icon_path .. "fw-reactor-dopant.png",
    icon_size = 256,
    subgroup = "fw-intermediate-electrical",
    order = "x[fw-reactor-dopant]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-radioactive-scrap",
    icon = icon_path .. "fw-radioactive-scrap.png",
    icon_size = 256,
    subgroup = "fw-intermediate-structural",
    order = "y[fw-radioactive-scrap]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-recovered-actinides",
    icon = icon_path .. "fw-recovered-actinides.png",
    icon_size = 64,
    subgroup = "fw-intermediate-electrical",
    order = "z[fw-recovered-actinides]",
    stack_size = 100,
  },
})
