local icon_path = "__FluxWorksAssets__/graphics/icons/items/"

local function layered_item_icons(base_icon, base_size, overlay_icon, overlay_size, overlay_scale, overlay_shift)
  return {
    { icon = base_icon, icon_size = base_size },
    {
      icon = overlay_icon,
      icon_size = overlay_size,
      scale = overlay_scale,
      shift = overlay_shift,
    },
  }
end

data:extend({
  { type = "item-subgroup", name = "fw-intermediate-structural", group = "intermediate-products", order = "fa" },
  { type = "item-subgroup", name = "fw-intermediate-electrical", group = "intermediate-products", order = "fb" },
  { type = "item-subgroup", name = "fw-intermediate-precision", group = "intermediate-products", order = "fc" },
  { type = "item-subgroup", name = "fw-intermediate-ballistic", group = "intermediate-products", order = "fd" },
  { type = "item-subgroup", name = "fw-intermediate-aerospace", group = "intermediate-products", order = "fe" },
})

data:extend({
  {
    type = "item",
    name = "fw-crushed-lead-ore",
    icon = icon_path .. "fw-crushed-lead-ore.png",
    icon_size = 128,
    subgroup = "raw-material",
    order = "f[fw-crushed-lead-ore]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-crushed-titanium-ore",
    icon = icon_path .. "fw-crushed-titanium-ore.png",
    icon_size = 128,
    subgroup = "raw-material",
    order = "f[fw-crushed-titanium-ore]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-crushed-iron-ore",
    icon = icon_path .. "fw-crushed-iron-ore.png",
    icon_size = 128,
    subgroup = "raw-material",
    order = "f[fw-crushed-iron-ore]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-crushed-copper-ore",
    icon = icon_path .. "fw-crushed-copper-ore.png",
    icon_size = 128,
    subgroup = "raw-material",
    order = "f[fw-crushed-copper-ore]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-sand",
    icon = icon_path .. "fw-sand.png",
    icon_size = 1024,
    subgroup = "raw-material",
    order = "f[fw-sand]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-glass",
    icon = icon_path .. "fw-glass.png",
    icon_size = 1024,
    pictures = {
      { filename = icon_path .. "glass-panes/fw-glass-pane-1.png", size = 1024 },
      { filename = icon_path .. "glass-panes/fw-glass-pane-2.png", size = 1024 },
      { filename = icon_path .. "glass-panes/fw-glass-pane-3.png", size = 1024 },
      { filename = icon_path .. "glass-panes/fw-glass-pane-4.png", size = 1024 },
      { filename = icon_path .. "glass-panes/fw-glass-pane-5.png", size = 1024 },
      { filename = icon_path .. "glass-panes/fw-glass-pane-6.png", size = 1024 },
      { filename = icon_path .. "glass-panes/fw-glass-pane-7.png", size = 1024 },
      { filename = icon_path .. "glass-panes/fw-glass-pane-8.png", size = 1024 },
      { filename = icon_path .. "glass-panes/fw-glass-pane-9.png", size = 1024 },
      { filename = icon_path .. "glass-panes/fw-glass-pane-10.png", size = 1024 },
    },
    subgroup = "fw-intermediate-structural",
    order = "a[fw-glass]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-iron-beam",
    icon = icon_path .. "fw-iron-beam.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-structural",
    order = "c[fw-iron-beam]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-steel-beam",
    icon = icon_path .. "fw-steel-beam.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-structural",
    order = "d[fw-steel-beam]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-aluminum-beam",
    icon = icon_path .. "fw-aluminum-beam.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-structural",
    order = "e[fw-aluminum-beam]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-cable-harness",
    icon = icon_path .. "fw-cable-harness.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-electrical",
    order = "a[fw-cable-harness]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-copper-tube",
    icon = icon_path .. "fw-copper-tube.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-structural",
    order = "b[fw-copper-tube]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-inductor-coil",
    icon = icon_path .. "fw-inductor-coil.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-electrical",
    order = "c[fw-inductor-coil]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-circuit-substrate",
    icon = icon_path .. "fw-circuit-substrate.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-precision",
    order = "a[fw-circuit-substrate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-metal-mesh",
    icon = icon_path .. "fw-metal-mesh.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-structural",
    order = "f[fw-metal-mesh]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-rubber-sheet",
    icon = icon_path .. "fw-rubber-sheet.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-structural",
    order = "g[fw-rubber-sheet]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-composite-panel",
    icon = icon_path .. "fw-composite-panel.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-structural",
    order = "h[fw-composite-panel]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-glass-lens",
    icon = icon_path .. "fw-glass-lens.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-precision",
    order = "k[fw-glass-lens]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-ribbon-cable",
    icon = icon_path .. "fw-ribbon-cable.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-electrical",
    order = "b[fw-ribbon-cable]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-sensor-package",
    icon = icon_path .. "fw-sensor-package.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-precision",
    order = "i[fw-sensor-package]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-cermet",
    icon = icon_path .. "fw-cermet.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-structural",
    order = "i[fw-cermet]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-inline-filter",
    icon = icon_path .. "fw-inline-filter.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-precision",
    order = "j[fw-inline-filter]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-transformer-core",
    icon = icon_path .. "fw-transformer-core.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-electrical",
    order = "d[fw-transformer-core]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-solder-alloy",
    icon = icon_path .. "fw-solder-alloy.png",
    icon_size = 128,
    subgroup = "fw-intermediate-ballistic",
    order = "c[fw-solder-alloy]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-bearing",
    icon = icon_path .. "fw-bearing.png",
    icon_size = 128,
    subgroup = "fw-intermediate-structural",
    order = "j[fw-bearing]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-light-frame",
    icon = icon_path .. "fw-light-frame.png",
    icon_size = 128,
    subgroup = "fw-intermediate-structural",
    order = "k[fw-light-frame]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-ceramic-insulator",
    icon = icon_path .. "fw-ceramic-insulator.png",
    icon_size = 128,
    subgroup = "fw-intermediate-precision",
    order = "g[fw-ceramic-insulator]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-capacitor",
    icon = icon_path .. "fw-capacitor.png",
    icon_size = 128,
    subgroup = "fw-intermediate-precision",
    order = "h[fw-capacitor]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-gunpowder",
    icon = icon_path .. "fw-gunpowder.png",
    icon_size = 128,
    subgroup = "fw-intermediate-ballistic",
    order = "b[fw-gunpowder]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-solder-wire",
    icon = icon_path .. "fw-solder-wire.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-electrical",
    order = "e[fw-solder-wire]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-tinned-cable",
    icon = icon_path .. "fw-cable-harness.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-electrical",
    order = "ea[fw-tinned-cable]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-conductor-bundle",
    icon = icon_path .. "fw-conductor-bundle.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-electrical",
    order = "f[fw-conductor-bundle]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-chip-carrier",
    icon = icon_path .. "fw-chip-carrier.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-precision",
    order = "b[fw-chip-carrier]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-microchip",
    icon = icon_path .. "fw-microchip.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-precision",
    order = "c[fw-microchip]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-memory-die",
    icon = icon_path .. "fw-memory-die.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-precision",
    order = "d[fw-memory-die]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-ceramic-wafer",
    icon = icon_path .. "fw-ceramic-wafer.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-precision",
    order = "e[fw-ceramic-wafer]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-silicon-wafer",
    icons = layered_item_icons(
      icon_path .. "fw-ceramic-wafer.png",
      1024,
      icon_path .. "fw-bz-silicon.png",
      64,
      5.5,
      { 120, -120 }
    ),
    subgroup = "fw-intermediate-precision",
    order = "ea[fw-silicon-wafer]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-circuit-contact",
    icon = icon_path .. "fw-circuit-contact.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-precision",
    order = "f[fw-circuit-contact]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-rocket-engine",
    icon = icon_path .. "fw-rocket-engine.png",
    icon_size = 1024,
    subgroup = "fw-intermediate-aerospace",
    order = "a[fw-rocket-engine]",
    stack_size = 100,
  },
})
