data:extend({
  {
    type = "item",
    name = "fw-resin",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-resin.png",
    icon_size = 64,
    subgroup = "fw-chemistry-materials",
    order = "m[fw-resin]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-aquilo-cryogel",
    icon = "__space-age__/graphics/icons/ice.png",
    icon_size = 64,
    subgroup = "fw-chemistry-materials",
    order = "n[fw-aquilo-cryogel]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-gleba-spore-resin",
    icon = "__space-age__/graphics/icons/bioflux.png",
    icon_size = 64,
    subgroup = "fw-chemistry-materials",
    order = "o[fw-gleba-spore-resin]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-nutrient-bed",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-nutrient-bed.png",
    icon_size = 1024,
    subgroup = "fw-chemistry-materials",
    order = "oa[fw-nutrient-bed]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-fulgora-static-mesh",
    icon = "__space-age__/graphics/icons/supercapacitor.png",
    icon_size = 64,
    subgroup = "fw-chemistry-materials",
    order = "p[fw-fulgora-static-mesh]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-vulcanus-slag-cermet",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-vulcanus-slag-cermet.png",
    icon_size = 128,
    subgroup = "fw-chemistry-materials",
    order = "q[fw-vulcanus-slag-cermet]",
    stack_size = 100,
  },
})
