data:extend({
  {
    type = "item-group",
    name = "fw-science",
    icon = "__base__/graphics/icons/lab.png",
    icon_size = 64,
    order = "c-a[science]",
  },
  {
    type = "item-group",
    name = "fw-bioprocessing",
    icon = "__space-age__/graphics/icons/biochamber.png",
    icon_size = 64,
    order = "c-b[bioprocessing]",
  },
  {
    type = "item-group",
    name = "fw-flux",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux.png",
    icon_size = 64,
    order = "c-c[flux]",
  },
  {
    type = "item-group",
    name = "fw-chemistry",
    icon = "__FluxWorksAssets__/graphics/resources/fluids/chlorine.png",
    icon_size = 128,
    order = "c-d[chemistry]",
  },
  {
    type = "item-group",
    name = "fw-fabrication",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-foundry-lining.png",
    icon_size = 1024,
    order = "ca[fabrication]",
  },
  {
    type = "item-subgroup",
    name = "fw-science-packs",
    group = "fw-science",
    order = "a[science-packs]",
  },
  {
    type = "item-subgroup",
    name = "fw-science-labs",
    group = "fw-science",
    order = "b[labs]",
  },
  {
    type = "item-subgroup",
    name = "fw-bioprocessing-machines",
    group = "fw-bioprocessing",
    order = "a[machines]",
  },
  {
    type = "item-subgroup",
    name = "fw-bioprocessing-products",
    group = "fw-bioprocessing",
    order = "b[products]",
  },
  {
    type = "item-subgroup",
    name = "fw-bioprocessing-processes",
    group = "fw-bioprocessing",
    order = "c[processes]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-machines",
    group = "fw-flux",
    order = "a[machines]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-resources",
    group = "fw-flux",
    order = "b[resources]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-systems",
    group = "fw-flux",
    order = "c[systems]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-purple",
    group = "fw-flux",
    order = "d[purple]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-yellow",
    group = "fw-flux",
    order = "e[yellow]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-red",
    group = "fw-flux",
    order = "f[red]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-green",
    group = "fw-flux",
    order = "g[green]",
  },
  {
    type = "item-subgroup",
    name = "fw-transmutation-upcycle",
    group = "fw-flux",
    order = "h[transmutation]-a[upcycle]",
  },
  {
    type = "item-subgroup",
    name = "fw-transmutation-downcycle",
    group = "fw-flux",
    order = "i[transmutation]-b[downcycle]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-condensing-core",
    group = "fw-flux",
    order = "j[condensing]-a[core]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-condensing-promethium",
    group = "fw-flux",
    order = "k[condensing]-b[promethium]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-exchange",
    group = "fw-flux",
    order = "l[exchange]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-machines",
    group = "fw-chemistry",
    order = "a[machines]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-fluids",
    group = "fw-chemistry",
    order = "b[fluids]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-materials",
    group = "fw-chemistry",
    order = "c[materials]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-processes",
    group = "fw-chemistry",
    order = "d[processes]",
  },
  {
    type = "item-subgroup",
    name = "fw-intermediate-structural",
    group = "fw-fabrication",
    order = "b[structural]",
  },
  {
    type = "item-subgroup",
    name = "fw-intermediate-electrical",
    group = "fw-fabrication",
    order = "c[electrical]",
  },
  {
    type = "item-subgroup",
    name = "fw-intermediate-precision",
    group = "fw-fabrication",
    order = "d[precision]",
  },
  {
    type = "item-subgroup",
    name = "fw-intermediate-ballistic",
    group = "fw-fabrication",
    order = "e[ballistic]",
  },
  {
    type = "item-subgroup",
    name = "fw-intermediate-aerospace",
    group = "fw-fabrication",
    order = "f[aerospace]",
  },
  {
    type = "item-subgroup",
    name = "fw-fabrication-components",
    group = "fw-fabrication",
    order = "y[components]",
  },
  {
    type = "item-subgroup",
    name = "fw-fabrication-machines",
    group = "fw-fabrication",
    order = "a[machines]",
  },
})
