data:extend({
  {
    type = "item-group",
    name = "fw-science",
    icon = "__base__/graphics/icons/lab.png",
    icon_size = 64,
    order = "z[fluxworks]-a[science]",
  },
  {
    type = "item-group",
    name = "fw-bioprocessing",
    icon = "__space-age__/graphics/icons/biochamber.png",
    icon_size = 64,
    order = "z[fluxworks]-b[bioprocessing]",
  },
  {
    type = "item-group",
    name = "fw-energy",
    icon = "__space-age__/graphics/icons/fusion-power-cell.png",
    icon_size = 64,
    order = "z[fluxworks]-c[energy]",
  },
  {
    type = "item-group",
    name = "fw-chemistry",
    icon = "__Krastorio2Assets__/icons/fluids/chlorine.png",
    icon_size = 64,
    order = "z[fluxworks]-d[chemistry]",
  },
  {
    type = "item-group",
    name = "fw-systems",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-logic-matrix.png",
    icon_size = 64,
    order = "z[fluxworks]-e[systems]",
  },
  {
    type = "item-group",
    name = "fw-fabrication",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-foundry-lining.png",
    icon_size = 1024,
    order = "z[fluxworks]-f[fabrication]",
  },
  {
    type = "item-group",
    name = "fw-flux",
    icon = "__FluxWorksAssets__/graphics/icons/items/flux.png",
    icon_size = 64,
    order = "z[fluxworks]-g[flux]",
  },
  -- Keep FluxWorks content inside the vanilla logistics/production tabs where
  -- it already feels at home, while giving the custom branches their own tabs.
  {
    type = "item-subgroup",
    name = "fw-logistics-transport",
    group = "logistics",
    order = "z[fluxworks]-0[transport]",
  },
  {
    type = "item-subgroup",
    name = "fw-logistics-inserters",
    group = "logistics",
    order = "z[fluxworks]-1[inserters]",
  },
  {
    type = "item-subgroup",
    name = "fw-logistics-storage",
    group = "logistics",
    order = "z[fluxworks]-2[storage]",
  },
  {
    type = "item-subgroup",
    name = "fw-logistics-fluid-handling",
    group = "logistics",
    order = "z[fluxworks]-3[fluid-handling]",
  },
  {
    type = "item-subgroup",
    name = "fw-logistics-rail",
    group = "logistics",
    order = "z[fluxworks]-4[rail]",
  },
  {
    type = "item-subgroup",
    name = "fw-logistics-power",
    group = "logistics",
    order = "z[fluxworks]-5[power]",
  },
  {
    type = "item-subgroup",
    name = "fw-logistics-circuitry",
    group = "logistics",
    order = "z[fluxworks]-6[circuitry]",
  },
  {
    type = "item-subgroup",
    name = "fw-logistics-robotics",
    group = "logistics",
    order = "z[fluxworks]-7[robotics]",
  },
  {
    type = "item-subgroup",
    name = "fw-logistics-network",
    group = "logistics",
    order = "z[fluxworks]-8[network]",
  },
  {
    type = "item-subgroup",
    name = "fw-production-extraction",
    group = "production",
    order = "z[fluxworks]-9[extraction]",
  },
  {
    type = "item-subgroup",
    name = "fw-production-smelting",
    group = "production",
    order = "z[fluxworks]-a[smelting]",
  },
  {
    type = "item-subgroup",
    name = "fw-production-assembly",
    group = "production",
    order = "z[fluxworks]-b[assembly]",
  },
  {
    type = "item-subgroup",
    name = "fw-production-chemistry",
    group = "production",
    order = "z[fluxworks]-c[chemistry]",
  },
  {
    type = "item-subgroup",
    name = "fw-production-specialized",
    group = "production",
    order = "z[fluxworks]-d[specialized]",
  },
  {
    type = "item-subgroup",
    name = "fw-production-processing",
    group = "production",
    order = "z[fluxworks]-e[processing]",
  },
  {
    type = "item-subgroup",
    name = "fw-science-packs",
    group = "fw-science",
    order = "z[fluxworks]-a[science]-a[packs]",
  },
  {
    type = "item-subgroup",
    name = "fw-science-labs",
    group = "fw-science",
    order = "z[fluxworks]-a[science]-b[labs]",
  },
  {
    type = "item-subgroup",
    name = "fw-science-facilities",
    group = "fw-science",
    order = "z[fluxworks]-a[science]-c[facilities]",
  },
  {
    type = "item-subgroup",
    name = "fw-bioprocessing-machines",
    group = "fw-bioprocessing",
    order = "z[fluxworks]-b[bioprocessing]-a[machines]",
  },
  {
    type = "item-subgroup",
    name = "fw-bioprocessing-products",
    group = "fw-bioprocessing",
    order = "z[fluxworks]-b[bioprocessing]-b[products]",
  },
  {
    type = "item-subgroup",
    name = "fw-bioprocessing-processes",
    group = "fw-bioprocessing",
    order = "z[fluxworks]-b[bioprocessing]-c[processes]",
  },
  {
    type = "item-subgroup",
    name = "fw-energy-generation",
    group = "fw-energy",
    order = "z[fluxworks]-c[energy]-a[generation]",
  },
  {
    type = "item-subgroup",
    name = "fw-energy-storage",
    group = "fw-energy",
    order = "z[fluxworks]-c[energy]-b[storage]",
  },
  {
    type = "item-subgroup",
    name = "fw-energy-reactors",
    group = "fw-energy",
    order = "z[fluxworks]-c[energy]-c[reactors]",
  },
  {
    type = "item-subgroup",
    name = "fw-energy-fuels",
    group = "fw-energy",
    order = "z[fluxworks]-c[energy]-d[fuels]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-machines",
    group = "fw-chemistry",
    order = "z[fluxworks]-d[chemistry]-a[machines]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-feedstocks",
    group = "fw-chemistry",
    order = "z[fluxworks]-d[chemistry]-b[feedstocks]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-polymers",
    group = "fw-chemistry",
    order = "z[fluxworks]-d[chemistry]-c[polymers]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-reactives",
    group = "fw-chemistry",
    order = "z[fluxworks]-d[chemistry]-d[reactives]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-fluids",
    group = "fw-chemistry",
    order = "z[fluxworks]-d[chemistry]-e[fluids]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-petrochem",
    group = "fw-chemistry",
    order = "z[fluxworks]-d[chemistry]-f[petrochem]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-advanced",
    group = "fw-chemistry",
    order = "z[fluxworks]-d[chemistry]-g[advanced]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-barrels",
    group = "fw-chemistry",
    order = "z[fluxworks]-d[chemistry]-h[barrels]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-materials",
    group = "fw-chemistry",
    order = "z[fluxworks]-d[chemistry]-i[materials]",
  },
  {
    type = "item-subgroup",
    name = "fw-chemistry-processes",
    group = "fw-chemistry",
    order = "z[fluxworks]-d[chemistry]-j[processes]",
  },
  {
    type = "item-subgroup",
    name = "fw-systems-machines",
    group = "fw-systems",
    order = "z[fluxworks]-e[systems]-a[machines]",
  },
  {
    type = "item-subgroup",
    name = "fw-systems-control",
    group = "fw-systems",
    order = "z[fluxworks]-e[systems]-b[control]",
  },
  {
    type = "item-subgroup",
    name = "fw-systems-instrumentation",
    group = "fw-systems",
    order = "z[fluxworks]-e[systems]-c[instrumentation]",
  },
  {
    type = "item-subgroup",
    name = "fw-systems-infrastructure",
    group = "fw-systems",
    order = "z[fluxworks]-e[systems]-d[infrastructure]",
  },
  {
    type = "item-subgroup",
    name = "fw-fabrication-machines",
    group = "fw-fabrication",
    order = "z[fluxworks]-f[fabrication]-a[machines]",
  },
  {
    type = "item-subgroup",
    name = "fw-intermediate-structural",
    group = "fw-fabrication",
    order = "z[fluxworks]-f[fabrication]-b[structural]",
  },
  {
    type = "item-subgroup",
    name = "fw-intermediate-electrical",
    group = "fw-fabrication",
    order = "z[fluxworks]-f[fabrication]-c[electrical]",
  },
  {
    type = "item-subgroup",
    name = "fw-intermediate-precision",
    group = "fw-fabrication",
    order = "z[fluxworks]-f[fabrication]-d[precision]",
  },
  {
    type = "item-subgroup",
    name = "fw-intermediate-ballistic",
    group = "fw-fabrication",
    order = "z[fluxworks]-f[fabrication]-e[ballistic]",
  },
  {
    type = "item-subgroup",
    name = "fw-intermediate-aerospace",
    group = "fw-fabrication",
    order = "z[fluxworks]-f[fabrication]-f[aerospace]",
  },
  {
    type = "item-subgroup",
    name = "fw-fabrication-components",
    group = "fw-fabrication",
    order = "z[fluxworks]-f[fabrication]-g[general]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-machines",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-a[machines]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-resources",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-b[resources]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-systems",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-c[systems]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-purple",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-d[purple]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-yellow",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-e[yellow]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-red",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-f[red]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-green",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-g[green]",
  },
  {
    type = "item-subgroup",
    name = "fw-transmutation-upcycle",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-h[transmutation]-a[upcycle]",
  },
  {
    type = "item-subgroup",
    name = "fw-transmutation-downcycle",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-i[transmutation]-b[downcycle]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-condensing-core",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-j[condensing]-a[core]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-condensing-promethium",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-k[condensing]-b[promethium]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-exchange",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-l[exchange]",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-origin-projects",
    group = "fw-flux",
    order = "z[fluxworks]-g[flux]-m[origin-projects]",
  },
})
