local icon_path = "__FluxWorksAssets__/graphics/icons/items/"

data:extend({
  {
    type = "item",
    name = "fw-petrochemical-facility",
    icon = "__Age-of-Production-Graphics__/graphics/icons/petrochemical-facility.png",
    icon_size = 64,
    subgroup = "fw-chemistry-machines",
    order = "a[fw-petrochemical-facility]",
    place_result = "fw-petrochemical-facility",
    stack_size = 20,
  },
  {
    type = "item",
    name = "fw-hydraulic-plant",
    icon = "__Age-of-Production-Graphics__/graphics/icons/hydraulic-plant.png",
    icon_size = 64,
    subgroup = "fw-fabrication-machines",
    order = "b[fw-hydraulic-plant]",
    place_result = "fw-hydraulic-plant",
    stack_size = 20,
  },
  {
    type = "item",
    name = "fw-polymer-binder",
    icon = icon_path .. "fw-polymer-binder.png",
    icon_size = 64,
    subgroup = "fw-chemistry-materials",
    order = "r[fw-polymer-binder]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-chlorinated-binder-stock",
    icon = icon_path .. "fw-chlorinated-binder-stock.png",
    icon_size = 64,
    subgroup = "fw-chemistry-materials",
    order = "s[fw-chlorinated-binder-stock]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-elastomer-matrix",
    icon = icon_path .. "fw-elastomer-matrix.png",
    icon_size = 64,
    subgroup = "fw-chemistry-materials",
    order = "t[fw-elastomer-matrix]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-reinforced-seal",
    icon = icon_path .. "fw-reinforced-seal.png",
    icon_size = 64,
    subgroup = "fw-intermediate-structural",
    order = "r[fw-reinforced-seal]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-hydraulic-actuator",
    icon = icon_path .. "fw-hydraulic-actuator.png",
    icon_size = 64,
    subgroup = "fw-intermediate-structural",
    order = "s[fw-hydraulic-actuator]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-servo-valve",
    icon = icon_path .. "fw-servo-valve.png",
    icon_size = 64,
    subgroup = "fw-intermediate-precision",
    order = "o[fw-servo-valve]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-hydraulic-manifold",
    icon = icon_path .. "fw-hydraulic-manifold.png",
    icon_size = 64,
    subgroup = "fw-intermediate-precision",
    order = "q[fw-hydraulic-manifold]",
    stack_size = 100,
  },
})
