local icon_path = "__FluxWorksAssets__/graphics/icons/items/"
local late_utility_icon_path = "__FluxWorksAssets__/graphics/icons/items/late-utility/"

data:extend({
  {
    type = "item-subgroup",
    name = "fw-flux-systems",
    group = "intermediate-products",
    order = "ff",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-exchange",
    group = "intermediate-products",
    order = "fg",
  },
  {
    type = "item",
    name = "fw-flux-catalyst",
    icon = icon_path .. "flux-2.png",
    icon_size = 64,
    subgroup = "fw-flux-systems",
    order = "a[fw-flux-catalyst]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-stabilized-flux-crystal",
    icon = icon_path .. "flux-3.png",
    icon_size = 64,
    subgroup = "fw-flux-systems",
    order = "b[fw-stabilized-flux-crystal]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-flux-lattice",
    icon = icon_path .. "fw-metal-mesh.png",
    icon_size = 1024,
    subgroup = "fw-flux-systems",
    order = "c[fw-flux-lattice]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-harvester-head",
    icons = {
      { icon = icon_path .. "fw-flux-harvester.png", icon_size = 64 },
      { icon = icon_path .. "flux-2-light.png", icon_size = 64, scale = 0.5, shift = { 8, 8 } },
    },
    subgroup = "fw-flux-systems",
    order = "c1[fw-harvester-head]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "fw-annealed-cermet",
    icons = {
      { icon = icon_path .. "fw-cermet.png", icon_size = 1024 },
      { icon = icon_path .. "flux-1-light.png", icon_size = 64, scale = 7.5, shift = { 136, -136 }, tint = { r = 1.0, g = 0.65, b = 0.55, a = 0.85 } },
    },
    subgroup = "fw-flux-systems",
    order = "c2[fw-annealed-cermet]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-resonance-substrate",
    icons = {
      { icon = icon_path .. "fw-circuit-substrate.png", icon_size = 1024 },
      { icon = icon_path .. "flux-2-light.png", icon_size = 64, scale = 7.25, shift = { 136, -136 }, tint = { r = 0.95, g = 1.0, b = 1.0, a = 0.9 } },
    },
    subgroup = "fw-flux-systems",
    order = "c3[fw-resonance-substrate]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-condensed-flux-matrix",
    icon = icon_path .. "flux-1-light.png",
    icon_size = 64,
    subgroup = "fw-flux-systems",
    order = "d[fw-condensed-flux-matrix]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-flux-resonance-cell",
    icon = icon_path .. "flux-2-light.png",
    icon_size = 64,
    subgroup = "fw-flux-systems",
    order = "e[fw-flux-resonance-cell]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-flux-phase-manifold",
    icon = icon_path .. "fw-circuit-substrate.png",
    icon_size = 1024,
    subgroup = "fw-flux-systems",
    order = "f[fw-flux-phase-manifold]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "fw-phase-anchor",
    icon = late_utility_icon_path .. "fw-phase-anchor.png",
    icon_size = 1024,
    subgroup = "fw-flux-systems",
    order = "g[fw-phase-anchor]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "fw-entanglement-core",
    icon = late_utility_icon_path .. "fw-entanglement-core.png",
    icon_size = 1024,
    subgroup = "fw-flux-systems",
    order = "h[fw-entanglement-core]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "fw-reservoir-lining",
    icon = late_utility_icon_path .. "fw-reservoir-lining.png",
    icon_size = 1024,
    subgroup = "fw-flux-systems",
    order = "i[fw-reservoir-lining]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "fw-compression-baffle",
    icon = late_utility_icon_path .. "fw-compression-baffle.png",
    icon_size = 1024,
    subgroup = "fw-flux-systems",
    order = "j[fw-compression-baffle]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "fw-thermal-phase-gasket",
    icon = late_utility_icon_path .. "fw-thermal-phase-gasket.png",
    icon_size = 1024,
    subgroup = "fw-flux-systems",
    order = "k[fw-thermal-phase-gasket]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "fw-rift-coupler",
    icon = late_utility_icon_path .. "fw-rift-coupler.png",
    icon_size = 1024,
    subgroup = "fw-flux-exchange",
    order = "a[fw-rift-coupler]",
    stack_size = 20,
  },
  {
    type = "item",
    name = "fw-phase-vault",
    icon = "__FluxWorksAssets__/graphics/icons/items/deep-storage-unit/memory-unit.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "fw-flux-exchange",
    order = "b[fw-phase-vault]",
    stack_size = 10,
    place_result = "fw-phase-vault",
  },
  {
    type = "item",
    name = "fw-spectral-reservoir",
    icon = "__FluxWorksAssets__/graphics/icons/items/fluid-memory-storage/fluid-memory-unit.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "fw-flux-exchange",
    order = "c[fw-spectral-reservoir]",
    stack_size = 10,
    place_result = "fw-spectral-reservoir",
  },
  {
    type = "item",
    name = "fw-rift-exchange-gate",
    icon = late_utility_icon_path .. "fw-rift-exchange-gate.png",
    icon_size = 1024,
    subgroup = "fw-flux-exchange",
    order = "d[fw-rift-exchange-gate]",
    stack_size = 10,
    place_result = "fw-rift-exchange-gate",
  },
})
