local icon_path = "__FluxWorksAssets__/graphics/icons/items/"

data:extend({
  {
    type = "item-subgroup",
    name = "fw-flux-systems",
    group = "intermediate-products",
    order = "ff",
  },
  {
    type = "item-subgroup",
    name = "fw-flux-exchange",
    group = "intermediate-products",
    order = "fg",
  },
  {
    type = "item",
    name = "fw-flux-catalyst",
    icon = icon_path .. "flux-2.png",
    icon_size = 64,
    subgroup = "fw-flux-systems",
    order = "a[fw-flux-catalyst]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-stabilized-flux-crystal",
    icon = icon_path .. "flux-3.png",
    icon_size = 64,
    subgroup = "fw-flux-systems",
    order = "b[fw-stabilized-flux-crystal]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-flux-lattice",
    icon = icon_path .. "fw-metal-mesh.png",
    icon_size = 1024,
    subgroup = "fw-flux-systems",
    order = "c[fw-flux-lattice]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-condensed-flux-matrix",
    icon = icon_path .. "flux-1-light.png",
    icon_size = 64,
    subgroup = "fw-flux-systems",
    order = "d[fw-condensed-flux-matrix]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-flux-resonance-cell",
    icon = icon_path .. "flux-2-light.png",
    icon_size = 64,
    subgroup = "fw-flux-systems",
    order = "e[fw-flux-resonance-cell]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-flux-phase-manifold",
    icon = icon_path .. "fw-circuit-substrate.png",
    icon_size = 1024,
    subgroup = "fw-flux-systems",
    order = "f[fw-flux-phase-manifold]",
    stack_size = 50,
  },
})
