local item_sounds = require("__base__.prototypes.item_sounds")

data:extend({
  {
    type = "item",
    name = "lead-plate",
    icon = "__FluxWorksAssets__/graphics/icons/items/metal-plate-lead.png",
    icon_size = 256,
    inventory_move_sound = item_sounds.metal_small_inventory_move,
    pick_sound = item_sounds.metal_small_inventory_pickup,
    drop_sound = item_sounds.metal_small_inventory_move,
    subgroup = "raw-material",
    order = "d[lead-plate]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "titanium-plate",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-titanium-plate.png",
    icon_size = 128,
    inventory_move_sound = item_sounds.metal_small_inventory_move,
    pick_sound = item_sounds.metal_small_inventory_pickup,
    drop_sound = item_sounds.metal_small_inventory_move,
    subgroup = "raw-material",
    order = "d[titanium-plate]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "aluminum-plate",
    icon = "__FluxWorksAssets__/graphics/icons/items/aluminum-plate.png",
    icon_size = 128,
    inventory_move_sound = item_sounds.metal_small_inventory_move,
    pick_sound = item_sounds.metal_small_inventory_pickup,
    drop_sound = item_sounds.metal_small_inventory_move,
    subgroup = "raw-material",
    order = "d[aluminum-plate]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "tin-plate",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-tin-plate.png",
    icon_size = 128,
    inventory_move_sound = item_sounds.metal_small_inventory_move,
    pick_sound = item_sounds.metal_small_inventory_pickup,
    drop_sound = item_sounds.metal_small_inventory_move,
    subgroup = "raw-material",
    order = "d[tin-plate]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "bronze-plate",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bronze-plate.png",
    icon_size = 128,
    inventory_move_sound = item_sounds.metal_small_inventory_move,
    pick_sound = item_sounds.metal_small_inventory_pickup,
    drop_sound = item_sounds.metal_small_inventory_move,
    subgroup = "raw-material",
    order = "d[bronze-plate]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "silicon",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-silicon-ore-clean.png",
    icon_size = 64,
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    subgroup = "raw-material",
    order = "d[silicon]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-carbon",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-bz-carbon-ore.png",
    icon_size = 128,
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    subgroup = "raw-material",
    order = "d[fw-carbon]",
    stack_size = 100,
  },
})
