local icon_path = "__FluxWorksAssets__/graphics/icons/items/"
data:extend({
  {
    type = "item",
    name = "fw-fired-ceramic",
    icon = icon_path .. "fw-fired-ceramic.png",
    icon_size = 256,
    subgroup = "fw-intermediate-structural",
    order = "l[fw-fired-ceramic]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-ceramic-casing",
    icon = icon_path .. "fw-ceramic-casing.png",
    icon_size = 64,
    subgroup = "fw-intermediate-structural",
    order = "m[fw-ceramic-casing]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-coil-block",
    icon = icon_path .. "fw-coil-block.png",
    icon_size = 256,
    subgroup = "fw-intermediate-electrical",
    order = "g[fw-coil-block]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-signal-conduit",
    icon = icon_path .. "fw-signal-conduit.png",
    icon_size = 256,
    subgroup = "fw-intermediate-electrical",
    order = "h[fw-signal-conduit]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "fw-lens-array",
    icon = icon_path .. "fw-lens-array.png",
    icon_size = 256,
    subgroup = "fw-intermediate-precision",
    order = "l[fw-lens-array]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-pressure-housing",
    icon = icon_path .. "fw-pressure-housing.png",
    icon_size = 256,
    subgroup = "fw-intermediate-structural",
    order = "n[fw-pressure-housing]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-flow-regulator",
    icon = icon_path .. "fw-flow-regulator.png",
    icon_size = 256,
    subgroup = "fw-intermediate-precision",
    order = "n[fw-flow-regulator]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-power-regulator",
    icon = "__base__/graphics/icons/processing-unit.png",
    icon_size = 64,
    subgroup = "fw-intermediate-electrical",
    order = "i[fw-power-regulator]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-field-winding",
    icon = icon_path .. "fw-field-winding.png",
    icon_size = 256,
    subgroup = "fw-intermediate-electrical",
    order = "j[fw-field-winding]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-foundry-lining",
    icon = icon_path .. "fw-foundry-lining.png",
    icon_size = 256,
    subgroup = "fw-intermediate-structural",
    order = "o[fw-foundry-lining]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-cryo-coil",
    icon = icon_path .. "fw-cryo-coil.png",
    icon_size = 256,
    subgroup = "fw-intermediate-electrical",
    order = "k[fw-cryo-coil]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-thermal-buffer",
    icon = icon_path .. "fw-thermal-buffer.png",
    icon_size = 256,
    subgroup = "fw-intermediate-structural",
    order = "q[fw-thermal-buffer]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-em-core",
    icon = icon_path .. "fw-em-core.png",
    icon_size = 256,
    subgroup = "fw-intermediate-electrical",
    order = "l[fw-em-core]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-logic-matrix",
    icon = icon_path .. "fw-logic-matrix.png",
    icon_size = 128,
    subgroup = "fw-intermediate-precision",
    order = "o[fw-logic-matrix]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-promethium-shard",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-promethium-shard.png",
    icon_size = 1254,
    subgroup = "fw-flux-resources",
    order = "f[fw-promethium-shard]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "fw-promethium-matrix",
    icon = icon_path .. "fw-promethium-matrix.png",
    icon_size = 256,
    subgroup = "fw-flux-systems",
    order = "g[fw-promethium-matrix]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "fw-rift-stabilizer",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-rift-stabilizer.png",
    icon_size = 128,
    subgroup = "fw-flux-systems",
    order = "h[fw-rift-stabilizer]",
    stack_size = 50,
  },
})
