local icon_path = "__FluxWorksAssets__/graphics/icons/items/"

local function tech_unit(count, science_packs, time)
  return {
    count = count,
    ingredients = science_packs,
    time = time,
  }
end

local function unlock(recipe_name)
  return { type = "unlock-recipe", recipe = recipe_name }
end

data:extend({
  {
    type = "technology",
    name = "fw-isotope-conditioning",
    icon = icon_path .. "fw-isotope-matrix.png",
    icon_size = 64,
    prerequisites = { "fw-flux-metallurgy", "nuclear-power" },
    unit = tech_unit(440, {
      { "automation-science-pack", 1 },
      { "logistic-science-pack", 1 },
      { "chemical-science-pack", 1 },
      { "production-science-pack", 1 },
      { "utility-science-pack", 1 },
      { "space-science-pack", 1 },
    }, 36),
    effects = {},
    order = "d-hc[fw-isotope-conditioning]",
  },
  {
    type = "technology",
    name = "fw-fuel-fabrication",
    icon = "__finely-crafted-graphics__/graphics/atom-forge/atom-forge-icon.png",
    icon_size = 64,
    prerequisites = { "fw-isotope-conditioning" },
    unit = tech_unit(460, {
      { "automation-science-pack", 1 },
      { "logistic-science-pack", 1 },
      { "chemical-science-pack", 1 },
      { "production-science-pack", 1 },
      { "utility-science-pack", 1 },
      { "space-science-pack", 1 },
    }, 36),
    effects = {
      unlock("fw-atomic-enricher"),
      unlock("fw-shielded-fuel-casing"),
      unlock("fw-fuel-pellet-bundle"),
      unlock("fw-precision-uranium-assay"),
    },
    order = "d-hd[fw-fuel-fabrication]",
  },
  {
    type = "technology",
    name = "fw-lattice-moderation",
    icon = icon_path .. "fw-moderator-lattice.png",
    icon_size = 64,
    prerequisites = { "fw-isotope-conditioning", "fw-flux-resonance" },
    unit = tech_unit(480, {
      { "automation-science-pack", 1 },
      { "logistic-science-pack", 1 },
      { "chemical-science-pack", 1 },
      { "production-science-pack", 1 },
      { "utility-science-pack", 1 },
      { "space-science-pack", 1 },
    }, 38),
    effects = {
      unlock("fw-moderator-lattice"),
      unlock("fw-isotope-matrix"),
      unlock("fw-reactor-grade-fuel-cell"),
      unlock("fw-flux-isotope-separation"),
    },
    order = "d-he[fw-lattice-moderation]",
  },
  {
    type = "technology",
    name = "fw-reactor-doping",
    icon = icon_path .. "fw-reactor-dopant.png",
    icon_size = 256,
    prerequisites = {
      "fw-fuel-fabrication",
      "fw-lattice-moderation",
      "kovarex-enrichment-process",
      "fw-cryogenic-control",
    },
    unit = tech_unit(540, {
      { "automation-science-pack", 1 },
      { "logistic-science-pack", 1 },
      { "chemical-science-pack", 1 },
      { "production-science-pack", 1 },
      { "utility-science-pack", 1 },
      { "space-science-pack", 1 },
      { "cryogenic-science-pack", 1 },
    }, 40),
    effects = {
      unlock("fw-reactor-dopant"),
    },
    order = "d-hf[fw-reactor-doping]",
  },
  {
    type = "technology",
    name = "fw-reactor-safeguards",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-control-rod-assembly.png",
    icon_size = 256,
    prerequisites = { "fw-reactor-doping", "fw-thermal-retention" },
    unit = tech_unit(580, {
      { "automation-science-pack", 1 },
      { "logistic-science-pack", 1 },
      { "chemical-science-pack", 1 },
      { "production-science-pack", 1 },
      { "utility-science-pack", 1 },
      { "space-science-pack", 1 },
      { "cryogenic-science-pack", 1 },
    }, 40),
    effects = {
      unlock("fw-control-rod-assembly"),
      unlock("fw-reactor-coolant-cartridge"),
    },
    order = "d-hg[fw-reactor-safeguards]",
  },
  {
    type = "technology",
    name = "fw-actinide-recovery",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-recovered-actinides.png",
    icon_size = 64,
    prerequisites = {
      "fw-reactor-doping",
      "fw-reactor-safeguards",
      "fw-lattice-moderation",
      "fw-electromagnetic-architecture",
    },
    unit = tech_unit(640, {
      { "automation-science-pack", 1 },
      { "logistic-science-pack", 1 },
      { "chemical-science-pack", 1 },
      { "production-science-pack", 1 },
      { "utility-science-pack", 1 },
      { "space-science-pack", 1 },
      { "cryogenic-science-pack", 1 },
      { "electromagnetic-science-pack", 1 },
    }, 42),
    effects = {
      unlock("fw-spent-fuel-reconditioning"),
      unlock("fw-depleted-cell-dissolution"),
    },
    order = "d-hh[fw-actinide-recovery]",
  },
  {
    type = "technology",
    name = "fw-actinide-sorting",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-radioactive-scrap.png",
    icon_size = 256,
    prerequisites = { "fw-actinide-recovery", "fw-reactor-safeguards" },
    unit = tech_unit(700, {
      { "automation-science-pack", 1 },
      { "logistic-science-pack", 1 },
      { "chemical-science-pack", 1 },
      { "production-science-pack", 1 },
      { "utility-science-pack", 1 },
      { "space-science-pack", 1 },
      { "cryogenic-science-pack", 1 },
      { "electromagnetic-science-pack", 1 },
    }, 44),
    effects = {
      unlock("fw-radioactive-scrap-sorting"),
      unlock("fw-isotope-recovery"),
    },
    order = "d-hi[fw-actinide-sorting]",
  },
  {
    type = "technology",
    name = "fw-actinide-reforging",
    icons = {
      {
        icon = "__FluxWorksAssets__/graphics/icons/items/fw-isotope-matrix.png",
        icon_size = 64,
      },
      {
        icon = "__FluxWorksAssets__/graphics/icons/items/fw-radioactive-scrap.png",
        icon_size = 256,
        scale = 0.45,
        shift = { 9, 9 },
      },
    },
    prerequisites = { "fw-actinide-recovery", "fw-lattice-moderation" },
    unit = tech_unit(720, {
      { "automation-science-pack", 1 },
      { "logistic-science-pack", 1 },
      { "chemical-science-pack", 1 },
      { "production-science-pack", 1 },
      { "utility-science-pack", 1 },
      { "space-science-pack", 1 },
      { "cryogenic-science-pack", 1 },
      { "electromagnetic-science-pack", 1 },
    }, 44),
    effects = {
      unlock("fw-actinide-matrix-seeding"),
      unlock("fw-scrap-lattice-recasting"),
      unlock("fw-pellet-bundle-reprocessing"),
    },
    order = "d-hj[fw-actinide-reforging]",
  },
  {
    type = "technology",
    name = "fw-reactor-instrumentation",
    icon = "__FluxWorksAssets__/graphics/icons/items/fw-reactor-coolant-cartridge.png",
    icon_size = 64,
    prerequisites = {
      "fw-actinide-sorting",
      "fw-actinide-reforging",
      "fw-reactor-safeguards",
      "fw-flux-resonance",
    },
    unit = tech_unit(800, {
      { "automation-science-pack", 1 },
      { "logistic-science-pack", 1 },
      { "chemical-science-pack", 1 },
      { "production-science-pack", 1 },
      { "utility-science-pack", 1 },
      { "space-science-pack", 1 },
      { "cryogenic-science-pack", 1 },
      { "electromagnetic-science-pack", 1 },
    }, 46),
    effects = {
      unlock("fw-nuclear-fuel-overdrive"),
      unlock("fw-actinide-dopant-refining"),
      unlock("fw-fusion-cell-doping"),
    },
    order = "d-hk[fw-reactor-instrumentation]",
  },
})
