local content = require("prototypes.updates.factoriopedia-content")

local covered_descriptions = {}

local function set_factoriopedia_description(prototype_type, prototype_name, locale_key)
  if not (data.raw[prototype_type] and data.raw[prototype_type][prototype_name]) then
    return
  end
  covered_descriptions[prototype_type] = covered_descriptions[prototype_type] or {}
  covered_descriptions[prototype_type][prototype_name] = locale_key
  data.raw[prototype_type][prototype_name].factoriopedia_description = { "fw-factoriopedia." .. locale_key }
end

local function set_factoriopedia_simulation(prototype_type, prototype_name, simulation_key)
  if not (data.raw[prototype_type] and data.raw[prototype_type][prototype_name]) then
    return
  end

  local simulation = content.simulations[simulation_key]
  if not simulation then
    return
  end

  data.raw[prototype_type][prototype_name].factoriopedia_simulation = simulation
end

-- Rocket reusability entries
set_factoriopedia_description("item", "incomplete-rocket-part", "incomplete-rocket-part")
set_factoriopedia_description("item", "rocket-chunk", "rocket-chunk-item")
set_factoriopedia_description("item", "remnant-beacon", "remnant-beacon-item")
set_factoriopedia_description("item", "fw-rocket-avionics", "fw-rocket-avionics-item")
set_factoriopedia_description("item", "fw-rocket-heatshield", "fw-rocket-heatshield-item")
set_factoriopedia_description("asteroid", "used-rocket-asteroid", "used-rocket-asteroid")
set_factoriopedia_description("asteroid-chunk", "rocket-chunk", "rocket-chunk-asteroid")
set_factoriopedia_description("radar", "remnant-beacon", "remnant-beacon-entity")
set_factoriopedia_description("recipe", "incomplete-rocket-part", "incomplete-rocket-part-recipe")
set_factoriopedia_description("recipe", "rocket-chunk-processing", "rocket-chunk-processing-recipe")
set_factoriopedia_description("recipe", "remnant-beacon", "remnant-beacon-recipe")
set_factoriopedia_description("recipe", "fw-rocket-avionics", "fw-rocket-avionics-recipe")
set_factoriopedia_description("recipe", "fw-rocket-heatshield", "fw-rocket-heatshield-recipe")
set_factoriopedia_description("technology", "rocket-chunk-processing", "rocket-chunk-processing-technology")
set_factoriopedia_description("technology", "remnant-beacon", "remnant-beacon-technology")

-- FluxWorks entries
set_factoriopedia_description("item", "fw-crystalised-flux", "fw-crystalised-flux-item")
set_factoriopedia_description("item", "fw-flux-quarry", "fw-flux-quarry-item")
set_factoriopedia_description("item", "fw-rocket-engine", "fw-rocket-engine-item")
set_factoriopedia_description("item", "fw-transformer-core", "fw-transformer-core-item")
set_factoriopedia_description("item", "fw-flux-resonance-cell", "fw-flux-resonance-cell-item")
set_factoriopedia_description("item", "fw-flux-phase-manifold", "fw-flux-phase-manifold-item")
set_factoriopedia_description("item", "fw-phase-anchor", "fw-phase-anchor-item")
set_factoriopedia_description("item", "fw-entanglement-core", "fw-entanglement-core-item")
set_factoriopedia_description("item", "fw-reservoir-lining", "fw-reservoir-lining-item")
set_factoriopedia_description("item", "fw-compression-baffle", "fw-compression-baffle-item")
set_factoriopedia_description("item", "fw-thermal-phase-gasket", "fw-thermal-phase-gasket-item")
set_factoriopedia_description("item", "fw-phase-vault", "fw-phase-vault-item")
set_factoriopedia_description("item", "fw-spectral-reservoir", "fw-spectral-reservoir-item")
set_factoriopedia_description("item", "fw-rift-coupler", "fw-rift-coupler-item")
set_factoriopedia_description("item", "fw-rift-exchange-gate", "fw-rift-exchange-gate-item")
set_factoriopedia_description("item", "fw-origin-forge", "fw-origin-forge-item")
set_factoriopedia_description("item", "fw-storm-spine-segment", "fw-storm-spine-segment-item")
set_factoriopedia_description("item", "fw-origin-crucible-lining", "fw-origin-crucible-lining-item")
set_factoriopedia_description("item", "fw-harmonic-lattice-core", "fw-harmonic-lattice-core-item")
set_factoriopedia_description("item", "fw-living-reactor-weave", "fw-living-reactor-weave-item")
set_factoriopedia_description("item", "fw-origin-catalyst-manifold", "fw-origin-catalyst-manifold-item")
set_factoriopedia_description("item", "fw-storm-spine", "fw-storm-spine-item")
set_factoriopedia_description("item", "fw-origin-crucible", "fw-origin-crucible-item")
set_factoriopedia_description("item", "fw-universal-collapse-core", "fw-universal-collapse-core-item")
set_factoriopedia_description("item", "fw-genesis-ark", "fw-genesis-ark-item")
set_factoriopedia_description("item", "fw-origin-singularity", "fw-origin-singularity-item")
set_factoriopedia_description("item", "fw-harvester-head", "fw-harvester-head-item")
set_factoriopedia_description("item", "fw-annealed-cermet", "fw-annealed-cermet-item")
set_factoriopedia_description("item", "fw-resonance-substrate", "fw-resonance-substrate-item")
set_factoriopedia_description("item", "fw-flux-harvester", "fw-flux-harvester-item")
set_factoriopedia_description("item", "fw-arc-foundry", "fw-arc-foundry-item")
set_factoriopedia_description("item", "fw-synthesis-plant", "fw-synthesis-plant-item")
set_factoriopedia_description("item", "fw-flux-condenser", "fw-flux-condenser-item")
set_factoriopedia_description("item", "fw-shattered-convergence-array", "fw-shattered-convergence-array-item")
set_factoriopedia_description("item", "fw-promethium-shard", "fw-promethium-shard-item")
set_factoriopedia_description("item", "fw-promethium-primer", "fw-promethium-primer-item")
set_factoriopedia_description("item", "fw-stabilized-flux-crystal", "fw-stabilized-flux-crystal-item")
set_factoriopedia_description("item", "fw-flux-lattice", "fw-flux-lattice-item")
set_factoriopedia_description("item", "fw-condensed-flux-matrix", "fw-condensed-flux-matrix-item")
set_factoriopedia_description("item", "fw-flux-catalyst", "fw-flux-catalyst-item")
set_factoriopedia_description("resource", "fw-crystalised-flux", "fw-crystalised-flux-resource")
set_factoriopedia_description("resource", "fw-metallic-deposit", "fw-metallic-deposit-resource")
set_factoriopedia_description("resource", "fw-mineral-deposit", "fw-mineral-deposit-resource")
set_factoriopedia_description("resource", "fw-carbonic-deposit", "fw-carbonic-deposit-resource")
set_factoriopedia_description("resource", "fw-promethium-impact", "fw-promethium-impact-resource")
set_factoriopedia_description("resource", "fw-silica-vein", "fw-silica-vein-resource")
set_factoriopedia_description("resource", "fw-shattered-yellow-flux-vent", "fw-shattered-yellow-flux-vent-resource")
set_factoriopedia_description("resource", "fw-shattered-red-flux-vent", "fw-shattered-red-flux-vent-resource")
set_factoriopedia_description("resource", "fw-shattered-green-flux-vent", "fw-shattered-green-flux-vent-resource")
set_factoriopedia_description("resource", "fw-shattered-purple-flux-vent", "fw-shattered-purple-flux-vent-resource")
set_factoriopedia_description("recipe", "fw-flux-quarry", "fw-flux-quarry-recipe")
set_factoriopedia_description("recipe", "fw-purple-flux", "fw-purple-flux-recipe")
set_factoriopedia_description("recipe", "fw-flux-catalyst", "fw-flux-catalyst-recipe")
set_factoriopedia_description("recipe", "fw-flux-harvester", "fw-flux-harvester-recipe")
set_factoriopedia_description("recipe", "fw-arc-foundry", "fw-arc-foundry-recipe")
set_factoriopedia_description("recipe", "fw-synthesis-plant", "fw-synthesis-plant-recipe")
set_factoriopedia_description("recipe", "fw-flux-condenser", "fw-flux-condenser-recipe")
set_factoriopedia_description("recipe", "fw-shattered-convergence-array", "fw-shattered-convergence-array-recipe")
set_factoriopedia_description("recipe", "fw-promethium-primer", "fw-promethium-primer-recipe")
set_factoriopedia_description("recipe", "fw-stabilized-flux-crystal", "fw-stabilized-flux-crystal-recipe")
set_factoriopedia_description("recipe", "fw-flux-lattice", "fw-flux-lattice-recipe")
set_factoriopedia_description("recipe", "fw-condensed-flux-matrix", "fw-condensed-flux-matrix-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-condensed-flux-matrix", "fw-ion-storm-condensed-flux-matrix-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-promethium-primer", "fw-ion-storm-promethium-primer-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-catalyst-forging", "fw-ion-storm-catalyst-forging-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-spore-resin-culture", "fw-ion-storm-spore-resin-culture-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-fuel-pellet-bundling", "fw-ion-storm-fuel-pellet-bundling-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-resonance-weaving", "fw-ion-storm-resonance-weaving-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-cryogel-annealing", "fw-ion-storm-cryogel-annealing-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-static-mesh-overcharge", "fw-ion-storm-static-mesh-overcharge-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-slag-cermet-tempering", "fw-ion-storm-slag-cermet-tempering-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-superconductor-bath", "fw-ion-storm-superconductor-bath-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-resonance-cell-overdrive", "fw-ion-storm-resonance-cell-overdrive-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-phase-manifold-weaving", "fw-ion-storm-phase-manifold-weaving-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-fusion-power-cell-conditioning", "fw-ion-storm-fusion-power-cell-conditioning-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-rift-seed-crystallization", "fw-ion-storm-rift-seed-crystallization-recipe")
set_factoriopedia_description("recipe", "fw-ion-storm-rift-stabilizer-convergence", "fw-ion-storm-rift-stabilizer-convergence-recipe")
set_factoriopedia_description("recipe", "fw-origin-singularity", "fw-origin-singularity-recipe")
set_factoriopedia_description("recipe", "fw-origin-cascade", "fw-origin-cascade-recipe")
set_factoriopedia_description("recipe", "fw-origin-forge", "fw-origin-forge-recipe")
set_factoriopedia_description("recipe", "fw-storm-spine-segment", "fw-storm-spine-segment-recipe")
set_factoriopedia_description("recipe", "fw-origin-crucible-lining", "fw-origin-crucible-lining-recipe")
set_factoriopedia_description("recipe", "fw-harmonic-lattice-core", "fw-harmonic-lattice-core-recipe")
set_factoriopedia_description("recipe", "fw-living-reactor-weave", "fw-living-reactor-weave-recipe")
set_factoriopedia_description("recipe", "fw-origin-catalyst-manifold", "fw-origin-catalyst-manifold-recipe")
set_factoriopedia_description("recipe", "fw-storm-spine", "fw-storm-spine-recipe")
set_factoriopedia_description("recipe", "fw-origin-crucible", "fw-origin-crucible-recipe")
set_factoriopedia_description("recipe", "fw-universal-collapse-core", "fw-universal-collapse-core-recipe")
set_factoriopedia_description("recipe", "fw-genesis-ark", "fw-genesis-ark-recipe")
set_factoriopedia_description("recipe", "fw-phase-vault", "fw-phase-vault-recipe")
set_factoriopedia_description("recipe", "fw-spectral-reservoir", "fw-spectral-reservoir-recipe")
set_factoriopedia_description("recipe", "fw-rift-exchange-gate", "fw-rift-exchange-gate-recipe")
set_factoriopedia_description("mining-drill", "fw-flux-quarry", "fw-flux-quarry-entity")
set_factoriopedia_description("assembling-machine", "fw-flux-harvester", "fw-flux-harvester-entity")
set_factoriopedia_description("assembling-machine", "fw-arc-foundry", "fw-arc-foundry-entity")
set_factoriopedia_description("assembling-machine", "fw-synthesis-plant", "fw-synthesis-plant-entity")
set_factoriopedia_description("assembling-machine", "fw-flux-condenser", "fw-flux-condenser-entity")
set_factoriopedia_description("assembling-machine", "fw-shattered-convergence-array", "fw-shattered-convergence-array-entity")
set_factoriopedia_description("assembling-machine", "fw-origin-forge", "fw-origin-forge-entity")
set_factoriopedia_description("container", "fw-phase-vault", "fw-phase-vault-entity")
set_factoriopedia_description("storage-tank", "fw-spectral-reservoir", "fw-spectral-reservoir-entity")
set_factoriopedia_description("container", "fw-rift-exchange-gate", "fw-rift-exchange-gate-entity")
set_factoriopedia_description("container", "fw-origin-singularity", "fw-origin-singularity-entity")
set_factoriopedia_description("fluid", "fw-purple-flux", "fw-purple-flux-fluid")
set_factoriopedia_description("fluid", "fw-yellow-flux", "fw-yellow-flux-fluid")
set_factoriopedia_description("fluid", "fw-red-flux", "fw-red-flux-fluid")
set_factoriopedia_description("fluid", "fw-green-flux", "fw-green-flux-fluid")
set_factoriopedia_description("technology", "fw-ceramic-engineering", "fw-ceramic-engineering-technology")
set_factoriopedia_description("technology", "fw-conductive-networks", "fw-conductive-networks-technology")
set_factoriopedia_description("technology", "fw-optical-instrumentation", "fw-optical-instrumentation-technology")
set_factoriopedia_description("technology", "fw-sealed-systems", "fw-sealed-systems-technology")
set_factoriopedia_description("technology", "fw-polymer-chemistry", "fw-polymer-chemistry-technology")
set_factoriopedia_description("technology", "fw-power-regulation", "fw-power-regulation-technology")
set_factoriopedia_description("technology", "fw-energetic-compounds", "fw-energetic-compounds-technology")
set_factoriopedia_description("technology", "fw-metallurgic-assemblies", "fw-metallurgic-assemblies-technology")
set_factoriopedia_description("technology", "fw-biosystems-engineering", "fw-biosystems-engineering-technology")
set_factoriopedia_description("technology", "fw-cryogenic-control", "fw-cryogenic-control-technology")
set_factoriopedia_description("technology", "fw-electromagnetic-architecture", "fw-electromagnetic-architecture-technology")
set_factoriopedia_description("technology", "fw-orbital-hardening", "fw-orbital-hardening-technology")
set_factoriopedia_description("technology", "fw-promethium-stabilization", "fw-promethium-stabilization-technology")
set_factoriopedia_description("technology", "fw-industrial-expansion", "fw-industrial-expansion-technology")
set_factoriopedia_description("technology", "fw-petrochemical-engineering", "fw-petrochemical-engineering-technology")
set_factoriopedia_description("technology", "fw-polymer-stabilization", "fw-polymer-stabilization-technology")
set_factoriopedia_description("technology", "fw-hydraulic-systems", "fw-hydraulic-systems-technology")
set_factoriopedia_description("technology", "fw-fluid-control-architecture", "fw-fluid-control-architecture-technology")
set_factoriopedia_description("technology", "fw-isotope-conditioning", "fw-isotope-conditioning-technology")
set_factoriopedia_description("technology", "fw-reactor-doping", "fw-reactor-doping-technology")
set_factoriopedia_description("technology", "fw-actinide-recovery", "fw-actinide-recovery-technology")
set_factoriopedia_description("technology", "fw-reactor-instrumentation", "fw-reactor-instrumentation-technology")
set_factoriopedia_description("technology", "fw-comminution", "fw-comminution-technology")
set_factoriopedia_description("technology", "fw-basic-separation", "fw-basic-separation-technology")
set_factoriopedia_description("technology", "fw-ore-crushing", "fw-ore-crushing-technology")
set_factoriopedia_description("technology", "fw-mineral-beneficiation", "fw-mineral-beneficiation-technology")
set_factoriopedia_description("technology", "fw-flux-extraction", "fw-flux-extraction-technology")
set_factoriopedia_description("technology", "fw-flux-mining-productivity", "fw-flux-mining-productivity-technology")
set_factoriopedia_description("technology", "fw-glassworking", "fw-glassworking-technology")
set_factoriopedia_description("technology", "fw-material-foundations", "fw-material-foundations-technology")
set_factoriopedia_description("technology", "fw-structural-fabrication", "fw-structural-fabrication-technology")
set_factoriopedia_description("technology", "fw-sealed-components", "fw-sealed-components-technology")
set_factoriopedia_description("technology", "fw-contact-casting", "fw-contact-casting-technology")
set_factoriopedia_description("technology", "fw-metals-fabrication", "fw-metals-fabrication-technology")
set_factoriopedia_description("technology", "fw-circuit-foundry", "fw-circuit-foundry-technology")
set_factoriopedia_description("technology", "fw-beam-engineering", "fw-beam-engineering-technology")
set_factoriopedia_description("technology", "fw-conductive-assembly", "fw-conductive-assembly-technology")
set_factoriopedia_description("technology", "fw-wafer-etching", "fw-wafer-etching-technology")
set_factoriopedia_description("technology", "fw-electromechanical-systems", "fw-electromechanical-systems-technology")
set_factoriopedia_description("technology", "fw-signal-architecture", "fw-signal-architecture-technology")
set_factoriopedia_description("technology", "fw-computational-arrays", "fw-computational-arrays-technology")
set_factoriopedia_description("technology", "fw-material-refinement", "fw-material-refinement-technology")
set_factoriopedia_description("technology", "fw-instrumentation", "fw-instrumentation-technology")
set_factoriopedia_description("technology", "fw-systems-integration", "fw-systems-integration-technology")
set_factoriopedia_description("technology", "fw-advanced-fabrication", "fw-advanced-fabrication-technology")
set_factoriopedia_description("technology", "fw-liquid-mining", "fw-liquid-mining-technology")
set_factoriopedia_description("technology", "fw-flux-catalysis", "fw-flux-catalysis-technology")
set_factoriopedia_description("technology", "fw-flux-yellow-catalysis", "fw-flux-yellow-catalysis-technology")
set_factoriopedia_description("technology", "fw-flux-stabilization", "fw-flux-stabilization-technology")
set_factoriopedia_description("technology", "fw-harvester-systems", "fw-harvester-systems-technology")
set_factoriopedia_description("technology", "fw-flux-structuring", "fw-flux-structuring-technology")
set_factoriopedia_description("technology", "fw-flux-red-energetics", "fw-flux-red-energetics-technology")
set_factoriopedia_description("technology", "fw-flux-green-reclamation", "fw-flux-green-reclamation-technology")
set_factoriopedia_description("technology", "fw-flux-metallurgy", "fw-flux-metallurgy-technology")
set_factoriopedia_description("technology", "fw-flux-resonance", "fw-flux-resonance-technology")
set_factoriopedia_description("technology", "fw-resonance-assemblies", "fw-resonance-assemblies-technology")
set_factoriopedia_description("technology", "fw-flux-asteroid-harvesting", "fw-flux-asteroid-harvesting-technology")
set_factoriopedia_description("technology", "fw-flux-field-theory", "fw-flux-field-theory-technology")
set_factoriopedia_description("technology", "fw-aquilo-cryochemistry", "fw-aquilo-cryochemistry-technology")
set_factoriopedia_description("technology", "fw-gleba-biochemistry", "fw-gleba-biochemistry-technology")
set_factoriopedia_description("technology", "fw-flux-chemical-synthesis", "fw-flux-chemical-synthesis-technology")
set_factoriopedia_description("technology", "fw-vulcanus-pyrochemistry", "fw-vulcanus-pyrochemistry-technology")
set_factoriopedia_description("technology", "fw-flux-reactive-slurries", "fw-flux-reactive-slurries-technology")
set_factoriopedia_description("technology", "fw-fulgora-electrochemistry", "fw-fulgora-electrochemistry-technology")
set_factoriopedia_description("technology", "fw-flux-green-cultivation", "fw-flux-green-cultivation-technology")
set_factoriopedia_description("technology", "fw-flux-green-propagation", "fw-flux-green-propagation-technology")
set_factoriopedia_description("technology", "fw-flux-thermal-networks", "fw-flux-thermal-networks-technology")
set_factoriopedia_description("technology", "fw-superconductive-systems", "fw-superconductive-systems-technology")
set_factoriopedia_description("technology", "fw-flux-phase-engineering", "fw-flux-phase-engineering-technology")
set_factoriopedia_description("technology", "fw-flux-synthesis", "fw-flux-synthesis-technology")
set_factoriopedia_description("technology", "fw-deep-phase-storage", "fw-deep-phase-storage-technology")
set_factoriopedia_description("technology", "fw-spectral-fluid-retention", "fw-spectral-fluid-retention-technology")
set_factoriopedia_description("technology", "fw-rift-logistics", "fw-rift-logistics-technology")
set_factoriopedia_description("technology", "fw-flux-overdrive", "fw-flux-overdrive-technology")
set_factoriopedia_description("technology", "fw-fusion-lattices", "fw-fusion-lattices-technology")
set_factoriopedia_description("technology", "fw-flux-convergence", "fw-flux-convergence-technology")
set_factoriopedia_description("technology", "fw-rift-harmonics", "fw-rift-harmonics-technology")
set_factoriopedia_description("technology", "fw-origin-infrastructure", "fw-origin-infrastructure-technology")
set_factoriopedia_description("technology", "fw-storm-megastructures", "fw-storm-megastructures-technology")
set_factoriopedia_description("technology", "fw-origin-transcendence", "fw-origin-transcendence-technology")
set_factoriopedia_description("technology", "fw-reactive-chemistry-productivity", "fw-reactive-chemistry-productivity-technology")
set_factoriopedia_description("technology", "fw-green-reclamation-productivity", "fw-green-reclamation-productivity-technology")
set_factoriopedia_description("technology", "fw-green-cultivation-productivity", "fw-green-cultivation-productivity-technology")
set_factoriopedia_description("technology", "fw-green-propagation-productivity", "fw-green-propagation-productivity-technology")
set_factoriopedia_description("technology", "fw-cryogenic-loop-productivity", "fw-cryogenic-loop-productivity-technology")
set_factoriopedia_description("technology", "fw-phase-assembly-productivity", "fw-phase-assembly-productivity-technology")
set_factoriopedia_description("technology", "fw-asteroid-refinement-productivity", "fw-asteroid-refinement-productivity-technology")

set_factoriopedia_simulation("resource", "fw-crystalised-flux", "fw_crystalised_flux")
set_factoriopedia_simulation("resource", "fw-metallic-deposit", "fw_metallic_deposit")
set_factoriopedia_simulation("resource", "fw-mineral-deposit", "fw_mineral_deposit")
set_factoriopedia_simulation("resource", "fw-carbonic-deposit", "fw_carbonic_deposit")
set_factoriopedia_simulation("resource", "fw-promethium-impact", "fw_promethium_impact")
set_factoriopedia_simulation("resource", "fw-silica-vein", "fw_silica_vein")
set_factoriopedia_simulation("item", "fw-flux-quarry", "fw_flux_quarry")
set_factoriopedia_simulation("mining-drill", "fw-flux-quarry", "fw_flux_quarry")
set_factoriopedia_simulation("item", "fw-flux-harvester", "fw_flux_harvester")
set_factoriopedia_simulation("assembling-machine", "fw-flux-harvester", "fw_flux_harvester")
set_factoriopedia_simulation("item", "fw-arc-foundry", "fw_arc_foundry")
set_factoriopedia_simulation("assembling-machine", "fw-arc-foundry", "fw_arc_foundry")
set_factoriopedia_simulation("item", "fw-synthesis-plant", "fw_synthesis_plant")
set_factoriopedia_simulation("assembling-machine", "fw-synthesis-plant", "fw_synthesis_plant")
set_factoriopedia_simulation("item", "fw-flux-condenser", "fw_flux_condenser")
set_factoriopedia_simulation("assembling-machine", "fw-flux-condenser", "fw_flux_condenser")
set_factoriopedia_simulation("item", "fw-petrochemical-facility", "fw_petrochemical_facility")
set_factoriopedia_simulation("assembling-machine", "fw-petrochemical-facility", "fw_petrochemical_facility")
set_factoriopedia_simulation("item", "fw-hydraulic-plant", "fw_hydraulic_plant")
set_factoriopedia_simulation("assembling-machine", "fw-hydraulic-plant", "fw_hydraulic_plant")
set_factoriopedia_simulation("item", "fw-atomic-enricher", "fw_atomic_enricher")
set_factoriopedia_simulation("assembling-machine", "fw-atomic-enricher", "fw_atomic_enricher")
set_factoriopedia_simulation("item", "remnant-beacon", "fw_orbital_salvage")
set_factoriopedia_simulation("radar", "remnant-beacon", "fw_orbital_salvage")
set_factoriopedia_simulation("technology", "rocket-chunk-processing", "fw_orbital_salvage")

for name, technology in pairs(data.raw.technology or {}) do
  if string.sub(name, 1, 3) == "fw-" and not (covered_descriptions.technology and covered_descriptions.technology[name]) then
    error("Missing FluxWorks Factoriopedia technology description: " .. name)
  end
end
